#!/bin/sh
# Set up CLASSPATH for webhead
# Finding the root folder for this Scala distribution



LIB=../java/lib



# Constructing the extension classpath
TOOL_CLASSPATH=""
if [ -z "$TOOL_CLASSPATH" ] ; then
    for ext in `ls -d "$LIB"/*.jar` ; do
        if [ -z "$TOOL_CLASSPATH" ] ; then
            TOOL_CLASSPATH="$ext"
        else
            TOOL_CLASSPATH="$TOOL_CLASSPATH:$ext"
        fi
    done
fi

/usr/local/scala/bin/scalac -cp $TOOL_CLASSPATH content.scala 
