#!/usr/bin/perl -w
#$Id$
#description: Create a tar of files specified in file named by $ARGV[0]
use strict qw (subs vars refs);
  die "No file specified"unless (-r $ARGV[0]);
open (INPUT, "$ARGV[0]") or die "could not open $ARGV[0] $!";
my @files =<INPUT>;
my $filenames = join (" ", @files);
$filenames =~ s/\s+/ /gm;
qx( tar cvf new.tar $filenames);
qx (gzip -9 new.tar);
print STDERR "Archived <$filenames> to new.tar.gz\n";
