* Executive Summary 

A combination of *ALSA*, *Ladspa* and *OpenAL* can provide an enhanced
headphone listening experience on Linux ---  this article summarizes
various tools and techniques for leveraging these affordances on the
Emacspeak Audio Desktop.

* Glossary 

  - ALSA :: Advanced Linux Sound Architecture. This is my  preferred
       means of controlling audio, and I entirely avoid Pulseaudio on
       all my machines.
  - Ladspa  ::   Linux Audio Developer's Simple Plugin API. Enables
       the injection of Digital Signal Processing (DSP)  when playing
       media. It is a layer that sits above *ALSA*. *Ladspa* filters
       can be  used by  user-space applications like *MPlayer* and
       *SoX* when playing media. They can also be used  within the
       user's *ASoundRC* to define virtual audio devices that inject
       DSP plugins into the media stream.
  - OpenAL ::  OpenAL is an API for enabling cross-platform 3D
       audio. User-space applications like *MPlayer* can use OpenAL as
       the audio output driver --- note that OpenAL on Linux writes to
       *ALSA* under the covers.

* Playing Media Using MPlayer 


1. With Ladspa and its associated plugins installed --- at the minimum
 I would recommend installing ~tap-plugins~, module
 ~emacspeak-m-player~ provides a number of affordances for
 interactively applying Ladspa filters. See commands
 _emacspeak-m-player-apply-reverb-preset_(bound to _P_ in ~M-Player~)
 and command _emacspeak-m-player-add-filter_ (bound to _f_ in
 ~M-Player~).
2. Command _emacspeak-m-player-apply-reverb-preset_ lets you pick
 among a total of 42 reverb presets defined by Ladspa module ~tap_reverb~.
3. Command _emacspeak-m-player-add-filter_ lets you add some of the
 more commonly used Ladspa effects with smart minibuffer
 prompts. Use tab completion to discover some of the predefined
 filters --- these are just convenience shortcuts --- and you can
 add  any filters you use commonly to this list.
4. Note that ~mplayer~ also has its own
  HRTF filter, but that  filter requires that the stream being played is
  a 48K stream.
5. Command _emacspeak-m-player-using-openal_ bound by default to
  _Hyper ;_ launches ~mplayer~ with _OpenAL_ as the audio output
  driver --- adding  the following line 
to your _~/.alsoftrc~ file will apply a suitable  HRTF filter for
augmented headphone listening. 
: hrtf=true

* Defining Virtual Audio Devices For Use With Soundscapes 

I use soundscapes to provide a pleasant auditory background as I work
--- see earlier blog article that describes [[http://emacspeak.blogspot.com/2015/12/soundscapes-on-emacspeak-audio-desktop.html][Soundscapes On The
Emacspeak Audio Desktop]]. Defining virtual ALSA devices that inject
Ladspa plugins into the output processing chain is an elegant means
for enhancing the auditory experience provided by these
soundscapes. In this instance, I apply one of the predefined reverb
effects (Ambiance) from Ladspa module ~tap-plugins~ and pass the
results through a BS2B (Bauer Stereo To Binaural) filter --- see file
[[https://github.com/tvraman/emacspeak/blob/master/scapes/ladspa-asoundrc][scapes/ladspa-asoundrc]] in the emacspeak Github Repo. Notice that that
file defines a number of virtual audio devices and can serve as a
template for injecting any installed Ladspa plugins --- you can first
experiment with filters using Emacspeak's  [[http://emacspeak.blogspot.com/2015/12/a-ladspa-work-bench-for-emacspeak.html][Laudible]] module to find
settings that work for you before applying them via a virtual device
defined in your ~asoundrc~ file. Finally, you can customize option
~soundscape-manager-options~  to add _--device <devicename>_ to have
the soundscapes use the desired virtual device.


* Summary 

Laptops today have plenty of processing power and some really nice
audio hardware.  Linux has a powerful audio processing stack in ALSA,
Ladspa and OpenAL. Connecting the dots can be fun and provide an
enhanced auditory environment.

#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t title:t toc:nil todo:t |:t
#+TITLE: Augmented Headphone Listening On Linux For The Emacspeak Audio Desktop
#+DATE: <2016-02-25 Thu>
#+AUTHOR: raman
#+EMAIL: raman@google.com
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.0.90.1 (Org mode 8.3.3)
