* Introduction

  1. Emacspeak, started in September 1994, was released as Open
   Source in [[https://tvraman.github.io/emacspeak//web/releases/release-3.0.html][April 1995]].
  2. [[https://emacspeak.sourceforge.net/turning-twenty.html][Emacspeak At Twenty]]  was published in September 2014 to trace the
     evolution of the project.
  3. Now, this article gives a birds-eye overview of the last 10 years
     by following the logical structure of the Turning-Twenty paper.
  4. In the process, we identify the dreams that have come to pass as
     well as the expectations that have failed to  materialize because
     of developments in the larger  Internet eco-system we live in.
  5. But never fear, though some of the above might be superficially
     disappointing, they likely herald the nature of bigger and better
     things to come.
  6. As a proof-point, in 1994, I could not have imagined the impact
     that the world of Internet-centric computing and the accompanying
     information revolution has had on the state of information
     access.
  7. Share And Enjoy --- [[https://tvraman.github.io/emacspeak/web/01-gemini.ogg ][The Best Is Yet To Come]]!


** How To Read This Document

  1. I recommend reading the /Turning Twenty/ paper to get a full overview.
  2. Then, read this paper a section at a time, while refering back to
     the parallel section in the /Turning Twenty/ paper.
  3. Make sure to skim or deep-dive into the references in both papers.
  

*  Using UNIX With Speech Output —  2024

  1. In 2024, Unix equates mostly to various Linux distros, and from
    the Emacspeak perspective, they are all made /mostly/ equal.
  2. Variations do exist and  running bleeding-edge distros can come
     with issues, e.g., unstable versions of the underlying audio framework.
  3. Yes, 30 years and counting, Linux Audio is still a work in
     progress though I hope Pipewire will be the last of these tidal shifts.
  4. Linux is moving to Wayland from X and expect that transition to
     be choppy.
  5. As with other platforms, /native apps/ are mostly gone bar the
     shouting; in that context, where the majority of users use most
     things through a /mainstream/ Web browser, Emacspeak users access
     /everything/ through Emacs.
  6. The above when things are done right is hugely empowering and
     enabling; when done badly, it's hugely disabling --- see later
     sections of this paper on  the continuing evolution of the Web.
     
* Key Enabler — Emacs And Lisp Advice

  1. Advice in Emacs is rock-solid.
  2. There is a newer /nadvice/ that is part of Emacs; Emacspeak does
     not use it.
  3. There are no plans to migrate to nadvice since that is a lot of
     busy work in my view and difficult to test any such migration.
  4. The classic /advice/ package may be removed from Emacs at some
     point in the future, but never fear; it'll be bundled with
     Emacspeak. This is a feature of Free Software and is a great
     example of what /Freedom/ means.
     
* Key Component —  Text To Speech (TTS)

  1. Speech output --- especially unencumbered text-to-speech is just
    as much a challenge as it was 30 years ago.
  2. Things appear to be coming full circle, Emacspeak started with
     the hardware Dectalk; now, the Software Dectalk is increasingly
     becoming the primary choice on Linux.
  3. Viavoice Outloud from Voxin is still supported (since 1999) but
     you can no longer buy new licenses; if you have a licence, it'll
     continue to work.
  4. The  Vocalizer voices that Voxin now sells /do not/ work with Emacspeak.
  5. The  other choice on Linux is ESpeak which will hopefully
     continue to be free -- albeit of much lower quality.
  6. The future as ever is unpredictable and new voices may well show
     up --- especially those powered by on-device LLMs as that
     technology progresses.
  7. On non-free platforms, there is usable TTS on the Mac, now
     supported by the new SwiftMac server for Emacspeak.
     
* Emacspeak And Software Development

  1. /Magit/  as a Git porcelain is perhaps the biggest leap forward
   with respect to software development  on Emacs.
  2. New completion frameworks such as /company/ and /consult/ come a
     close second in enhancing productivity.
  3. Packages like /transient/ that enable rapid keyboard access to
     complex nested-menu driven interfaces.
  4. Various plugin-in completion strategies such as /hotfuzz/ and
     /fuzz/ for fuzzy completion.
  5. IPython notebooks and their generalization to /Julia/, /Python/
     and /R/. The news here isn't all good; IPython notebooks are
     well-designed with respect to not getting locked into any given
     implementation. However in practice, all such environments depend
     on Javascript for interaction from within the browser. Today,
     many of Emacs' supporting environments for IPython Notebooks
     e.g., package ~ein~ are no longer maintained; hopefully there
     will be a new crop of packages to come in the future.
  6. Note that developing in languages like Python (~elpy~), ~R~,
     ~Clojure~ (~cider~), ~Scheme~, ~Racket~,  ~Ruby~ and numerous
     other high-level languages continues to be very well supported in Emacs.
  7. The re-emergence of Common Lisp in the last 20 years, thanks to
     ~asdf~ as a network-aware package management and build tool has
     once again made Lisp development using Emacs ~Slime~ a productive
     experience; as an example, I updated ~AsTeR~ --- my PhD project
     from 1993 to run under ~SBCL~ with  a freshly implemented Emacs
     front-end in late 2022.
  8. See the various relevant blog articles on the Emacspeak Blog for
     further context.
  9. Ergonomic keybindings under ~X~ using ~xcape~ to minimize
     chording has been  a significant win in the last two years.
     
     
* Emacspeak And Authoring Documents

  1. Package ~org~ and ~org-mode~ are to authoring as ~magit~ is to
    software development in terms of productivity gain.
  2. ~Org~ has existed since approx 2006 in my Emacs setup; but it
     continues to give and give plentifully.
  3. Where I one authored technical papers in LaTeX using ~auctex~, ~nxml~ for
     XML/HTML,  etc., I now mostly write everything in ~org-mode~ and export
     to the relevant target format.
  4. Integrating various search engines  in Emacs, with ~eww~
     providing  a consistent Emacs experience makes authoring content
      on the Emacspeak desktop extremely productive.
  5. Integrated access to dictionaries, translation engines, and other
     language tools rounds up the needed tools.
     
     
* Emacspeak  And The Web In 2024


  1. Package ~shr~ and ~eww~ arrived around 2014. But in 2024, they
    can be said to have *really* landed.
  2. The welcome re-emergence of ~ATOM~ and ~RSS~ feeds is perhaps a
     silent acknowledgement that bloated Web pages are  now unusable
     even for users who can see.
  3. Google Reader disappeared around 2012, but fortunately, ~elfeed~
     emerged as  a powerful feed-manager for Emacs.
  4. Emacspeak had already implemented ~RSS~ and ~ATOM~ support using
     ~XSLT~; but those features now shine even more with mainstream
     content sites reviving their support for content feeds.
  5. Package ~url-template~ and ~emacspeak-websearch~ continue to give
     in plenty, though they do require continuous updating.
  6. Web APIs come and go, usually  last for a few years, so in some
     sense that space is in steady state but contantly changing.
  7. Emacspeak support for rich multimedia is now much  more robust,
     see the next section.

* Audio Formatting —  Generalizing Aural CSS
  1. Audio formatting with Aural CSS support is stable, with
    enhancements with respect to supporting more TTS engines.
  2. Support for parallel streams of TTS using separate outputs to
     left/right channels is a big win and enables more efficient interaction.
  3. Support for various DSP filters makes Emacspeak a rich auditory environment.
  4. Soundscapes implemented via package ~boodler~ makes for  a
     pleasant and relaxing auditory environment.
  5. Enabling virtual sound devices via Pipewire for 5.1  and 7.1
     audio significantly enhances the environment.

     
* Conversational Gestures For The Audio Desktop

  1.  Parallel streams of audio, combined with more ergonomic
     keybindings are perhaps the only enhancement in this area.
     
* Accessing Media Streams

  1. First ~mplayer~ and now ~mpv~ signifcantly expand the
   multimedia streaming features of the Emacspeak desktop.
  2. Emacs package ~empv~ along with module ~emacspeak-empv~ is a
     powerful combination for locating, organizing  and playing local and remote
     media streams.
  3. This experience is augmented by a collection of /smart/ content
     locators on the Emacspeak desktop, see the relevant blog article
     on the Emacspeak Blog.
     
* EBooks—   Ubiquitous Access To Books

  1. Module ~emacspeak-epub~ for Epub and ~emacspeak-bookshare~ for
    Bookshare continue to provide good EBook integration.
  2. There are  /smart/ book locators analogous to the locators for
     media content.
     
* Leveraging Computational Tools —  From SQL And R To IPython Notebooks 
* Social Web  — EMail, Instant Messaging, Blogging  And Tweeting Using Open Protocols 
* The RESTful Web —  Web Wizards And URL Templates For Faster Access
* Mashing It Up —  Leveraging Evolving Web APIs
* Conclusion 
* References 

#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil expand-links:t f:t
#+options: inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+options: tasks:t tex:t timestamp:t title:t toc:nil todo:t |:t
#+title: 30 Years On: Emacspeak --- A Speech Odyssey
#+date: <2024-07-10 Wed>
#+author: T.V Raman
#+email: raman@google.com
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 31.0.50 (Org mode 9.7.6)
#+cite_export:
