(defun adventure ()
  (interactive)
  (comint-run "/usr/games/adventure")
  (unless emacspeak-comint-autospeak (emacspeak-toggle-comint-autospeak))
  (dtk-set-punctuations 'some)
  (when dtk-split-caps (dtk-toggle-split-caps))
  (emacspeak-auditory-icon 'open-object))
