(defun conditionally-enable-lispy ()
    (when (memq this-command '(eval-expression emacspeak-wizards-show-eval-result))
      (lispy-mode 1)))
(with-eval-after-load "lispy"
  (cl-declare (special lispy-mode-map lispy-mode-map-lispy))
  (define-key lispy-mode-map (kbd "M-m") nil)
  (define-key lispy-mode-map (kbd "C-y") 'emacspeak-muggles-yank-pop/yank)
  (define-key lispy-mode-map (kbd ";") 'self-insert-command)
  (define-key lispy-mode-map (kbd ":") 'self-insert-command)
  (define-key lispy-mode-map (kbd "M-;") 'lispy-comment)
  (define-key lispy-mode-map (kbd "C-d") 'delete-char)
  (define-key lispy-mode-map (kbd "M-C-d") 'lispy-delete)
  (define-key lispy-mode-map (kbd "M-d") 'kill-word)
  (define-key lispy-mode-map (kbd "M-e") 'lispy-move-end-of-line)
  (define-key lispy-mode-map "a" 'special-lispy-beginning-of-defun)
  (define-key lispy-mode-map "A" 'special-lispy-ace-symbol)
  (define-key lispy-mode-map (kbd "C-,") nil)
  (define-key lispy-mode-map [(control left)] 'lispy-barf)
  (define-key lispy-mode-map [(control right)] 'lispy-slurp)
  (define-key lispy-mode-map-lispy (kbd "C-,") nil)
;;;  Lispy for eval-expression:
  (add-hook 'minibuffer-setup-hook 'conditionally-enable-lispy))
