(with-eval-after-load "smartparens"
  (require 'smartparens-config)
  (sp-use-smartparens-bindings)
  (define-key  smartparens-mode-map "\C-\M-a" 'beginning-of-defun)
  (define-key  smartparens-mode-map "\C-\M-e" 'end-of-defun)
  (define-key  smartparens-mode-map "\C-\M-k" 'kill-sexp)
  (define-key smartparens-mode-map "\M-a" 'sp-backward-down-sexp)
  (define-key smartparens-mode-map "\M-e" 'sp-up-sexp)
  (define-key smartparens-mode-map "\M-k" 'sp-kill-sexp)
  (define-key smartparens-mode-map "\C-\M-f" 'forward-sexp)
  (define-key smartparens-mode-map "\C-\M-b" 'backward-sexp)
  (diminish 'smartparens-mode "" )
  )
