#!/bin/sh
#Upload a release to github
#Usage:  $1 tagname $2 filename asset (tar.bz2)

. ${HOME}/.github_token
export PATH=$PATH:$GOPATH/bin
github-release release --user tvraman --repo emacspeak \
--tag $1 --name "Release $1 " 

github-release upload --user tvraman --repo emacspeak \
--tag $1 --name $2 --file $2
github-release upload --user tvraman --repo emacspeak \
--tag $1 --name News-$2 --file ./etc/NEWS

echo "Released $1"
echo "Download URL: https://github.com/tvraman/emacspeak/releases/download/$1/$2"
