#!/bin/sh
EMACS=/home/raman/sourceforge/native-emacs/src/emacs
make config EMACS=$EMACS
make EMACS=$EMACS COMPILE='-f batch-byte-native-compile-for-bootstrap'
cd lisp
make EMACS=$EMACS COMPILE='-f batch-byte-native-compile-for-bootstrap' muggles --no-print-directory
make EMACS=$EMACS COMPILE='-f batch-byte-native-compile-for-bootstrap' extra-muggles --no-print-directory
