#!/bin/sh
#Run out of this directory.
# Default to using  espeak unless DTK_PROGRAM is set.
#
:${DTK_PROGRAM} ? "Using ${DTK_PROGRAM}" : export DTK_PROGRAM="espeak"
export EMACSPEAK_DIR=`pwd`
emacs "$&"

