#!/bin/sh

# install emacspeak keymaps
echo "Installing Emacspeak keymaps for future use."
sudo apt-get install console-data
cp emacspeak.enc.gz /usr/share/keymaps/i386/include/emacspeak.enc.gz 
cp emacspeak.kmap.gz /usr/share/keymaps/i386/qwerty/emacspeak.kmap.gz 
echo "Loading Emacspeak friendly keymaps."
sudo loadkeys /usr/share/keymaps/i386/qwerty/emacs2.kmap.gz
sudo loadkeys /usr/share/keymaps/i386/qwerty/emacspeak.kmap.gz
echo "Copying customized rc.local for future boots."

sudo cp ./rc.local  /etc/
sudo chmod 755 /etc/rc.local
echo "All done. "
