\input texinfo
@raggedright
@c$Id$
@setfilename./emacspeak.info 
@settitle Emacspeak User's Manual --2nd Edition.
@dircategory Accessibility
@dircategory Emacs
     @direntry
 * Emacspeak:(emacspeak).		Speech-enabled Audio Desktop.
@end direntry


@include preamble.texi
@include copyright.texi
@include announce.texi     
@include introduction.texi
@include install.texi
@include using.texi
@include audio-desktop.texi
@include online-help.texi
@include packages.texi
@include eterm.texi
@include commands.texi
@include options.texi
@include acknowledge.texi
@c trailer
     
@node Concept Index
@chapter Concept Index
@printindex cp

@node Key Index
@chapter Key Index
@printindex ky

@summarycontents
@contents
     
     @bye
