#!/bin/sh
# Lock screen 
sounds=/usr/share/sounds/ubuntu/stereo
ogg123 -q $sounds/service-logout.ogg &
#i3lock   -b  -d  && xbacklight -set 0
xbacklight -set 0
#xtrlock -b
gnome-screensaver-command -a  -l 

xbacklight -set 0
