#!/bin/sh
. ${HOME}/.bash_profile
export XLIB_SKIP_ARGB_VISUALS=1
# one-time action for 4k display:
xrandr --output eDP-1 --mode 1680x1050 
xset dpms 0 0 0
xmodmap $HOME/.xmodmap 
setxkbmap -option ctrl:nocaps #-option compose:rctrl
pidof ibus-daemon && pkill ibus-daemon

xrdb -merge $HOME/.Xresources &
xterm  -title Retriever -fullscreen &
export LISP=sbcl

#pidof ssh-agent && pkill ssh-agent
eval `ssh-agent -s`
eval $(/usr/bin/gnome-keyring-daemon --daemonize  --start --components =gpg,pkcs11,secrets,ssh)
export GPG_AGENT_INFO
export GNOME_KEYRING_PID  
${HOME}/bin/export_x_info &
light -S 5
mplayer -really-quiet   /home/raman/emacs/lisp/emacspeak/sounds/prompts/launch-wm.mp3 & 2>&1 > /dev/null
espeak-ng "Launching Window Manager" &
~/.fehbg & # wallpaper 
#ssh-agent dbus-launch --exit-with-session /usr/bin/gnome-session
ssh-agent dbus-launch --exit-with-session /usr/local/bin/stumpwm
#ssh-agent dbus-launch --exit-with-session /usr/local/bin/emacs
