#!/bin/sh
setxkbmap -option ctrl:nocaps
xmodmap $HOME/.xmodmap 
xrdb -merge $HOME/.Xresources &
xautolock -detectsleep -time 30  -locker  "$HOME/bin/xlock" & 
emacs  -title Emacs &
#xterm  -title Retriever &
export LISP=sbcl
${HOME}/bin/export_x_info &

dbus-launch --exit-with-session /usr/local/bin/stumpwm
#dbus-launch --exit-with-session emacs 
# exec gnome-session
