#!/bin/sh
export ALSA_DEFAULT=default
. ${HOME}/.bash_profile
export SSH_ASKPASS=/usr/local/bin/e-askpass.sh
export GNUBBY_PROMPT=/usr/local/bin/e-gnubbyprompt.sh
export XLIB_SKIP_ARGB_VISUALS=1
xmodmap $HOME/.xmodmap 
pidof ibus-daemon && pkill ibus-daemon
pidof ibus-daemon && ibus-daemon exit
#$HOME/emacs/lisp/emacspeak/tvr/xcape.sh
xset b 100 440
xset dpms
xset dpms 30 60 180
xrdb -merge $HOME/.Xresources &
