#!/bin/sh
#PreRequisites:
# install piper-tts using pipx:
#pipx install piper-tts
# Download the model to /usr/local/lib/piper/datasets
# See voice-urls.org for download urls.

#usage: pipspeak model device

PIP=/usr/local/lib/piper/datasets
MODEL=$1
DEV=$2

cd ${PIP}
piper -m en_US-$MODEL.onnx   --output-raw | \
aplay -D$DEV  -r 22050 -f S16_LE -t raw -
