#!/bin/sh
#PreRequisites:
# install piper-tts using pipx:
#pipx install piper-tts
# Download the model to /usr/local/lib/piper/datasets
# See voice-urls.org for download urls.

#usage: pipspeak model device
# where model is a fully-qualified path to the model.
# And device is an alsa device.

MODEL=$1
DEV=$2

piper -m $MODEL   --output-raw | \
aplay -D$DEV  -r 22050 -f S16_LE -t raw -
#  play -L -r 22050 -b 16 -c 1 -e signed-integer - # for sox
