#!/bin/bash
# Usage: ./bootstrap
# Downloads,  builds and runs specified version.
v=$1
if [ ! -n "$1" ]
then
  v=44.0
fi  


u="https://github.com/tvraman/emacspeak/releases/download/${v}/emacspeak-${v}.tar.bz2"
echo $u
