#!/bin/sh
# Build Emacs in your git checkout from
# git://git.savannah.gnu.org/emacs.git

#git reset --hard
git pull
export CCFLAGS="-O3"
export LDFLAGS="-O3"
export CPPFLAGS="-Ofast "
test -f Makefile || ./configure --enable-silent-rules  \
--without-native-compilation --without-xwidgets \
 --with-mailutils  --without-compress-install --with-pgtk
#make -j 8 V=0 bootstrap
make -j 2 V=0
