#!/bin/bash
# Description: Headless Chrome
set -x


pidof Xvfb ||  nice -n 15 Xvfb -ac :5 -screen 0 800x200x16 &
export DISPLAY=:5
nice -n 19 google-chrome-unstable  --remote-debugging-port=9222 "$@"  2>&1 > /dev/null &
