#!/bin/sh
#$Id$
#

if which pdftotext   > /dev/null
then
    tempfile=/tmp/pdftotext-$$.pdf
    cat > $tempfile
    pdftotext -layout $tempfile - | cat -s 
    rm -f $tempfile
    exit 0
else 
    echo "pdftotext not found --install package XPDF."
    exit 1
fi
