#!/bin/sh
# usage: remote-tts-setup server-script synthesizer-server remote-host
# starts a local server, then ssh to remote-host,
# and set up reverse port forwarding.
# Main speech server is on 2222
# Optionally, start notification stream on 3333
#Examples:
# remote-tts-setup speech-server outloud host.example.com
# remote-tts-setup 32-speech-server 32-outloud host.example.com

SDIR=<emacspeak_dir>
$SDIR/$1 2222 $SDIR/$2 &
# $SDIR/$1 3333 $SDIR/$2 &
beep -f 800 -l 50
ssh -R 2222:localhost:2222 -R 3333:localhost:3333 $3
