#!/bin/sh
# usage: remote-tts-setup server-script synthesizer-server remote-host
# starts a local server, then ssh to remote-host,
# and set up reverse port forwarding.
#Examples:
# remote-tts-setup speech-server outloud host.example.com
# remote-tts-setup 32-speech-server 32-outloud host.example.com

SDIR=$HOME/emacs/lisp/emacspeak/servers
$SDIR/$1 2222 $SDIR/$2 &
beep -f 800 -l 50
ssh -R 2222:localhost:2222 $3
