;;; Auto Generated: Do Not Hand Edit.

(autoload  'emacspeak-muggles-outliner/body "emacspeak-muggles" "emacspeak-muggles-outliner/body" t)
(global-set-key [3 46] 'emacspeak-muggles-outliner/body)
(autoload  'emacspeak-muggles-info-summary/body "emacspeak-muggles" "emacspeak-muggles-info-summary/body" t)
(autoload  'emacspeak-muggles-toggle-option/body "emacspeak-muggles" "emacspeak-muggles-toggle-option/body" t)
(global-set-key [3 111] 'emacspeak-muggles-toggle-option/body)
(autoload  'emacspeak-muggles-yank-pop/body "emacspeak-muggles" "emacspeak-muggles-yank-pop/body" t)
(autoload  'emacspeak-muggles-brightness/body "emacspeak-muggles" "emacspeak-muggles-brightness/body" t)
(global-set-key [print] 'emacspeak-muggles-brightness/body)
(autoload  'emacspeak-muggles-view/body "emacspeak-muggles" "emacspeak-muggles-view/body" t)
(global-set-key [3 118] 'emacspeak-muggles-view/body)
(autoload  'emacspeak-muggles-navigate/body "emacspeak-muggles" "emacspeak-muggles-navigate/body" t)
(global-set-key [8388718] 'emacspeak-muggles-navigate/body)
(autoload  'emacspeak-muggles-hideshow/body "emacspeak-muggles" "emacspeak-muggles-hideshow/body" t)
(global-set-key [3 104] 'emacspeak-muggles-hideshow/body)
(autoload  'emacspeak-muggles-org-table/body "emacspeak-muggles" "emacspeak-muggles-org-table/body" t)
(autoload  'emacspeak-muggles-maths-navigator/body "emacspeak-muggles" "emacspeak-muggles-maths-navigator/body" t)
(global-set-key [8388640] 'emacspeak-muggles-maths-navigator/body)
(autoload  'emacspeak-muggles-m-player/body "emacspeak-muggles" "emacspeak-muggles-m-player/body" t)
(global-set-key [8388667] 'emacspeak-muggles-m-player/body)
(autoload  'emacspeak-muggles-org-nav/body "emacspeak-muggles" "emacspeak-muggles-org-nav/body" t)
(provide 'emacspeak-muggles-autoloads)
