#!/bin/sh
# Use this server for emacs running in the cloud
# It just connects to local port 2222 
# It is assumed that the client has already done the appropriate
# reverse port forwarding.
# This also helps keeping the cloud environment simple:
# you dont need any flavor of TCL
telnet localhost 2222
