@node Emacspeak Commands
@chapter Emacspeak Commands

This chapter is generated automatically from the source-level documentation.
Any errors or corrections should be made to the source-level
documentation.
This chapter documents a total of 966 commands.

@menu
* cd-tool::
* dectalk-voices::
* dtk-speak::
* dtk-unicode::
* emacspeak-alsaplayer::
* emacspeak-amark::
* emacspeak-arc::
* emacspeak-aumix::
* emacspeak-bookshare::
* emacspeak-bs::
* emacspeak-buff-menu::
* emacspeak-c::
* emacspeak-calendar::
* emacspeak-compile::
* emacspeak-custom::
* emacspeak-dired::
* emacspeak-dismal::
* emacspeak-ecb::
* emacspeak-ediff::
* emacspeak-emms::
* emacspeak-enriched::
* emacspeak-entertain::
* emacspeak-eperiodic::
* emacspeak-epub::
* emacspeak-erc::
* emacspeak-eterm::
* emacspeak-eudc::
* emacspeak-feeds::
* emacspeak-filtertext::
* emacspeak-fix-interactive::
* emacspeak-forms::
* emacspeak-gnus::
* emacspeak-gomoku::
* emacspeak-google::
* emacspeak-gridtext::
* emacspeak-hide::
* emacspeak-ibuffer::
* emacspeak-imenu::
* emacspeak-info::
* emacspeak-jabber::
* emacspeak-keymap::
* emacspeak-librivox::
* emacspeak-loaddefs::
* emacspeak-m-player::
* emacspeak-madplay::
* emacspeak-man::
* emacspeak-mpg123::
* emacspeak-npr::
* emacspeak-ocr::
* emacspeak-outline::
* emacspeak-pianobar::
* emacspeak-pronounce::
* emacspeak-redefine::
* emacspeak-remote::
* emacspeak-rmail::
* emacspeak-solitaire::
* emacspeak-sounds::
* emacspeak-speak::
* emacspeak-speedbar::
* emacspeak-sudoku::
* emacspeak-table-ui::
* emacspeak-tabulate::
* emacspeak-tapestry::
* emacspeak-tar::
* emacspeak-tetris::
* emacspeak-tnt::
* emacspeak-url-template::
* emacspeak-view::
* emacspeak-vm::
* emacspeak-w3::
* emacspeak-w3m::
* emacspeak-we::
* emacspeak-websearch::
* emacspeak-webspace::
* emacspeak-webutils::
* emacspeak-widget::
* emacspeak-wizards::
* emacspeak-xml-shell::
* emacspeak-xslt::
* emacspeak-zinf::
* emacspeak::
* voice-setup::
* emacspeak-bbc::
* emacspeak-org::
* URL Templates ::
@end menu

@node cd-tool
@section cd-tool

Commentary:
Provide an emacs front-end to cdtool.
cdtool can be obtained as an rpm
check using rpmfind
or from its home site at
  sunsite.unc.edu /pub/Linux/apps/sound/cdrom/cli
This module also provides the ability to play or save
clips from a CD if you have cdda2wav installed.
cdda2wav is a cd to wav convertor.

Automatically generated documentation
for commands defined in module  cd-tool.

Caught cd-tool

@node dectalk-voices
@section dectalk-voices

Commentary:
This module defines the various voices used in voice-lock mode.
This module is Dectalk specific.

Automatically generated documentation
for commands defined in module  dectalk-voices.

Caught dtk-exp

@node dtk-speak
@section dtk-speak

Commentary:
Defines the TTS interface.

Automatically generated documentation
for commands defined in module  dtk-speak.

Caught dtk-add-cleanup-pattern
Caught dtk-async-server
Caught dtk-local-server
Caught dtk-pause
Caught dtk-reset-state
Caught dtk-resume
Caught dtk-select-server
Caught dtk-set-character-scale
Caught dtk-set-chunk-separator-syntax
Caught dtk-set-language
Caught dtk-set-next-language
Caught dtk-set-predefined-speech-rate
Caught dtk-set-preferred-language
Caught dtk-set-previous-language
Caught dtk-set-punctuations
Caught dtk-set-punctuations-to-all
Caught dtk-set-punctuations-to-some
Caught dtk-set-rate
Caught dtk-stop
Caught dtk-toggle-allcaps-beep
Caught dtk-toggle-capitalization
Caught dtk-toggle-debug
Caught dtk-toggle-punctuation-mode
Caught dtk-toggle-quiet
Caught dtk-toggle-speak-nonprinting-chars
Caught dtk-toggle-split-caps
Caught dtk-toggle-splitting-on-white-space
Caught dtk-toggle-strip-octals

@node dtk-unicode
@section dtk-unicode

Commentary:

This  Provides Unicode support to the speech layer.

Automatically generated documentation
for commands defined in module  dtk-unicode.

Caught dtk-unicode-customize-char
Caught dtk-unicode-uncustomize-char

@node emacspeak-alsaplayer
@section emacspeak-alsaplayer

Commentary:
Defines a simple derived mode for interacting with
alsaplayer.
alsaplayer navigation commands  work via single keystrokes.

Automatically generated documentation
for commands defined in module  emacspeak-alsaplayer.

Caught emacspeak-alsaplayer-add-to-queue
Caught emacspeak-alsaplayer-amark-add
Caught emacspeak-alsaplayer-amark-jump
Caught emacspeak-alsaplayer-backward-10-seconds
Caught emacspeak-alsaplayer-backward-minute
Caught emacspeak-alsaplayer-backward-ten-minutes
Caught emacspeak-alsaplayer-cd
Caught emacspeak-alsaplayer-clear
Caught emacspeak-alsaplayer-clip
Caught emacspeak-alsaplayer-find-and-add-to-queue
Caught emacspeak-alsaplayer-forward-10-seconds
Caught emacspeak-alsaplayer-forward-minute
Caught emacspeak-alsaplayer-forward-ten-minutes
Caught emacspeak-alsaplayer-info
Caught emacspeak-alsaplayer-jump
Caught emacspeak-alsaplayer-launch
Caught emacspeak-alsaplayer-mark-position
Caught emacspeak-alsaplayer-mode
Caught emacspeak-alsaplayer-next
Caught emacspeak-alsaplayer-pause
Caught emacspeak-alsaplayer-previous
Caught emacspeak-alsaplayer-quit
Caught emacspeak-alsaplayer-relative
Caught emacspeak-alsaplayer-replace-queue
Caught emacspeak-alsaplayer-seek
Caught emacspeak-alsaplayer-speed
Caught emacspeak-alsaplayer-start
Caught emacspeak-alsaplayer-status
Caught emacspeak-alsaplayer-stop
Caught emacspeak-alsaplayer-volume
Caught emacspeak-alsaplayer-where

@node emacspeak-amark
@section emacspeak-amark

Commentary:
Structure emacspeak-amark holds a bookmark into an mp3 file
path: fully qualified pathname  to file being marked
name: Bookmark tag
Position: time offset from start 

This library will be used from emacspeak-m-player,
emacspeak-alsaplayer and friends to set and jump to bookmarks.

Automatically generated documentation
for commands defined in module  emacspeak-amark.

Caught emacspeak-amark-add
Caught emacspeak-amark-find
Caught emacspeak-amark-load
Caught emacspeak-amark-save

@node emacspeak-arc
@section emacspeak-arc

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-arc.

Caught emacspeak-arc-speak-file-modification-time
Caught emacspeak-arc-speak-file-name
Caught emacspeak-arc-speak-file-permissions
Caught emacspeak-arc-speak-file-size

@node emacspeak-aumix
@section emacspeak-aumix

Commentary:
Provides an AUI to setting up the auditory display via AUMIX
This module is presently Linux specific

Automatically generated documentation
for commands defined in module  emacspeak-aumix.

Caught emacspeak-aumix-edit
Caught emacspeak-aumix-reset
Caught emacspeak-aumix-volume-decrease
Caught emacspeak-aumix-volume-increase
Caught emacspeak-aumix-wave-decrease
Caught emacspeak-aumix-wave-increase

@node emacspeak-bookshare
@section emacspeak-bookshare

Commentary:
BOOKSHARE == http://www.bookshare.org provides book access to print-disabled users.
It provides a simple Web  API http://developer.bookshare.org
This module implements an Emacspeak Bookshare client.
For now, users will need to get their own API key

Automatically generated documentation
for commands defined in module  emacspeak-bookshare.

Caught emacspeak-bookshare
Caught emacspeak-bookshare-action
Caught emacspeak-bookshare-author-search
Caught emacspeak-bookshare-browse
Caught emacspeak-bookshare-browse-latest
Caught emacspeak-bookshare-browse-popular
Caught emacspeak-bookshare-download-brf
Caught emacspeak-bookshare-download-brf-at-point
Caught emacspeak-bookshare-download-daisy
Caught emacspeak-bookshare-download-daisy-at-point
Caught emacspeak-bookshare-download-internal
Caught emacspeak-bookshare-eww
Caught emacspeak-bookshare-expand-at-point
Caught emacspeak-bookshare-extract-and-view
Caught emacspeak-bookshare-extract-xml
Caught emacspeak-bookshare-flush-lines
Caught emacspeak-bookshare-fulltext
Caught emacspeak-bookshare-fulltext-search
Caught emacspeak-bookshare-get-more-results
Caught emacspeak-bookshare-id-search
Caught emacspeak-bookshare-isbn-search
Caught emacspeak-bookshare-list-preferences
Caught emacspeak-bookshare-mode
Caught emacspeak-bookshare-next-result
Caught emacspeak-bookshare-periodical-list
Caught emacspeak-bookshare-previous-result
Caught emacspeak-bookshare-set-preference
Caught emacspeak-bookshare-sign-out
Caught emacspeak-bookshare-since-search
Caught emacspeak-bookshare-title-search
Caught emacspeak-bookshare-title/author-search
Caught emacspeak-bookshare-toc
Caught emacspeak-bookshare-toc-at-point
Caught emacspeak-bookshare-unpack-at-point
Caught emacspeak-bookshare-url-executor
Caught emacspeak-bookshare-version-handler
Caught emacspeak-bookshare-view
Caught emacspeak-bookshare-view-at-point
Caught emacspeak-bookshare-view-page-range

@node emacspeak-bs
@section emacspeak-bs

Commentary:
speech-enable bs.el -- an alternative to Emacs' default  list-buffers

Automatically generated documentation
for commands defined in module  emacspeak-bs.

Caught emacspeak-bs-speak-buffer-line

@node emacspeak-buff-menu
@section emacspeak-buff-menu

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-buff-menu.

Caught emacspeak-list-buffers-next-line
Caught emacspeak-list-buffers-previous-line
Caught emacspeak-list-buffers-speak-buffer-line
Caught emacspeak-list-buffers-speak-buffer-name

@node emacspeak-c
@section emacspeak-c

Commentary:
Make some of C and C++ mode more emacspeak friendly
Works with both boring c-mode
and the excellent cc-mode

Automatically generated documentation
for commands defined in module  emacspeak-c.

Caught emacspeak-c-speak-semantics

@node emacspeak-calendar
@section emacspeak-calendar

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-calendar.

Caught emacspeak-appt-repeat-announcement
Caught emacspeak-calendar-setup-sunrise-sunset
Caught emacspeak-calendar-speak-date

@node emacspeak-compile
@section emacspeak-compile

Commentary:
This module makes compiling code from inside Emacs speech friendly.
It is an example of how a little amount of code can make Emacspeak even better.

Automatically generated documentation
for commands defined in module  emacspeak-compile.

Caught emacspeak-compilation-speak-error

@node emacspeak-custom
@section emacspeak-custom

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-custom.

Caught emacspeak-custom-goto-group
Caught emacspeak-custom-goto-toolbar

@node emacspeak-dired
@section emacspeak-dired

Commentary:
This module speech enables dired.
It reduces the amount of speech you hear:
Typically you hear the file names as you move through the dired buffer
Voicification is used to indicate directories, marked files etc.

Automatically generated documentation
for commands defined in module  emacspeak-dired.

Caught emacspeak-dired-label-fields
Caught emacspeak-dired-show-file-type
Caught emacspeak-dired-speak-file-access-time
Caught emacspeak-dired-speak-file-modification-time
Caught emacspeak-dired-speak-file-permissions
Caught emacspeak-dired-speak-file-size
Caught emacspeak-dired-speak-header-line
Caught emacspeak-dired-speak-symlink-target

@node emacspeak-dismal
@section emacspeak-dismal

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-dismal.

Caught emacspeak-dismal-backward-col-and-summarize
Caught emacspeak-dismal-backward-row-and-summarize
Caught emacspeak-dismal-col-summarize
Caught emacspeak-dismal-display-cell-expression
Caught emacspeak-dismal-display-cell-value
Caught emacspeak-dismal-display-cell-with-col-header
Caught emacspeak-dismal-display-cell-with-row-header
Caught emacspeak-dismal-forward-col-and-summarize
Caught emacspeak-dismal-forward-row-and-summarize
Caught emacspeak-dismal-row-summarize
Caught emacspeak-dismal-set-col-summarizer-list
Caught emacspeak-dismal-set-row-summarizer-list
Caught emacspeak-dismal-set-sheet-summarizer-list
Caught emacspeak-dismal-sheet-summarize

@node emacspeak-ecb
@section emacspeak-ecb

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-ecb.

Caught emacspeak-ecb-speak-window-directories
Caught emacspeak-ecb-speak-window-history
Caught emacspeak-ecb-speak-window-methods
Caught emacspeak-ecb-speak-window-sources
Caught emacspeak-ecb-tree-backspace
Caught emacspeak-ecb-tree-clear
Caught emacspeak-ecb-tree-expand-common-prefix
Caught emacspeak-ecb-tree-shift-return

@node emacspeak-ediff
@section emacspeak-ediff

Commentary:
Ediff provides a nice visual interface to diff. ;;;Comparing and
patching files is easy with ediff when you can see the screen.
This module provides Emacspeak extensions to work fluently
with ediff. Try it out, it's an excellent example of why
Emacspeak is better than a traditional screenreader. This module
was originally written to interface to the old ediff.el bundled
with GNU Emacs 19.28 and earlier. It has been updated to work
with the newer and much larger ediff system found in Emacs 19.29
and later.

Automatically generated documentation
for commands defined in module  emacspeak-ediff.

Caught emacspeak-ediff-speak-current-difference

@node emacspeak-emms
@section emacspeak-emms

Commentary:
Speech-enables EMMS --- the Emacs equivalent of XMMS
See
http://savannah.gnu.org/project/emms
EMMS is under active development,
to get the current CVS version, use Emacspeak command
M-x emacspeak-cvs-gnu-get-project-snapshot RET emms RET

Automatically generated documentation
for commands defined in module  emacspeak-emms.

Caught emacspeak-emms-speak-current-track

@node emacspeak-enriched
@section emacspeak-enriched

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-enriched.

Caught emacspeak-enriched-voiceify-faces

@node emacspeak-entertain
@section emacspeak-entertain

Commentary:
Auditory interface to misc games

Automatically generated documentation
for commands defined in module  emacspeak-entertain.

Caught emacspeak-hangman-speak-guess
Caught emacspeak-hangman-speak-statistics

@node emacspeak-eperiodic
@section emacspeak-eperiodic

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-eperiodic.

Caught emacspeak-eperiodic-goto-property-section
Caught emacspeak-eperiodic-next-line
Caught emacspeak-eperiodic-play-description
Caught emacspeak-eperiodic-previous-line
Caught emacspeak-eperiodic-speak-current-element

@node emacspeak-epub
@section emacspeak-epub

Commentary:
In celebration of a million books and more to read from
Google Books
The EPubs format is slightly simpler than full Daisy ---
(see) emacspeak-daisy.el
Since it only needs one level of indirection (no audio,
therefore no smil). This module is consequently simpler than
emacspeak-daisy.el.
This module will eventually  implement the Google Books  API
--- probably by invoking the yet-to-be-written gbooks.el in emacs-g-client
As we move to epub-3, this module will bring back audio layers etc., perhaps via a simplified smil implementation.

Automatically generated documentation
for commands defined in module  emacspeak-epub.

Caught emacspeak-calibre-mode
Caught emacspeak-epub
Caught emacspeak-epub-bookshelf-add-directory
Caught emacspeak-epub-bookshelf-add-epub
Caught emacspeak-epub-bookshelf-calibre-author
Caught emacspeak-epub-bookshelf-calibre-search
Caught emacspeak-epub-bookshelf-calibre-title
Caught emacspeak-epub-bookshelf-clear
Caught emacspeak-epub-bookshelf-load
Caught emacspeak-epub-bookshelf-open
Caught emacspeak-epub-bookshelf-open-epub
Caught emacspeak-epub-bookshelf-redraw
Caught emacspeak-epub-bookshelf-refresh
Caught emacspeak-epub-bookshelf-remove-directory
Caught emacspeak-epub-bookshelf-remove-this-book
Caught emacspeak-epub-bookshelf-rename
Caught emacspeak-epub-bookshelf-save
Caught emacspeak-epub-browse-files
Caught emacspeak-epub-calibre-dired-at-point
Caught emacspeak-epub-calibre-results
Caught emacspeak-epub-delete
Caught emacspeak-epub-eww
Caught emacspeak-epub-fulltext
Caught emacspeak-epub-google
Caught emacspeak-epub-gutenberg-catalog
Caught emacspeak-epub-gutenberg-download
Caught emacspeak-epub-mode
Caught emacspeak-epub-next
Caught emacspeak-epub-open
Caught emacspeak-epub-previous
Caught emacspeak-epub-url-executor

@node emacspeak-erc
@section emacspeak-erc

Commentary:
erc.el is a modern Emacs client for IRC including color
and font locking support. 
erc.el - an Emacs IRC client (by Alexander L. Belikoff)
http://www.cs.cmu.edu/~berez/irc/erc.el

Automatically generated documentation
for commands defined in module  emacspeak-erc.

Caught emacspeak-erc-add-name-to-monitor
Caught emacspeak-erc-delete-name-from-monitor
Caught emacspeak-erc-setup-cricket-rules
Caught emacspeak-erc-toggle-my-monitor
Caught emacspeak-erc-toggle-room-monitor
Caught emacspeak-erc-toggle-speak-all-participants

@node emacspeak-eterm
@section emacspeak-eterm

Commentary:
This module makes eterm talk.
Eterm is the new terminal emulator for Emacs.
Use of emacspeak with eterm really needs an info page.
At present, the only documentation is the source level documentation.
This module uses Control-t as an additional prefix key to allow the user
To move around the terminal and have different parts spoken. 

Automatically generated documentation
for commands defined in module  emacspeak-eterm.

Caught emacspeak-eterm-copy-region-to-register
Caught emacspeak-eterm-define-window
Caught emacspeak-eterm-describe-window
Caught emacspeak-eterm-goto-line
Caught emacspeak-eterm-kill-ring-save-region
Caught emacspeak-eterm-maybe-send-raw
Caught emacspeak-eterm-paste-register
Caught emacspeak-eterm-pointer-backward-word
Caught emacspeak-eterm-pointer-down
Caught emacspeak-eterm-pointer-forward-word
Caught emacspeak-eterm-pointer-left
Caught emacspeak-eterm-pointer-right
Caught emacspeak-eterm-pointer-to-bottom
Caught emacspeak-eterm-pointer-to-cursor
Caught emacspeak-eterm-pointer-to-left-edge
Caught emacspeak-eterm-pointer-to-next-color-change
Caught emacspeak-eterm-pointer-to-previous-color-change
Caught emacspeak-eterm-pointer-to-right-edge
Caught emacspeak-eterm-pointer-to-top
Caught emacspeak-eterm-pointer-up
Caught emacspeak-eterm-remote-term
Caught emacspeak-eterm-search-backward
Caught emacspeak-eterm-search-forward
Caught emacspeak-eterm-set-filter-window
Caught emacspeak-eterm-set-focus-window
Caught emacspeak-eterm-set-marker
Caught emacspeak-eterm-speak-cursor
Caught emacspeak-eterm-speak-pointer
Caught emacspeak-eterm-speak-pointer-char
Caught emacspeak-eterm-speak-pointer-line
Caught emacspeak-eterm-speak-pointer-word
Caught emacspeak-eterm-speak-predefined-window
Caught emacspeak-eterm-speak-screen
Caught emacspeak-eterm-speak-window
Caught emacspeak-eterm-toggle-filter-window
Caught emacspeak-eterm-toggle-focus-window
Caught emacspeak-eterm-toggle-pointer-mode
Caught emacspeak-eterm-toggle-review
Caught emacspeak-eterm-yank-window
Caught emacspeak-toggle-eterm-autospeak

@node emacspeak-eudc
@section emacspeak-eudc

Commentary:
EUDC --Emacs Universal Directory Client 
provides a unified interface to directory servers
e.g. ldap servers
this module speech enables eudc 

Automatically generated documentation
for commands defined in module  emacspeak-eudc.

Caught emacspeak-eudc-send-mail

@node emacspeak-feeds
@section emacspeak-feeds

Commentary:
This module provides Feeds support for Emacspeak

Automatically generated documentation
for commands defined in module  emacspeak-feeds.

Caught emacspeak-feeds-add-feed
Caught emacspeak-feeds-archive-feeds
Caught emacspeak-feeds-atom-display
Caught emacspeak-feeds-browse
Caught emacspeak-feeds-fastload-feeds
Caught emacspeak-feeds-find-feeds
Caught emacspeak-feeds-lookup-and-view
Caught emacspeak-feeds-opml-display
Caught emacspeak-feeds-restoere-feeds
Caught emacspeak-feeds-rss-display

@node emacspeak-filtertext
@section emacspeak-filtertext

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-filtertext.

Caught emacspeak-filtertext
Caught emacspeak-filtertext-mode
Caught emacspeak-filtertext-revert

@node emacspeak-fix-interactive
@section emacspeak-fix-interactive

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-fix-interactive.

Caught emacspeak-fix-all-recent-commands
Caught emacspeak-fix-commands-loaded-from

@node emacspeak-forms
@section emacspeak-forms

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-forms.

Caught emacspeak-forms-find-file
Caught emacspeak-forms-flush-unwanted-records
Caught emacspeak-forms-rerun-filter
Caught emacspeak-forms-speak-field
Caught emacspeak-forms-summarize-current-position
Caught emacspeak-forms-summarize-current-record

@node emacspeak-gnus
@section emacspeak-gnus

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-gnus.

Caught emacspeak-gnus-summary-catchup-quietly-and-exit
Caught emacspeak-gnus-summary-hide-all-headers
Caught emacspeak-gnus-summary-show-some-headers

@node emacspeak-gomoku
@section emacspeak-gomoku

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-gomoku.

Caught emacspeak-gomoku-display-statistics
Caught emacspeak-gomoku-goto-x-y
Caught emacspeak-gomoku-show-current-column
Caught emacspeak-gomoku-show-current-negative-diagonal
Caught emacspeak-gomoku-show-current-positive-diagonal
Caught emacspeak-gomoku-show-current-row
Caught emacspeak-gomoku-speak-emacs-previous-move
Caught emacspeak-gomoku-speak-humans-previous-move
Caught emacspeak-gomoku-speak-number-of-moves
Caught emacspeak-gomoku-speak-square

@node emacspeak-google
@section emacspeak-google

Commentary:
There are a number of search tools that can be implemented on
the Google search page --- in a JS-powered browser, these
show up as the Google tool-belt.
This module implements a minor mode for use in Google result
pages that enables these tools via single keyboard commands.
Originally all options were available as tbs=p:v
Now, some specialized searches, e.g. blog search are tbm=

Automatically generated documentation
for commands defined in module  emacspeak-google.

Caught emacspeak-google-show-toolbelt
Caught emacspeak-google-sign-in
Caught emacspeak-google-sign-out
Caught emacspeak-google-toolbelt-change
Caught emacspeak-google-toolbelt-change-Shopping
Caught emacspeak-google-toolbelt-change-blog
Caught emacspeak-google-toolbelt-change-books
Caught emacspeak-google-toolbelt-change-books-format
Caught emacspeak-google-toolbelt-change-books-type
Caught emacspeak-google-toolbelt-change-books-viewability
Caught emacspeak-google-toolbelt-change-commercial
Caught emacspeak-google-toolbelt-change-commercial-prices
Caught emacspeak-google-toolbelt-change-date-filter
Caught emacspeak-google-toolbelt-change-discussions
Caught emacspeak-google-toolbelt-change-duration
Caught emacspeak-google-toolbelt-change-forums
Caught emacspeak-google-toolbelt-change-images
Caught emacspeak-google-toolbelt-change-literal
Caught emacspeak-google-toolbelt-change-news
Caught emacspeak-google-toolbelt-change-non-commercial
Caught emacspeak-google-toolbelt-change-patents
Caught emacspeak-google-toolbelt-change-places
Caught emacspeak-google-toolbelt-change-recent
Caught emacspeak-google-toolbelt-change-recipes
Caught emacspeak-google-toolbelt-change-reviews
Caught emacspeak-google-toolbelt-change-social
Caught emacspeak-google-toolbelt-change-sort-by-date
Caught emacspeak-google-toolbelt-change-structured-snippets
Caught emacspeak-google-toolbelt-change-timeline
Caught emacspeak-google-toolbelt-change-timeline-high
Caught emacspeak-google-toolbelt-change-timeline-low
Caught emacspeak-google-toolbelt-change-video
Caught emacspeak-google-toolbelt-change-web-history-not-visited
Caught emacspeak-google-toolbelt-change-web-history-visited

@node emacspeak-gridtext
@section emacspeak-gridtext

Commentary:
Emacspeak's table browsing mode allows one to
efficiently access  content that is tabular in nature.
That module also provides functions for infering table
structure where possible.
Often, such structure is hard to infer automatically
--but might be known to the user 
e.g. treat columns 1 through 30 as one column of a table
and so on.
This module allows the user to specify a conceptual grid
that is "overlaid" on the region of text to turn it into
a table for tabular browsing. For now, elements of the
grid are "one line" high --but that may change in the
future if necessary. This module is useful for browsing
structured text files and the output from programs that
tabulate their output.
It's also useful for handling multicolumn text.

Automatically generated documentation
for commands defined in module  emacspeak-gridtext.

Caught emacspeak-gridtext-apply
Caught emacspeak-gridtext-load
Caught emacspeak-gridtext-save

@node emacspeak-hide
@section emacspeak-hide

Commentary:
Flexible hide and show for emacspeak.
This module allows one to easily hide or expose
blocks of lines starting with a common prefix.
It is motivated by the need to flexibly hide quoted text in email
but is designed to be more general.
the prefix parsing is inspired by filladapt.el

Automatically generated documentation
for commands defined in module  emacspeak-hide.

Caught emacspeak-hide-or-expose-all-blocks
Caught emacspeak-hide-or-expose-block
Caught emacspeak-hide-speak-block-sans-prefix

@node emacspeak-ibuffer
@section emacspeak-ibuffer

Commentary:
speech-enable ibuffer.el
this is an alternative to buffer-menu

Automatically generated documentation
for commands defined in module  emacspeak-ibuffer.

Caught emacspeak-ibuffer-speak-buffer-line

@node emacspeak-imenu
@section emacspeak-imenu

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-imenu.

Caught emacspeak-imenu-goto-next-index-position
Caught emacspeak-imenu-goto-previous-index-position
Caught emacspeak-imenu-speak-this-section

@node emacspeak-info
@section emacspeak-info

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-info.

Caught emacspeak-info-speak-header
Caught emacspeak-info-wizard

@node emacspeak-jabber
@section emacspeak-jabber

Commentary:
emacs-jabber.el implements a  jabber client for emacs
emacs-jabber is hosted at sourceforge.
I use emacs-jabber with my gmail.com account

Automatically generated documentation
for commands defined in module  emacspeak-jabber.

Caught emacspeak-jabber-chat-next-message
Caught emacspeak-jabber-chat-previous-message
Caught emacspeak-jabber-chat-speak-this-message
Caught emacspeak-jabber-popup-roster

@node emacspeak-keymap
@section emacspeak-keymap

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-keymap.

Caught emacspeak-keymap-choose-new-emacspeak-prefix

@node emacspeak-librivox
@section emacspeak-librivox

Commentary:
LIBRIVOX == http://wwwlibrivox.org Free Audio Books
It provides a simple Web  API http://wiki.librivox.org/index.php/LibriVoxAPI
This module implements an Emacspeak Librivox client.

Automatically generated documentation
for commands defined in module  emacspeak-librivox.

Caught emacspeak-librivox
Caught emacspeak-librivox-fetch-catalog
Caught emacspeak-librivox-mode
Caught emacspeak-librivox-open-rss
Caught emacspeak-librivox-open-url
Caught emacspeak-librivox-play
Caught emacspeak-librivox-search-author
Caught emacspeak-librivox-search-genre
Caught emacspeak-librivox-search-title

@node emacspeak-loaddefs
@section emacspeak-loaddefs

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-loaddefs.

Caught emacspeak-mark-forward-mark
Caught emacspeak-toggle-comint-output-monitor

@node emacspeak-m-player
@section emacspeak-m-player

Commentary:
Defines a simple derived mode for interacting with mplayer.
mplayer  is a versatile media player capable of playing many
streaming formats  and is especially useful for playing windows
media (WMA) and streaming windows media (ASF) files.
mplayer is available  on the WWW:
RPM package
http://mirrors.sctpc.com/dominik/linux/pkgs/mplayer/i586/mplayer-0.90pre5-2.i586.rpm
You may need the  win32 codecs which can be downloaded from 
http://ftp.lug.udel.edu/MPlayer/releases/w32codec-0.60.tar.bz2
Mplayer FAQ at
http://www.mplayerhq.hu/DOCS/faq.html
Mplayer docs at 
http://www.mplayerhq.hu/DOCS/

Automatically generated documentation
for commands defined in module  emacspeak-m-player.

Caught emacspeak-m-player-add-equalizer
Caught emacspeak-m-player-add-filter
Caught emacspeak-m-player-alt-src-step
Caught emacspeak-m-player-backward-10min
Caught emacspeak-m-player-backward-10s
Caught emacspeak-m-player-backward-1min
Caught emacspeak-m-player-balance
Caught emacspeak-m-player-beginning-of-track
Caught emacspeak-m-player-bind-accelerator
Caught emacspeak-m-player-command
Caught emacspeak-m-player-customize-options
Caught emacspeak-m-player-display-position
Caught emacspeak-m-player-double-speed
Caught emacspeak-m-player-end-of-track
Caught emacspeak-m-player-equalizer-control
Caught emacspeak-m-player-faster
Caught emacspeak-m-player-forward-10min
Caught emacspeak-m-player-forward-10s
Caught emacspeak-m-player-forward-1min
Caught emacspeak-m-player-get-length
Caught emacspeak-m-player-half-speed
Caught emacspeak-m-player-load
Caught emacspeak-m-player-load-file
Caught emacspeak-m-player-load-playlist
Caught emacspeak-m-player-mode
Caught emacspeak-m-player-next-track
Caught emacspeak-m-player-pause
Caught emacspeak-m-player-play-tracks-jump
Caught emacspeak-m-player-play-tree-up
Caught emacspeak-m-player-previous-track
Caught emacspeak-m-player-quit
Caught emacspeak-m-player-reset-options
Caught emacspeak-m-player-reset-speed
Caught emacspeak-m-player-resume
Caught emacspeak-m-player-scale-speed
Caught emacspeak-m-player-seek-absolute
Caught emacspeak-m-player-seek-relative
Caught emacspeak-m-player-shuffle
Caught emacspeak-m-player-slave-command
Caught emacspeak-m-player-slower
Caught emacspeak-m-player-speak-current-info
Caught emacspeak-m-player-speak-mode-line
Caught emacspeak-m-player-url
Caught emacspeak-m-player-volume-change
Caught emacspeak-m-player-volume-down
Caught emacspeak-m-player-volume-up
Caught emacspeak-m-player-youtube-player
Caught emacspeak-multimedia

@node emacspeak-madplay
@section emacspeak-madplay

Commentary:
Defines a simple derived mode for interacting with
madplay.
madplay navigation commands  work via single keystrokes.

Automatically generated documentation
for commands defined in module  emacspeak-madplay.

Caught emacspeak-aumix
Caught emacspeak-madplay
Caught emacspeak-madplay-madplay-call-command
Caught emacspeak-madplay-madplay-command
Caught emacspeak-madplay-mode

@node emacspeak-man
@section emacspeak-man

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-man.

Caught emacspeak-man-browse-man-page
Caught emacspeak-man-speak-this-section

@node emacspeak-mpg123
@section emacspeak-mpg123

Commentary:
This module speech-enables  MPG123
MPG123 is an MP3 player.

Automatically generated documentation
for commands defined in module  emacspeak-mpg123.

Caught emacspeak-mp3-playlist-play
Caught emacspeak-mp3-playlist-skip
Caught emacspeak-mp3-playlist-stop
Caught emacspeak-mpg123-backward-minute
Caught emacspeak-mpg123-forward-minute
Caught emacspeak-mpg123-speak-current-time
Caught emacspeak-mpg123-speak-filename
Caught emacspeak-mpg123-speak-length
Caught emacspeak-mpg123-speak-title

@node emacspeak-npr
@section emacspeak-npr

Commentary:
NPR == http://wwwnpr.org National Public Radio in the US
It provides a simple Web  API http://www.npr.org/api/
This module implements an Emacspeak Npr client.

For now, users will need to get their own API key

Automatically generated documentation
for commands defined in module  emacspeak-npr.

Caught emacspeak-npr-listing
Caught emacspeak-npr-listing-url-executor
Caught emacspeak-npr-view

@node emacspeak-ocr
@section emacspeak-ocr

Commentary:
This module defines Emacspeak front-end to OCR.
This module assumes that sane is installed and working
for image acquisition,
and that there is an OCR engine that can take acquired
images and produce text.
Prerequisites:
Sane installed and working.
scanimage to generate tiff files from scanner.
tiffcp to compress the tiff file.
working ocr executable 
by default this module assumes that the OCR executable
is named "ocr"

Automatically generated documentation
for commands defined in module  emacspeak-ocr.

Caught emacspeak-ocr
Caught emacspeak-ocr-backward-page
Caught emacspeak-ocr-customize
Caught emacspeak-ocr-flipflop-and-recognize-image
Caught emacspeak-ocr-forward-page
Caught emacspeak-ocr-mode
Caught emacspeak-ocr-name-document
Caught emacspeak-ocr-open-working-directory
Caught emacspeak-ocr-page
Caught emacspeak-ocr-read-current-page
Caught emacspeak-ocr-recognize-image
Caught emacspeak-ocr-save-current-page
Caught emacspeak-ocr-scan-and-recognize
Caught emacspeak-ocr-scan-image
Caught emacspeak-ocr-scan-photo
Caught emacspeak-ocr-set-compress-image-options
Caught emacspeak-ocr-set-scan-image-options
Caught emacspeak-ocr-write-document

@node emacspeak-outline
@section emacspeak-outline

Commentary:
Provide additional advice to outline-mode

Automatically generated documentation
for commands defined in module  emacspeak-outline.

Caught emacspeak-outline-speak-backward-heading
Caught emacspeak-outline-speak-forward-heading
Caught emacspeak-outline-speak-next-heading
Caught emacspeak-outline-speak-previous-heading
Caught emacspeak-outline-speak-this-heading

@node emacspeak-pianobar
@section emacspeak-pianobar

Commentary:
PIANOBAR ==  Pandora Client for Emacs

pianobar git://github.com/PromyLOPh/pianobar.git
Is a stand-alone client for Pandora Radio.
pianobar.el available on the Emacs Wiki at
http://www.emacswiki.org/emacs/pianobar.el
Provides access to Pandora Radio via pianobar from the comfort of Emacs.
This module speech-enables Pianobar and enhances it for the Complete Audio Desktop.

Automatically generated documentation
for commands defined in module  emacspeak-pianobar.

Caught emacspeak-pianobar
Caught emacspeak-pianobar-command
Caught emacspeak-pianobar-electric-mode-toggle
Caught emacspeak-pianobar-switch-to-preset

@node emacspeak-pronounce
@section emacspeak-pronounce

Commentary:
This module implements user customizable pronunciation dictionaries
for emacspeak. Custom pronunciations can be defined per file, per
directory and/or per major mode. Emacspeak maintains a persistent
user dictionary upon request and loads these in new emacspeak
sessions. This module implements the user interface to the custom
dictionary as well as providing the internal API used by the rest
of emacspeak in using the dictionary.
Algorithm:

The persistent dictionary is a hash table where the hash keys are
filenames, directory names, or major-mode names. The hash values
are association lists defining the dictionary. Users of this module
can retrieve a dictionary made up of all applicable association
lists for a given file.

Automatically generated documentation
for commands defined in module  emacspeak-pronounce.

Caught emacspeak-pronounce-clear-dictionaries
Caught emacspeak-pronounce-define-local-pronunciation
Caught emacspeak-pronounce-define-pronunciation
Caught emacspeak-pronounce-define-template-pronunciation
Caught emacspeak-pronounce-dispatch
Caught emacspeak-pronounce-edit-pronunciations
Caught emacspeak-pronounce-load-dictionaries
Caught emacspeak-pronounce-refresh-pronunciations
Caught emacspeak-pronounce-save-dictionaries
Caught emacspeak-pronounce-toggle-use-of-dictionaries
Caught emacspeak-pronounce-yank-word

@node emacspeak-redefine
@section emacspeak-redefine

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-redefine.

Caught emacspeak-backward-char
Caught emacspeak-forward-char
Caught emacspeak-self-insert-command

@node emacspeak-remote
@section emacspeak-remote

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-remote.

Caught emacspeak-remote-connect-to-server
Caught emacspeak-remote-edit-current-remote-hostname
Caught emacspeak-remote-home
Caught emacspeak-remote-quick-connect-to-server
Caught emacspeak-remote-quick-connect-via-ssh
Caught emacspeak-remote-ssh-to-server

@node emacspeak-rmail
@section emacspeak-rmail

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-rmail.

Caught emacspeak-rmail-speak-current-message-labels
Caught emacspeak-rmail-summarize-current-message

@node emacspeak-solitaire
@section emacspeak-solitaire

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-solitaire.

Caught emacspeak-solitaire-show-column
Caught emacspeak-solitaire-show-row
Caught emacspeak-solitaire-speak-coordinates

@node emacspeak-sounds
@section emacspeak-sounds

Commentary:
This module provides the interface for generating auditory icons in emacspeak.
Design goal:
1) Auditory icons should be used to provide additional feedback,
not as a gimmick.
2) The interface should be usable at all times without the icons:
e.g. when on a machine without a sound card.
3) General principle for when to use an icon:
Convey information about events taking place in parallel.
For instance, if making a selection automatically moves the current focus
to the next choice,
We speak the next choice, while indicating the fact that something was selected with a sound cue.
 This interface will assume the availability of a shell command "play"
that can take one or more sound files and play them.
This module will also provide a mapping between names in the elisp world and actual sound files.
Modules that wish to use auditory icons should use these names, instead of actual file names.
As of Emacspeak 13.0, this module defines a themes
architecture for  auditory icons.
Sound files corresponding to a given theme are found in
appropriate subdirectories of emacspeak-sounds-directory

Automatically generated documentation
for commands defined in module  emacspeak-sounds.

Caught emacspeak-audio-setup
Caught emacspeak-play-all-icons
Caught emacspeak-set-auditory-icon-player
Caught emacspeak-sounds-reset-local-player
Caught emacspeak-sounds-reset-sound
Caught emacspeak-sounds-select-theme
Caught emacspeak-toggle-auditory-icons

@node emacspeak-speak
@section emacspeak-speak

Commentary:
This module defines the core speech services used by emacspeak.
It depends on the speech server interface modules
It protects other parts of emacspeak
from becoming dependent on the speech server modules

Automatically generated documentation
for commands defined in module  emacspeak-speak.

Caught emacspeak-blink-matching-open
Caught emacspeak-completion-pick-completion
Caught emacspeak-completions-move-to-completion-group
Caught emacspeak-dial-dtk
Caught emacspeak-execute-repeatedly
Caught emacspeak-goto-percent
Caught emacspeak-mark-backward-mark
Caught emacspeak-owindow-next-line
Caught emacspeak-owindow-previous-line
Caught emacspeak-owindow-scroll-down
Caught emacspeak-owindow-scroll-up
Caught emacspeak-owindow-speak-line
Caught emacspeak-read-next-line
Caught emacspeak-read-next-word
Caught emacspeak-read-previous-line
Caught emacspeak-read-previous-word
Caught emacspeak-search
Caught emacspeak-shell-command
Caught emacspeak-silence
Caught emacspeak-speak-and-skip-extent-upto-char
Caught emacspeak-speak-and-skip-extent-upto-this-char
Caught emacspeak-speak-browse-buffer
Caught emacspeak-speak-buffer
Caught emacspeak-speak-buffer-filename
Caught emacspeak-speak-buffer-interactively
Caught emacspeak-speak-char
Caught emacspeak-speak-char-name
Caught emacspeak-speak-completions-if-available
Caught emacspeak-speak-continuously
Caught emacspeak-speak-current-column
Caught emacspeak-speak-current-field
Caught emacspeak-speak-current-kill
Caught emacspeak-speak-current-mark
Caught emacspeak-speak-current-percentage
Caught emacspeak-speak-current-window
Caught emacspeak-speak-display-char
Caught emacspeak-speak-face-interval-and-move
Caught emacspeak-speak-front-of-buffer
Caught emacspeak-speak-header-line
Caught emacspeak-speak-help
Caught emacspeak-speak-help-interactively
Caught emacspeak-speak-hostname
Caught emacspeak-speak-line
Caught emacspeak-speak-line-interactively
Caught emacspeak-speak-line-number
Caught emacspeak-speak-line-set-column-filter
Caught emacspeak-speak-load-directory-settings
Caught emacspeak-speak-message-again
Caught emacspeak-speak-message-at-time
Caught emacspeak-speak-microseconds-since-epoch
Caught emacspeak-speak-milliseconds-since-epoch
Caught emacspeak-speak-minibuffer
Caught emacspeak-speak-minor-mode-line
Caught emacspeak-speak-mode-line
Caught emacspeak-speak-next-face-chunk
Caught emacspeak-speak-next-field
Caught emacspeak-speak-next-personality-chunk
Caught emacspeak-speak-next-window
Caught emacspeak-speak-other-buffer
Caught emacspeak-speak-other-window
Caught emacspeak-speak-page
Caught emacspeak-speak-page-interactively
Caught emacspeak-speak-paragraph
Caught emacspeak-speak-paragraph-interactively
Caught emacspeak-speak-preceding-char
Caught emacspeak-speak-predefined-window
Caught emacspeak-speak-previous-face-chunk
Caught emacspeak-speak-previous-field
Caught emacspeak-speak-previous-personality-chunk
Caught emacspeak-speak-previous-window
Caught emacspeak-speak-rectangle
Caught emacspeak-speak-region
Caught emacspeak-speak-rest-of-buffer
Caught emacspeak-speak-seconds-since-epoch
Caught emacspeak-speak-sentence
Caught emacspeak-speak-set-display-table
Caught emacspeak-speak-set-mode-punctuations
Caught emacspeak-speak-sexp
Caught emacspeak-speak-sexp-interactively
Caught emacspeak-speak-show-active-network-interfaces
Caught emacspeak-speak-skim-buffer
Caught emacspeak-speak-skim-next-paragraph
Caught emacspeak-speak-skim-paragraph
Caught emacspeak-speak-spaces-at-point
Caught emacspeak-speak-spell-current-word
Caught emacspeak-speak-text-range
Caught emacspeak-speak-this-face-chunk
Caught emacspeak-speak-this-personality-chunk
Caught emacspeak-speak-time
Caught emacspeak-speak-version
Caught emacspeak-speak-voice-annotate-paragraphs
Caught emacspeak-speak-window-information
Caught emacspeak-speak-word
Caught emacspeak-speak-word-interactively
Caught emacspeak-speak-world-clock
Caught emacspeak-switch-to-reference-buffer
Caught emacspeak-toggle-action-mode
Caught emacspeak-toggle-audio-indentation
Caught emacspeak-toggle-character-echo
Caught emacspeak-toggle-comint-autospeak
Caught emacspeak-toggle-header-line
Caught emacspeak-toggle-line-echo
Caught emacspeak-toggle-mail-alert
Caught emacspeak-toggle-show-point
Caught emacspeak-toggle-speak-line-invert-filter
Caught emacspeak-toggle-speak-messages
Caught emacspeak-toggle-word-echo
Caught emacspeak-use-customized-blink-paren
Caught emacspeak-voiceify-rectangle
Caught emacspeak-voiceify-region
Caught emacspeak-zap-tts

@node emacspeak-speedbar
@section emacspeak-speedbar

Commentary:
This module advises speedbar.el for use with Emacs.  The
latest speedbar can be obtained from
ftp://ftp.ultranet.com/pub/zappo/ This module ensures
that speedbar works smoothly outside a windowing system
in addition to speech enabling all interactive
commands. Emacspeak also adds an Emacspeak environment
specific entry point to speedbar
--emacspeak-speedbar-goto-speedbar-- and binds this

Automatically generated documentation
for commands defined in module  emacspeak-speedbar.

Caught emacspeak-speedbar-click
Caught emacspeak-speedbar-goto-speedbar

@node emacspeak-sudoku
@section emacspeak-sudoku

Commentary:
Playing SuDoku using speech output.
Written to discover what type of feedback one needs for  this
task.
See http://emacspeak.blogspot.com/2006/02/playing-sudoku-using-auditory-feedback.html

Automatically generated documentation
for commands defined in module  emacspeak-sudoku.

Caught emacspeak-sudoku-board-columns-summarize
Caught emacspeak-sudoku-board-distribution-summarize
Caught emacspeak-sudoku-board-rows-summarize
Caught emacspeak-sudoku-board-sub-squares-summarize
Caught emacspeak-sudoku-board-summarizer
Caught emacspeak-sudoku-down-sub-square
Caught emacspeak-sudoku-erase-current-column
Caught emacspeak-sudoku-erase-current-row
Caught emacspeak-sudoku-erase-current-sub-square
Caught emacspeak-sudoku-hint
Caught emacspeak-sudoku-history-pop
Caught emacspeak-sudoku-history-push
Caught emacspeak-sudoku-how-many-remaining
Caught emacspeak-sudoku-next-sub-square
Caught emacspeak-sudoku-previous-sub-square
Caught emacspeak-sudoku-speak-current-cell-coordinates
Caught emacspeak-sudoku-speak-current-cell-value
Caught emacspeak-sudoku-speak-current-column
Caught emacspeak-sudoku-speak-current-row
Caught emacspeak-sudoku-speak-current-sub-square
Caught emacspeak-sudoku-speak-remaining-in-column
Caught emacspeak-sudoku-speak-remaining-in-row
Caught emacspeak-sudoku-speak-remaining-in-sub-square
Caught emacspeak-sudoku-up-sub-square

@node emacspeak-table-ui
@section emacspeak-table-ui

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-table-ui.

Caught emacspeak-table-copy-current-element-to-kill-ring
Caught emacspeak-table-copy-current-element-to-register
Caught emacspeak-table-copy-to-clipboard
Caught emacspeak-table-display-table-in-region
Caught emacspeak-table-find-csv-file
Caught emacspeak-table-find-file
Caught emacspeak-table-get-entry-with-headers
Caught emacspeak-table-goto
Caught emacspeak-table-goto-bottom
Caught emacspeak-table-goto-left
Caught emacspeak-table-goto-right
Caught emacspeak-table-goto-top
Caught emacspeak-table-next-column
Caught emacspeak-table-next-row
Caught emacspeak-table-paste-from-clipboard
Caught emacspeak-table-previous-column
Caught emacspeak-table-previous-row
Caught emacspeak-table-search
Caught emacspeak-table-search-column
Caught emacspeak-table-search-headers
Caught emacspeak-table-search-row
Caught emacspeak-table-select-automatic-speaking-method
Caught emacspeak-table-sort-on-current-column
Caught emacspeak-table-speak-both-headers-and-element
Caught emacspeak-table-speak-column-filtered
Caught emacspeak-table-speak-column-header-and-element
Caught emacspeak-table-speak-coordinates
Caught emacspeak-table-speak-current-element
Caught emacspeak-table-speak-dimensions
Caught emacspeak-table-speak-row-filtered
Caught emacspeak-table-speak-row-header-and-element
Caught emacspeak-table-ui-filter-load
Caught emacspeak-table-ui-filter-save
Caught emacspeak-table-view-csv-buffer

@node emacspeak-tabulate
@section emacspeak-tabulate

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-tabulate.

Caught emacspeak-tabulate-region

@node emacspeak-tapestry
@section emacspeak-tapestry

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-tapestry.

Caught emacspeak-tapestry-describe-tapestry
Caught emacspeak-tapestry-select-window-by-name

@node emacspeak-tar
@section emacspeak-tar

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-tar.

Caught emacspeak-tar-speak-file-date
Caught emacspeak-tar-speak-file-permissions
Caught emacspeak-tar-speak-file-size

@node emacspeak-tetris
@section emacspeak-tetris

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-tetris.

Caught emacspeak-tetris-goto-bottom-row
Caught emacspeak-tetris-goto-top-row
Caught emacspeak-tetris-speak-column
Caught emacspeak-tetris-speak-coordinates
Caught emacspeak-tetris-speak-current-shape
Caught emacspeak-tetris-speak-current-shape-and-coordinates
Caught emacspeak-tetris-speak-next-shape
Caught emacspeak-tetris-speak-row
Caught emacspeak-tetris-speak-row-number
Caught emacspeak-tetris-speak-score
Caught emacspeak-tetris-speak-x-coordinate

@node emacspeak-tnt
@section emacspeak-tnt

Commentary:
Speech-enables TNT -- the Emacs AOL Instant Messenger
client 

Automatically generated documentation
for commands defined in module  emacspeak-tnt.

Caught emacspeak-tnt-toggle-autospeak

@node emacspeak-url-template
@section emacspeak-url-template

Commentary:
It is often useful to have ``parametrized hot list entries''
i.e., hotlist entries  that are ``templates'' for the
actual URL.
The user provides values for the parametrized portions
of the URL e.g. the date.
See @xref{URL Templates}, for details on the URL templates
that are presently defined.

Automatically generated documentation
for commands defined in module  emacspeak-url-template.

Caught emacspeak-url-template-fetch
Caught emacspeak-url-template-help
Caught emacspeak-url-template-load
Caught emacspeak-url-template-save

@node emacspeak-view
@section emacspeak-view

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-view.

Caught emacspeak-view-line-to-top

@node emacspeak-vm
@section emacspeak-vm

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-vm.

Caught emacspeak-vm-browse-message
Caught emacspeak-vm-catch-up-all-messages
Caught emacspeak-vm-locate-subject-line
Caught emacspeak-vm-mode-line
Caught emacspeak-vm-next-button
Caught emacspeak-vm-speak-labels
Caught emacspeak-vm-speak-message
Caught emacspeak-vm-yank-header

@node emacspeak-w3
@section emacspeak-w3

Commentary:
Ensure that speech support for W3 gets installed and
loaded correctly.
The emacs W3 browser comes with builtin support for
Emacspeak and ACSS

Automatically generated documentation
for commands defined in module  emacspeak-w3.

Caught emacspeak-w3-curl-url-under-point
Caught emacspeak-w3-customize-base-uri-pronunciation
Caught emacspeak-w3-do-onclick
Caught emacspeak-w3-javascript-follow-link
Caught emacspeak-w3-jump-to-submit
Caught emacspeak-w3-lynx-url-under-point
Caught emacspeak-w3-next-block
Caught emacspeak-w3-next-doc-element
Caught emacspeak-w3-next-parsed-item
Caught emacspeak-w3-previous-doc-element
Caught emacspeak-w3-show-anchor-class
Caught emacspeak-w3-show-http-headers
Caught emacspeak-w3-speak-next-block
Caught emacspeak-w3-speak-next-element
Caught emacspeak-w3-speak-this-element
Caught emacspeak-w3-toggle-table-borders

@node emacspeak-w3m
@section emacspeak-w3m

Commentary:

Automatically generated documentation
for commands defined in module  emacspeak-w3m.

Caught emacspeak-m-player
Caught emacspeak-w3m-preview-this-buffer

@node emacspeak-we
@section emacspeak-we

Commentary:
we is for webedit
Invoke XSLT to edit/transform Web pages before they get
rendered.
we makes emacspeak's webedit layer independent of a given
Emacs web browser like W3 or W3M
This module will use the abstraction provided by browse-url
to handle Web pages.
Module emacspeak-webutils provides the needed additional
abstractions not already covered by browse-url

Automatically generated documentation
for commands defined in module  emacspeak-we.

Caught emacspeak-we-class-filter-and-follow
Caught emacspeak-we-class-filter-and-follow-link
Caught emacspeak-we-count-matches
Caught emacspeak-we-count-nested-tables
Caught emacspeak-we-count-tables
Caught emacspeak-we-extract-by-class
Caught emacspeak-we-extract-by-class-list
Caught emacspeak-we-extract-by-id
Caught emacspeak-we-extract-by-id-list
Caught emacspeak-we-extract-by-property
Caught emacspeak-we-extract-by-role
Caught emacspeak-we-extract-id-list-text
Caught emacspeak-we-extract-id-text
Caught emacspeak-we-extract-matching-urls
Caught emacspeak-we-extract-media-streams
Caught emacspeak-we-extract-media-streams-under-point
Caught emacspeak-we-extract-nested-table
Caught emacspeak-we-extract-nested-table-list
Caught emacspeak-we-extract-print-streams
Caught emacspeak-we-extract-table-by-match
Caught emacspeak-we-extract-table-by-position
Caught emacspeak-we-extract-tables-by-match-list
Caught emacspeak-we-extract-tables-by-position-list
Caught emacspeak-we-follow-and-extract-main
Caught emacspeak-we-follow-and-filter-by-id
Caught emacspeak-we-junk-by-class
Caught emacspeak-we-junk-by-class-list
Caught emacspeak-we-style-filter
Caught emacspeak-we-toggle-xsl-keep-result
Caught emacspeak-we-url-expand-and-execute
Caught emacspeak-we-url-rewrite-and-follow
Caught emacspeak-we-xpath-filter-and-follow
Caught emacspeak-we-xpath-junk-and-follow
Caught emacspeak-we-xsl-toggle
Caught emacspeak-we-xslt-apply
Caught emacspeak-we-xslt-filter
Caught emacspeak-we-xslt-junk
Caught emacspeak-we-xslt-select

@node emacspeak-websearch
@section emacspeak-websearch

Commentary:
This module provides utility functions for searching the WWW

Automatically generated documentation
for commands defined in module  emacspeak-websearch.

Caught emacspeak-websearch-accessible-google
Caught emacspeak-websearch-amazon-search
Caught emacspeak-websearch-ask-jeeves
Caught emacspeak-websearch-biblio-search
Caught emacspeak-websearch-blinkx-search
Caught emacspeak-websearch-citeseer-search
Caught emacspeak-websearch-company-news
Caught emacspeak-websearch-cpan-search
Caught emacspeak-websearch-ctan-search
Caught emacspeak-websearch-dispatch
Caught emacspeak-websearch-display-form
Caught emacspeak-websearch-ebay-search
Caught emacspeak-websearch-exchange-rate-convertor
Caught emacspeak-websearch-foldoc-search
Caught emacspeak-websearch-freshmeat-search
Caught emacspeak-websearch-google
Caught emacspeak-websearch-google-advanced
Caught emacspeak-websearch-google-feeling-lucky
Caught emacspeak-websearch-google-mobile
Caught emacspeak-websearch-google-news
Caught emacspeak-websearch-google-sak
Caught emacspeak-websearch-google-search-in-date-range
Caught emacspeak-websearch-google-specialize
Caught emacspeak-websearch-google-usenet-advanced
Caught emacspeak-websearch-gutenberg
Caught emacspeak-websearch-help
Caught emacspeak-websearch-map-yahoo-directions-search
Caught emacspeak-websearch-merriam-webster-search
Caught emacspeak-websearch-news-yahoo
Caught emacspeak-websearch-open-directory-search
Caught emacspeak-websearch-quotes-yahoo-search
Caught emacspeak-websearch-recorded-books-search
Caught emacspeak-websearch-rpm-find
Caught emacspeak-websearch-software-search
Caught emacspeak-websearch-sourceforge-search
Caught emacspeak-websearch-swik-search
Caught emacspeak-websearch-usenet
Caught emacspeak-websearch-usenet-search
Caught emacspeak-websearch-w3c-search
Caught emacspeak-websearch-weather
Caught emacspeak-websearch-wikipedia-search
Caught emacspeak-websearch-yahoo
Caught emacspeak-websearch-yahoo-exchange-rate-convertor
Caught emacspeak-websearch-yahoo-historical-chart

@node emacspeak-webspace
@section emacspeak-webspace

Commentary:
WEBSPACE == Smart Web Gadgets For The Emacspeak Desktop

Automatically generated documentation
for commands defined in module  emacspeak-webspace.

Caught emacspeak-webspace-feed-reader
Caught emacspeak-webspace-filter
Caught emacspeak-webspace-freebase-search
Caught emacspeak-webspace-google
Caught emacspeak-webspace-headlines
Caught emacspeak-webspace-headlines-browse
Caught emacspeak-webspace-headlines-update
Caught emacspeak-webspace-mode
Caught emacspeak-webspace-open
Caught emacspeak-webspace-transcode
Caught emacspeak-webspace-weather
Caught emacspeak-webspace-weather-update
Caught emacspeak-webspace-yank-link

@node emacspeak-webutils
@section emacspeak-webutils

Commentary:
This module provides common Web utilities for emacspeak.
This is to avoid duplication of code between emacspeak-w3.el
and emacspeak-w3m.el

Automatically generated documentation
for commands defined in module  emacspeak-webutils.

Caught emacspeak-webutils-google-extract-from-cache
Caught emacspeak-webutils-google-on-this-site
Caught emacspeak-webutils-google-similar-to-this-page
Caught emacspeak-webutils-google-who-links-to-this-page
Caught emacspeak-webutils-jump-to-title-in-content
Caught emacspeak-webutils-open-in-other-browser
Caught emacspeak-webutils-play-media-at-point
Caught emacspeak-webutils-transcode-current-url-via-google
Caught emacspeak-webutils-transcode-via-google

@node emacspeak-widget
@section emacspeak-widget

Commentary:
This module implements the necessary extensions to provide talking
widgets.

Automatically generated documentation
for commands defined in module  emacspeak-widget.

Caught emacspeak-widget-browse-widget-interactively
Caught emacspeak-widget-help
Caught emacspeak-widget-summarize-parent
Caught emacspeak-widget-summarize-widget-under-point
Caught emacspeak-widget-update-from-minibuffer

@node emacspeak-wizards
@section emacspeak-wizards

Commentary:
Contains various wizards for the Emacspeak desktop.

Automatically generated documentation
for commands defined in module  emacspeak-wizards.

Caught emacspeak-annotate-add-annotation
Caught emacspeak-clipboard-copy
Caught emacspeak-clipboard-paste
Caught emacspeak-copy-current-file
Caught emacspeak-curl
Caught emacspeak-customize
Caught emacspeak-customize-personal-settings
Caught emacspeak-cvs-berlios-get-project-snapshot
Caught emacspeak-cvs-get-anonymous
Caught emacspeak-cvs-gnu-get-project-snapshot
Caught emacspeak-cvs-sf-get-project-snapshot
Caught emacspeak-emergency-tts-restart
Caught emacspeak-frame-label-or-switch-to-labelled-frame
Caught emacspeak-frame-read-frame-label
Caught emacspeak-generate-documentation
Caught emacspeak-generate-texinfo-command-documentation
Caught emacspeak-generate-texinfo-option-documentation
Caught emacspeak-kill-buffer-quietly
Caught emacspeak-learn-emacs-mode
Caught emacspeak-link-current-file
Caught emacspeak-links
Caught emacspeak-lynx
Caught emacspeak-next-frame-or-buffer
Caught emacspeak-previous-frame-or-buffer
Caught emacspeak-root
Caught emacspeak-select-this-buffer-next-display
Caught emacspeak-select-this-buffer-other-window-display
Caught emacspeak-select-this-buffer-previous-display
Caught emacspeak-show-personality-at-point
Caught emacspeak-show-property-at-point
Caught emacspeak-skip-blank-lines-backward
Caught emacspeak-skip-blank-lines-forward
Caught emacspeak-speak-browse-linux-howto
Caught emacspeak-speak-popup-messages
Caught emacspeak-speak-run-shell-command
Caught emacspeak-speak-telephone-directory
Caught emacspeak-speak-this-buffer-next-display
Caught emacspeak-speak-this-buffer-other-window-display
Caught emacspeak-speak-this-buffer-previous-display
Caught emacspeak-ssh-tts-restart
Caught emacspeak-sudo
Caught emacspeak-sudo-edit
Caught emacspeak-switch-to-previous-buffer
Caught emacspeak-symlink-current-file
Caught emacspeak-view-emacspeak-doc
Caught emacspeak-view-emacspeak-faq
Caught emacspeak-view-emacspeak-news
Caught emacspeak-view-emacspeak-tips
Caught emacspeak-wizards-add-autoload-cookies
Caught emacspeak-wizards-braille
Caught emacspeak-wizards-byte-compile-current-buffer
Caught emacspeak-wizards-cleanup-shell-path
Caught emacspeak-wizards-comma-at-end-of-word
Caught emacspeak-wizards-count-slides-in-region
Caught emacspeak-wizards-cycle-browser
Caught emacspeak-wizards-cycle-to-next-buffer
Caught emacspeak-wizards-display-pod-as-manpage
Caught emacspeak-wizards-dvi-display
Caught emacspeak-wizards-dvi-mode
Caught emacspeak-wizards-edit-file-as-root
Caught emacspeak-wizards-end-of-word
Caught emacspeak-wizards-enumerate-matching-commands
Caught emacspeak-wizards-enumerate-matching-faces
Caught emacspeak-wizards-enumerate-obsolete-faces
Caught emacspeak-wizards-enumerate-uncovered-commands
Caught emacspeak-wizards-enumerate-unmapped-faces
Caught emacspeak-wizards-espeak-region
Caught emacspeak-wizards-espeak-string
Caught emacspeak-wizards-eww-buffer-list
Caught emacspeak-wizards-find-emacspeak-source
Caught emacspeak-wizards-find-file-as-root
Caught emacspeak-wizards-find-grep
Caught emacspeak-wizards-find-longest-line-in-region
Caught emacspeak-wizards-find-longest-paragraph-in-region
Caught emacspeak-wizards-find-shortest-line-in-region
Caught emacspeak-wizards-finder-find
Caught emacspeak-wizards-finder-mode
Caught emacspeak-wizards-fix-read-only-text
Caught emacspeak-wizards-fix-typo
Caught emacspeak-wizards-generate-finder
Caught emacspeak-wizards-generate-voice-sampler
Caught emacspeak-wizards-get-table-content-from-file
Caught emacspeak-wizards-get-table-content-from-url
Caught emacspeak-wizards-google-hits
Caught emacspeak-wizards-google-transcode
Caught emacspeak-wizards-how-many-matches
Caught emacspeak-wizards-i810-display-status
Caught emacspeak-wizards-js
Caught emacspeak-wizards-lacheck-buffer-file
Caught emacspeak-wizards-load-current-file
Caught emacspeak-wizards-move-and-speak
Caught emacspeak-wizards-next-bullet
Caught emacspeak-wizards-next-interactive-defun
Caught emacspeak-wizards-next-shell
Caught emacspeak-wizards-occur-header-lines
Caught emacspeak-wizards-pdf-open
Caught emacspeak-wizards-popup-input-buffer
Caught emacspeak-wizards-portfolio-quotes
Caught emacspeak-wizards-ppp-toggle
Caught emacspeak-wizards-ppt-display
Caught emacspeak-wizards-ppt-mode
Caught emacspeak-wizards-previous-bullet
Caught emacspeak-wizards-previous-shell
Caught emacspeak-wizards-refresh-shell-history
Caught emacspeak-wizards-rivo
Caught emacspeak-wizards-rpm-query-in-dired
Caught emacspeak-wizards-shell
Caught emacspeak-wizards-shell-toggle
Caught emacspeak-wizards-show-commentary
Caught emacspeak-wizards-show-environment-variable
Caught emacspeak-wizards-show-eval-result
Caught emacspeak-wizards-show-face
Caught emacspeak-wizards-show-memory-used
Caught emacspeak-wizards-speak-iso-datetime
Caught emacspeak-wizards-spot-words
Caught emacspeak-wizards-squeeze-blanks
Caught emacspeak-wizards-sunrise-sunset
Caught emacspeak-wizards-switch-shell
Caught emacspeak-wizards-term
Caught emacspeak-wizards-terminal
Caught emacspeak-wizards-tex-tie-current-word
Caught emacspeak-wizards-thanks-mail-signature
Caught emacspeak-wizards-toggle-mm-dd-yyyy-date-pronouncer
Caught emacspeak-wizards-toggle-yyyymmdd-date-pronouncer
Caught emacspeak-wizards-tpctl-display-status
Caught emacspeak-wizards-tramp-open-location
Caught emacspeak-wizards-unhex-uri
Caught emacspeak-wizards-units
Caught emacspeak-wizards-vc-n
Caught emacspeak-wizards-vc-viewer
Caught emacspeak-wizards-vc-viewer-mode
Caught emacspeak-wizards-vc-viewer-refresh
Caught emacspeak-wizards-vi-as-su-file
Caught emacspeak-wizards-view-buffers-filtered-by-mode
Caught emacspeak-wizards-view-buffers-filtered-by-this-mode
Caught emacspeak-wizards-view-url
Caught emacspeak-wizards-voice-sampler
Caught emacspeak-wizards-vpn-toggle
Caught emacspeak-wizards-xl-display
Caught emacspeak-wizards-xl-mode

@node emacspeak-xml-shell
@section emacspeak-xml-shell

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-xml-shell.

Caught emacspeak-xml-shell
Caught emacspeak-xml-shell-browse-current
Caught emacspeak-xml-shell-browse-result
Caught emacspeak-xml-shell-goto-children
Caught emacspeak-xml-shell-goto-next-child
Caught emacspeak-xml-shell-goto-parent
Caught emacspeak-xml-shell-goto-previous-child
Caught emacspeak-xml-shell-mode

@node emacspeak-xslt
@section emacspeak-xslt

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-xslt.

Caught emacspeak-xslt-view
Caught emacspeak-xslt-view-file
Caught emacspeak-xslt-view-region
Caught emacspeak-xslt-view-xml

@node emacspeak-zinf
@section emacspeak-zinf

Commentary:
Defines a simple derived mode for interacting with
zinf.
zinf == zinf is not freeamp
zinf navigation commands then work via single keystrokes.

Automatically generated documentation
for commands defined in module  emacspeak-zinf.

Caught emacspeak-zinf
Caught emacspeak-zinf-mode
Caught emacspeak-zinf-zinf-call-command
Caught emacspeak-zinf-zinf-command

@node emacspeak
@section emacspeak

Commentary:
The complete audio desktop.

Emacspeak extends Emacs to be a fully functional audio desktop.
This is the main emacspeak module.
It actually does very little:
It loads the various parts of the system.

Automatically generated documentation
for commands defined in module  emacspeak.

Caught emacspeak-describe-emacspeak
Caught emacspeak-submit-bug

@node voice-setup
@section voice-setup

Commentary:
A voice is to audio as a font is to a visual display.
A personality is to audio as a face is to a visual display.

Voice-lock-mode is a minor mode that causes your comments to be
spoken in one personality, strings in another, reserved words in another,
documentation strings in another, and so on.

Comments will be spoken in `emacspeak-voice-lock-comment-personality'.
Strings will be spoken in `emacspeak-voice-lock-string-personality'.
Function and variable names (in their defining forms) will be
 spoken in `emacspeak-voice-lock-function-name-personality'.
Reserved words will be spoken in `emacspeak-voice-lock-keyword-personality'.

To make the text you type be voiceified, use M-x voice-lock-mode.
When this minor mode is on, the voices of the current line are
updated with every insertion or deletion.

How faces map to voices: TTS engine specific modules e.g.,
dectalk-voices.el and outloud-voices.el define a standard set
of voice names.  This module maps standard "personality"
names to these pre-defined voices.  It does this via special
form def-voice-font which takes a personality name, a voice
name and a face name to set up the mapping between face and
personality, and personality and voice.
Newer Emacspeak modules should use voice-setup-add-map when
defining face->personality mappings.
Older code calls def-voice-font directly, but over time those
calls will be changed to the more succinct form provided by
voice-setup-add-map. For use from other modules, also see
function voice-setup-map-face which is useful when mapping a
single face.
Both voice-setup-add-map and voice-setup-map-face call
special form def-voice-font.

Special form def-voice-font sets up the personality name to
be available via custom.  new voices can be defined using CSS
style specifications see special form defvoice Voices defined
via defvoice can be customized via custom see the
documentation for defvoice.

Automatically generated documentation
for commands defined in module  voice-setup.

Caught voice-setup-list-voices
Caught voice-setup-toggle-silence-personality

@node emacspeak-bbc
@section emacspeak-bbc

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-bbc.

Caught emacspeak-bbc
Caught emacspeak-bbc-genre

@node emacspeak-org
@section emacspeak-org

Commentary:
Speech-enable org ---
 Org allows you to keep organized notes and todo lists.
Homepage: http://www.astro.uva.nl/~dominik/Tools/org/
or http://orgmode.org/

Automatically generated documentation
for commands defined in module  emacspeak-org.

Caught emacspeak-org-bookmark
Caught emacspeak-org-popup-input
Caught emacspeak-org-table-speak-current-element

No Commentary

Automatically generated documentation
for commands defined in module  nil.

Caught ad-Advice-emacspeak-eterm-copy-region-to-register
Caught ad-Advice-emacspeak-eterm-paste-register
Caught emacspeak-py-next-block
Caught emacspeak-py-previous-block
@node URL Templates 
@section  URL Templates

This section is generated automatically from the source-level documentation.
Any errors or corrections should be made to the source-level
documentation.
This section documents a total of 113 URL Templates.

All of these URL templates can be invoked via command
  @kbd{M-x emacspeak-url-template-fetch} normally bound to
  @kbd{C-e u}.
This command prompts for the name of the template, and completion
  is available via Emacs' minibuffer completion.
Each URL template carries out the following steps:
@itemize @bullet
@item Prompt for the relevant information.
@item Fetch the resulting URL using an appropriate fetcher.
@item Set up the resulting resource with appropriate
  customizations.
@end itemize

As an example, the URL templates that enable access to map directions
prompt for address and automatically
speak the relevant results.

@kbd{Air Traffic Control}

Find live streams for Air Traffic Control.

@kbd{Airport conditions}

Display airport conditions from the FAA.

@kbd{Amazon Product Details By ASIN}

Retrieve product details from Amazon by either ISBN or ASIN.

@kbd{Anonymize Google Search}

Logout from Google to do an anonymous search.

@kbd{Archive News Search}

Search Google Archive News.

@kbd{Ask Local Search}

Ask Local Search.

@kbd{Ask Walking Directions}

Walking directions from Ask.com

@kbd{BBC  iPlayer}

BBC iPlayer

@kbd{BBC Genre Using IPlayer}

BBC iPlayer Genre

@kbd{BBC Podcast Directory}

BBC PodCast Directory

@kbd{BBC Program Guide}

Display interactive BBC Program Guide.

@kbd{Baseball Game Index}

Display baseball Play By Play.

@kbd{Baseball Play By Play}

Display baseball Play By Play.

@kbd{Baseball scores}

Display baseball scores.

@kbd{Baseball standings}

Display MLB standings.

@kbd{Bing News}

Bing News results as RSS feed.

@kbd{Bing Search}

Bing results as RSS feed.

@kbd{BlogSearch Google}

Google Blog Search

@kbd{CNN Content }

CNN Content

@kbd{CNN Market Data }

CNN Money

@kbd{CNN headlines }

Retrieve and speak headline news from CNN.

@kbd{CNN technology }

CNN Technology news.

@kbd{CNNContent}

Filter down to CNN  content area.

@kbd{CNNPodCasts}

List CNN Podcast media links.

@kbd{Cartoon You Said It By Laxman}

Retrieve Cartoon Times Of India.

@kbd{Dictionary Lookup}

Dictionary Lookup

@kbd{Earthquakes}

Show table of recent quakes.

@kbd{EmacsWiki Search}

EmacsWiki Search

@kbd{Finance Google Portfolio}

Download and display portfolio from Google Finance.

@kbd{Finance Google Search}

Display content from Google Finance.

@kbd{Finance Google news}

Display content from Google Finance.

@kbd{G3 Sourcer URL}

Return Sourcerer URL.

@kbd{GCalendar Mobile}

Google Calendar XHTML version.

@kbd{Geek Linux Daily}

Play specified edition of Geek  Linux DailyShow

@kbd{GitHub Search}

Perform a GitHub Search.

@kbd{Google API Search}

Search Google APIDocs

@kbd{Google Books}

Google Books Search with text when available

@kbd{Google Feeds}

List  Google news Feeds.

@kbd{Google Glossary}

Google Glossary lookup.

@kbd{Google Hits}

Only show Google hits.

@kbd{Google Image Search}

Google Image Search

@kbd{Google Info View}

Do a Google search and get a Info view of results.

@kbd{Google Mobile Search}

Google Mobile Search

@kbd{Google News Search}

Search Google news.

@kbd{Google NewsPaper}

Retrieve and speak Google News Overview.

@kbd{Google Print}

Google Print Search

@kbd{Google Reader}

Google Reader

@kbd{Google Recent News Search}

Search Google news.

@kbd{Google Results}

Show just results and nav bar.

@kbd{Google Scholar}

Google Scholar Search

@kbd{Google TimeLine View}

Do a Google search and get a timeline view of results.

@kbd{Google Transcoder}

Transcode site via Google.

@kbd{Google WebQuotes}

Google WebQuotes.

@kbd{Google Webmaster Page Analysis}

Page Analysis From Google Webmaster tools.

@kbd{Google topical  News}

Display specified news feed.

@kbd{IToRSS}

Pull RSS  feed corresponding to an ITunes Podcast.

@kbd{Linux Today News}

Get news column from Linux Today.

@kbd{MDC Search}

Search MDC Wiki.

@kbd{MLB Scorecard}

Show MLB Scorecard.

@kbd{Market summary from Google}

Display financial market summary.

@kbd{Mobile BBC}

BBC Mobile Streams.

@kbd{Mobile Finance Google Search}

Display content from Google Finance.

@kbd{Money Content }

CNN Content

@kbd{Mozilla Developers Corner}

Pull specified resource from MDC.

@kbd{Multilingual dictionary via Google.}

Translate word using Google.
Source and target languages
are specified as two-letter language codes, e.g. en|de translates
from English to German

@kbd{NY Times Mobile}

NYTimes Mobile Site

@kbd{NY Times RSS Feeds}

Display browsable list of NY Times RSS Feeds.

@kbd{Official GoogleBlog Search}

Search within all official Google blogs.

@kbd{Old Time Radio}

This months Old Time Radio Programing

@kbd{On The Fly CSE}

Build a CSE on the fly and  use it to search.

@kbd{PHC Prairie Home Companion}

Play Prairie Home Companion

@kbd{Patent Search From Google}

Perform patent search via Google

@kbd{PodCast CNet}

Play Podcast from CNET

@kbd{Reader Subscription Search}

Search within feeds subscribed to in Google Reader.

@kbd{Recent BlogSearch Google}

Google Blog Search

@kbd{Recent YouTube Results}

YouTube Search Via Feeds

@kbd{Redhat Linux Show}

Play specified edition of Redhat Linux Show

@kbd{Reuters Finance}

Reuters Finance Lookup

@kbd{Seeking Alpha Stock Search}

Seeking Alpha search.

@kbd{Sign in to Google}

Login to Google.

@kbd{StreamWorld Radio}

Play radio stream.
See http://www.cbsradio.com/streaming/index.html for a list of CBS  stations that use StreamTheWorld.

@kbd{Tech News From CNet}

Display tech news from CNET

@kbd{Times Of India}

Retrieve Times Of India.
Set up URL rewrite rule to get print page.

@kbd{Translation Via Google}

Translate a Web page using google. Source and target languages
are specified as two-letter language codes, e.g. en|de translates
from English to German.

@kbd{Twitter Search}

Twitter search and display results feed.

@kbd{UPS Packages}

Display package tracking information from UPS.

@kbd{Weather forecast from Weather Underground}

Weather forecast from weather underground mobile.

@kbd{WordNet Search}

Look up term in WordNet.

@kbd{Yahoo Business News}

Retrieve and speak business  section from Yahoo Daily News.

@kbd{Yahoo Content By Content ID}

Retrieve and speak news section from Yahoo Daily News.

@kbd{Yahoo DailyNews}

Retrieve and speak DailyNewspage from  Yahoo Daily News.

@kbd{Yahoo Entertainment}

Retrieve and speak Entertainment section from Yahoo Daily News.

@kbd{Yahoo Health}

Retrieve and speak Health section from Yahoo Daily News.

@kbd{Yahoo Lifestyle}

Yahoo Lifestyle News.

@kbd{Yahoo Oddly}

Retrieve and speak Oddity section from Yahoo Daily News.

@kbd{Yahoo Politics}

Retrieve and speak Politics section from Yahoo Daily News.

@kbd{Yahoo RSS Feeds}

List Yahoo RSS Feeds.

@kbd{Yahoo SF Local}

Retrieve and speak Local section from Yahoo Daily News.

@kbd{Yahoo Science}

Retrieve and speak Science section from Yahoo Daily News.

@kbd{Yahoo Sports}

Entertainment news from Yahoo.

@kbd{Yahoo Technology  News}

Yahoo Technology News.

@kbd{Yahoo Top Stories}

Retrieve and speak Top Stories  section from Yahoo Daily News.

@kbd{Yahoo World News}

Yahoo World News.

@kbd{YouTube Results}

YouTube Search Via Feeds

@kbd{ask search mobile}

Mobile search using Ask.com

@kbd{fedex packages}

Display package tracking information from Fedex.

@kbd{html5IRC}

Show HTML5 IRC log.

@kbd{rss weather from wunderground}

Pull RSS weather feed for specified state/city.

@kbd{sourceforge Download}

Download specified file.

@kbd{sourceforge browse mirrors}

Retrieve download page  at Sourceforge for specified project.

@kbd{sourceforge project}

Open specified project page at SourceForge.

@kbd{w3c IRC Logs}

Use this to pull up the
archived  logs from the W3C IRC. You need to know the exact
name of the channel.

@kbd{w3c Lists}

Use this to pull up the
archived  mail from the W3C list. You need to know the exact
name of the list.

