@node Emacspeak Commands
@chapter Emacspeak Commands

This chapter is generated automatically from the source-level documentation.
Any errors or corrections should be made to the source-level
documentation. This chapter documents a total of 966
commands.

@menu
* cd-tool::
* dectalk-voices::
* dtk-speak::
* dtk-unicode::
* emacspeak-alsaplayer::
* emacspeak-amark::
* emacspeak-arc::
* emacspeak-aumix::
* emacspeak-bookshare::
* emacspeak-bs::
* emacspeak-buff-menu::
* emacspeak-c::
* emacspeak-calendar::
* emacspeak-compile::
* emacspeak-custom::
* emacspeak-dired::
* emacspeak-dismal::
* emacspeak-ecb::
* emacspeak-ediff::
* emacspeak-emms::
* emacspeak-enriched::
* emacspeak-entertain::
* emacspeak-eperiodic::
* emacspeak-epub::
* emacspeak-erc::
* emacspeak-eterm::
* emacspeak-eudc::
* emacspeak-feeds::
* emacspeak-filtertext::
* emacspeak-fix-interactive::
* emacspeak-forms::
* emacspeak-gnus::
* emacspeak-gomoku::
* emacspeak-google::
* emacspeak-gridtext::
* emacspeak-hide::
* emacspeak-ibuffer::
* emacspeak-imenu::
* emacspeak-info::
* emacspeak-jabber::
* emacspeak-keymap::
* emacspeak-librivox::
* emacspeak-loaddefs::
* emacspeak-m-player::
* emacspeak-madplay::
* emacspeak-man::
* emacspeak-mpg123::
* emacspeak-npr::
* emacspeak-ocr::
* emacspeak-outline::
* emacspeak-pianobar::
* emacspeak-pronounce::
* emacspeak-redefine::
* emacspeak-remote::
* emacspeak-rmail::
* emacspeak-solitaire::
* emacspeak-sounds::
* emacspeak-speak::
* emacspeak-speedbar::
* emacspeak-sudoku::
* emacspeak-table-ui::
* emacspeak-tabulate::
* emacspeak-tapestry::
* emacspeak-tar::
* emacspeak-tetris::
* emacspeak-tnt::
* emacspeak-url-template::
* emacspeak-view::
* emacspeak-vm::
* emacspeak-w3::
* emacspeak-w3m::
* emacspeak-we::
* emacspeak-websearch::
* emacspeak-webspace::
* emacspeak-webutils::
* emacspeak-widget::
* emacspeak-wizards::
* emacspeak-xml-shell::
* emacspeak-xslt::
* emacspeak-zinf::
* emacspeak::
* voice-setup::
* emacspeak-bbc::
* emacspeak-org::
* URL Templates ::
@end menu

@node cd-tool
@section cd-tool

Commentary:
Provide an emacs front-end to cdtool.
cdtool can be obtained as an rpm
check using rpmfind
or from its home site at
  sunsite.unc.edu /pub/Linux/apps/sound/cdrom/cli
This module also provides the ability to play or save
clips from a CD if you have cdda2wav installed.
cdda2wav is a cd to wav convertor.

Automatically generated documentation
for commands defined in module  cd-tool.

@c Caught cd-tool

@node dectalk-voices
@section dectalk-voices

Commentary:
This module defines the various voices used in voice-lock mode.
This module is Dectalk specific.

Automatically generated documentation
for commands defined in module  dectalk-voices.

@c Caught dtk-exp

@node dtk-speak
@section dtk-speak

Commentary:
Defines the TTS interface.

Automatically generated documentation
for commands defined in module  dtk-speak.

@c Caught dtk-add-cleanup-pattern

@c Caught dtk-async-server

@c Caught dtk-local-server

@c Caught dtk-pause

@c Caught dtk-reset-state

@c Caught dtk-resume

@c Caught dtk-select-server

@c Caught dtk-set-character-scale

@c Caught dtk-set-chunk-separator-syntax

@c Caught dtk-set-language

@c Caught dtk-set-next-language

@c Caught dtk-set-predefined-speech-rate

@c Caught dtk-set-preferred-language

@c Caught dtk-set-previous-language

@c Caught dtk-set-punctuations

@c Caught dtk-set-punctuations-to-all

@c Caught dtk-set-punctuations-to-some

@c Caught dtk-set-rate

@c Caught dtk-stop

@c Caught dtk-toggle-allcaps-beep

@c Caught dtk-toggle-capitalization

@c Caught dtk-toggle-debug

@c Caught dtk-toggle-punctuation-mode

@c Caught dtk-toggle-quiet

@c Caught dtk-toggle-speak-nonprinting-chars

@c Caught dtk-toggle-split-caps

@c Caught dtk-toggle-splitting-on-white-space

@c Caught dtk-toggle-strip-octals

@node dtk-unicode
@section dtk-unicode

Commentary:

This  Provides Unicode support to the speech layer.

Automatically generated documentation
for commands defined in module  dtk-unicode.

@c Caught dtk-unicode-customize-char

@c Caught dtk-unicode-uncustomize-char

@node emacspeak-alsaplayer
@section emacspeak-alsaplayer

Commentary:
Defines a simple derived mode for interacting with
alsaplayer.
alsaplayer navigation commands  work via single keystrokes.

Automatically generated documentation
for commands defined in module  emacspeak-alsaplayer.

@c Caught emacspeak-alsaplayer-add-to-queue

@c Caught emacspeak-alsaplayer-amark-add

@c Caught emacspeak-alsaplayer-amark-jump

@c Caught emacspeak-alsaplayer-backward-10-seconds

@c Caught emacspeak-alsaplayer-backward-minute

@c Caught emacspeak-alsaplayer-backward-ten-minutes

@c Caught emacspeak-alsaplayer-cd

@c Caught emacspeak-alsaplayer-clear

@c Caught emacspeak-alsaplayer-clip

@c Caught emacspeak-alsaplayer-find-and-add-to-queue

@c Caught emacspeak-alsaplayer-forward-10-seconds

@c Caught emacspeak-alsaplayer-forward-minute

@c Caught emacspeak-alsaplayer-forward-ten-minutes

@c Caught emacspeak-alsaplayer-info

@c Caught emacspeak-alsaplayer-jump

@c Caught emacspeak-alsaplayer-launch

@c Caught emacspeak-alsaplayer-mark-position

@c Caught emacspeak-alsaplayer-mode

@c Caught emacspeak-alsaplayer-next

@c Caught emacspeak-alsaplayer-pause

@c Caught emacspeak-alsaplayer-previous

@c Caught emacspeak-alsaplayer-quit

@c Caught emacspeak-alsaplayer-relative

@c Caught emacspeak-alsaplayer-replace-queue

@c Caught emacspeak-alsaplayer-seek

@c Caught emacspeak-alsaplayer-speed

@c Caught emacspeak-alsaplayer-start

@c Caught emacspeak-alsaplayer-status

@c Caught emacspeak-alsaplayer-stop

@c Caught emacspeak-alsaplayer-volume

@c Caught emacspeak-alsaplayer-where

@node emacspeak-amark
@section emacspeak-amark

Commentary:
Structure emacspeak-amark holds a bookmark into an mp3 file
path: fully qualified pathname  to file being marked
name: Bookmark tag
Position: time offset from start 

This library will be used from emacspeak-m-player,
emacspeak-alsaplayer and friends to set and jump to bookmarks.

Automatically generated documentation
for commands defined in module  emacspeak-amark.

@c Caught emacspeak-amark-add

@c Caught emacspeak-amark-find

@c Caught emacspeak-amark-load

@c Caught emacspeak-amark-save

@node emacspeak-arc
@section emacspeak-arc

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-arc.

@c Caught emacspeak-arc-speak-file-modification-time

@c Caught emacspeak-arc-speak-file-name

@c Caught emacspeak-arc-speak-file-permissions

@c Caught emacspeak-arc-speak-file-size

@node emacspeak-aumix
@section emacspeak-aumix

Commentary:
Provides an AUI to setting up the auditory display via AUMIX
This module is presently Linux specific

Automatically generated documentation
for commands defined in module  emacspeak-aumix.

@c Caught emacspeak-aumix-edit

@c Caught emacspeak-aumix-reset

@c Caught emacspeak-aumix-volume-decrease

@c Caught emacspeak-aumix-volume-increase

@c Caught emacspeak-aumix-wave-decrease

@c Caught emacspeak-aumix-wave-increase

@node emacspeak-bookshare
@section emacspeak-bookshare

Commentary:
BOOKSHARE == http://www.bookshare.org provides book access to print-disabled users.
It provides a simple Web  API http://developer.bookshare.org
This module implements an Emacspeak Bookshare client.
For now, users will need to get their own API key

Automatically generated documentation
for commands defined in module  emacspeak-bookshare.

@c Caught emacspeak-bookshare

@c Caught emacspeak-bookshare-action

@c Caught emacspeak-bookshare-author-search

@c Caught emacspeak-bookshare-browse

@c Caught emacspeak-bookshare-browse-latest

@c Caught emacspeak-bookshare-browse-popular

@c Caught emacspeak-bookshare-download-brf

@c Caught emacspeak-bookshare-download-brf-at-point

@c Caught emacspeak-bookshare-download-daisy

@c Caught emacspeak-bookshare-download-daisy-at-point

@c Caught emacspeak-bookshare-download-internal

@c Caught emacspeak-bookshare-eww

@c Caught emacspeak-bookshare-expand-at-point

@c Caught emacspeak-bookshare-extract-and-view

@c Caught emacspeak-bookshare-extract-xml

@c Caught emacspeak-bookshare-flush-lines

@c Caught emacspeak-bookshare-fulltext

@c Caught emacspeak-bookshare-fulltext-search

@c Caught emacspeak-bookshare-get-more-results

@c Caught emacspeak-bookshare-id-search

@c Caught emacspeak-bookshare-isbn-search

@c Caught emacspeak-bookshare-list-preferences

@c Caught emacspeak-bookshare-mode

@c Caught emacspeak-bookshare-next-result

@c Caught emacspeak-bookshare-periodical-list

@c Caught emacspeak-bookshare-previous-result

@c Caught emacspeak-bookshare-set-preference

@c Caught emacspeak-bookshare-sign-out

@c Caught emacspeak-bookshare-since-search

@c Caught emacspeak-bookshare-title-search

@c Caught emacspeak-bookshare-title/author-search

@c Caught emacspeak-bookshare-toc

@c Caught emacspeak-bookshare-toc-at-point

@c Caught emacspeak-bookshare-unpack-at-point

@c Caught emacspeak-bookshare-url-executor

@c Caught emacspeak-bookshare-version-handler

@c Caught emacspeak-bookshare-view

@c Caught emacspeak-bookshare-view-at-point

@c Caught emacspeak-bookshare-view-page-range

@node emacspeak-bs
@section emacspeak-bs

Commentary:
speech-enable bs.el -- an alternative to Emacs' default  list-buffers

Automatically generated documentation
for commands defined in module  emacspeak-bs.

@c Caught emacspeak-bs-speak-buffer-line

@node emacspeak-buff-menu
@section emacspeak-buff-menu

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-buff-menu.

@c Caught emacspeak-list-buffers-next-line

@c Caught emacspeak-list-buffers-previous-line

@c Caught emacspeak-list-buffers-speak-buffer-line

@c Caught emacspeak-list-buffers-speak-buffer-name

@node emacspeak-c
@section emacspeak-c

Commentary:
Make some of C and C++ mode more emacspeak friendly
Works with both boring c-mode
and the excellent cc-mode

Automatically generated documentation
for commands defined in module  emacspeak-c.

@c Caught emacspeak-c-speak-semantics

@node emacspeak-calendar
@section emacspeak-calendar

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-calendar.

@c Caught emacspeak-appt-repeat-announcement

@c Caught emacspeak-calendar-setup-sunrise-sunset

@c Caught emacspeak-calendar-speak-date

@node emacspeak-compile
@section emacspeak-compile

Commentary:
This module makes compiling code from inside Emacs speech friendly.
It is an example of how a little amount of code can make Emacspeak even better.

Automatically generated documentation
for commands defined in module  emacspeak-compile.

@c Caught emacspeak-compilation-speak-error

@node emacspeak-custom
@section emacspeak-custom

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-custom.

@c Caught emacspeak-custom-goto-group

@c Caught emacspeak-custom-goto-toolbar

@node emacspeak-dired
@section emacspeak-dired

Commentary:
This module speech enables dired.
It reduces the amount of speech you hear:
Typically you hear the file names as you move through the dired buffer
Voicification is used to indicate directories, marked files etc.

Automatically generated documentation
for commands defined in module  emacspeak-dired.

@c Caught emacspeak-dired-label-fields

@c Caught emacspeak-dired-show-file-type

@c Caught emacspeak-dired-speak-file-access-time

@c Caught emacspeak-dired-speak-file-modification-time

@c Caught emacspeak-dired-speak-file-permissions

@c Caught emacspeak-dired-speak-file-size

@c Caught emacspeak-dired-speak-header-line

@c Caught emacspeak-dired-speak-symlink-target

@node emacspeak-dismal
@section emacspeak-dismal

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-dismal.

@c Caught emacspeak-dismal-backward-col-and-summarize

@c Caught emacspeak-dismal-backward-row-and-summarize

@c Caught emacspeak-dismal-col-summarize

@c Caught emacspeak-dismal-display-cell-expression

@c Caught emacspeak-dismal-display-cell-value

@c Caught emacspeak-dismal-display-cell-with-col-header

@c Caught emacspeak-dismal-display-cell-with-row-header

@c Caught emacspeak-dismal-forward-col-and-summarize

@c Caught emacspeak-dismal-forward-row-and-summarize

@c Caught emacspeak-dismal-row-summarize

@c Caught emacspeak-dismal-set-col-summarizer-list

@c Caught emacspeak-dismal-set-row-summarizer-list

@c Caught emacspeak-dismal-set-sheet-summarizer-list

@c Caught emacspeak-dismal-sheet-summarize

@node emacspeak-ecb
@section emacspeak-ecb

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-ecb.

@c Caught emacspeak-ecb-speak-window-directories

@c Caught emacspeak-ecb-speak-window-history

@c Caught emacspeak-ecb-speak-window-methods

@c Caught emacspeak-ecb-speak-window-sources

@c Caught emacspeak-ecb-tree-backspace

@c Caught emacspeak-ecb-tree-clear

@c Caught emacspeak-ecb-tree-expand-common-prefix

@c Caught emacspeak-ecb-tree-shift-return

@node emacspeak-ediff
@section emacspeak-ediff

Commentary:
Ediff provides a nice visual interface to diff. ;;;Comparing and
patching files is easy with ediff when you can see the screen.
This module provides Emacspeak extensions to work fluently
with ediff. Try it out, it's an excellent example of why
Emacspeak is better than a traditional screenreader. This module
was originally written to interface to the old ediff.el bundled
with GNU Emacs 19.28 and earlier. It has been updated to work
with the newer and much larger ediff system found in Emacs 19.29
and later.

Automatically generated documentation
for commands defined in module  emacspeak-ediff.

@c Caught emacspeak-ediff-speak-current-difference

@node emacspeak-emms
@section emacspeak-emms

Commentary:
Speech-enables EMMS --- the Emacs equivalent of XMMS
See
http://savannah.gnu.org/project/emms
EMMS is under active development,
to get the current CVS version, use Emacspeak command
M-x emacspeak-cvs-gnu-get-project-snapshot RET emms RET

Automatically generated documentation
for commands defined in module  emacspeak-emms.

@c Caught emacspeak-emms-speak-current-track

@node emacspeak-enriched
@section emacspeak-enriched

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-enriched.

@c Caught emacspeak-enriched-voiceify-faces

@node emacspeak-entertain
@section emacspeak-entertain

Commentary:
Auditory interface to misc games

Automatically generated documentation
for commands defined in module  emacspeak-entertain.

@c Caught emacspeak-hangman-speak-guess

@c Caught emacspeak-hangman-speak-statistics

@node emacspeak-eperiodic
@section emacspeak-eperiodic

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-eperiodic.

@c Caught emacspeak-eperiodic-goto-property-section

@c Caught emacspeak-eperiodic-next-line

@c Caught emacspeak-eperiodic-play-description

@c Caught emacspeak-eperiodic-previous-line

@c Caught emacspeak-eperiodic-speak-current-element

@node emacspeak-epub
@section emacspeak-epub

Commentary:
In celebration of a million books and more to read from
Google Books
The EPubs format is slightly simpler than full Daisy ---
(see) emacspeak-daisy.el
Since it only needs one level of indirection (no audio,
therefore no smil). This module is consequently simpler than
emacspeak-daisy.el.
This module will eventually  implement the Google Books  API
--- probably by invoking the yet-to-be-written gbooks.el in emacs-g-client
As we move to epub-3, this module will bring back audio layers etc., perhaps via a simplified smil implementation.

Automatically generated documentation
for commands defined in module  emacspeak-epub.

@c Caught emacspeak-calibre-mode

@c Caught emacspeak-epub

@c Caught emacspeak-epub-bookshelf-add-directory

@c Caught emacspeak-epub-bookshelf-add-epub

@c Caught emacspeak-epub-bookshelf-calibre-author

@c Caught emacspeak-epub-bookshelf-calibre-search

@c Caught emacspeak-epub-bookshelf-calibre-title

@c Caught emacspeak-epub-bookshelf-clear

@c Caught emacspeak-epub-bookshelf-load

@c Caught emacspeak-epub-bookshelf-open

@c Caught emacspeak-epub-bookshelf-open-epub

@c Caught emacspeak-epub-bookshelf-redraw

@c Caught emacspeak-epub-bookshelf-refresh

@c Caught emacspeak-epub-bookshelf-remove-directory

@c Caught emacspeak-epub-bookshelf-remove-this-book

@c Caught emacspeak-epub-bookshelf-rename

@c Caught emacspeak-epub-bookshelf-save

@c Caught emacspeak-epub-browse-files

@c Caught emacspeak-epub-calibre-dired-at-point

@c Caught emacspeak-epub-calibre-results

@c Caught emacspeak-epub-delete

@c Caught emacspeak-epub-eww

@c Caught emacspeak-epub-fulltext

@c Caught emacspeak-epub-google

@c Caught emacspeak-epub-gutenberg-catalog

@c Caught emacspeak-epub-gutenberg-download

@c Caught emacspeak-epub-mode

@c Caught emacspeak-epub-next

@c Caught emacspeak-epub-open

@c Caught emacspeak-epub-previous

@c Caught emacspeak-epub-url-executor

@node emacspeak-erc
@section emacspeak-erc

Commentary:
erc.el is a modern Emacs client for IRC including color
and font locking support. 
erc.el - an Emacs IRC client (by Alexander L. Belikoff)
http://www.cs.cmu.edu/~berez/irc/erc.el

Automatically generated documentation
for commands defined in module  emacspeak-erc.

@c Caught emacspeak-erc-add-name-to-monitor

@c Caught emacspeak-erc-delete-name-from-monitor

@c Caught emacspeak-erc-setup-cricket-rules

@c Caught emacspeak-erc-toggle-my-monitor

@c Caught emacspeak-erc-toggle-room-monitor

@c Caught emacspeak-erc-toggle-speak-all-participants

@node emacspeak-eterm
@section emacspeak-eterm

Commentary:
This module makes eterm talk.
Eterm is the new terminal emulator for Emacs.
Use of emacspeak with eterm really needs an info page.
At present, the only documentation is the source level documentation.
This module uses Control-t as an additional prefix key to allow the user
To move around the terminal and have different parts spoken. 

Automatically generated documentation
for commands defined in module  emacspeak-eterm.

@c Caught emacspeak-eterm-copy-region-to-register

@c Caught emacspeak-eterm-define-window

@c Caught emacspeak-eterm-describe-window

@c Caught emacspeak-eterm-goto-line

@c Caught emacspeak-eterm-kill-ring-save-region

@c Caught emacspeak-eterm-maybe-send-raw

@c Caught emacspeak-eterm-paste-register

@c Caught emacspeak-eterm-pointer-backward-word

@c Caught emacspeak-eterm-pointer-down

@c Caught emacspeak-eterm-pointer-forward-word

@c Caught emacspeak-eterm-pointer-left

@c Caught emacspeak-eterm-pointer-right

@c Caught emacspeak-eterm-pointer-to-bottom

@c Caught emacspeak-eterm-pointer-to-cursor

@c Caught emacspeak-eterm-pointer-to-left-edge

@c Caught emacspeak-eterm-pointer-to-next-color-change

@c Caught emacspeak-eterm-pointer-to-previous-color-change

@c Caught emacspeak-eterm-pointer-to-right-edge

@c Caught emacspeak-eterm-pointer-to-top

@c Caught emacspeak-eterm-pointer-up

@c Caught emacspeak-eterm-remote-term

@c Caught emacspeak-eterm-search-backward

@c Caught emacspeak-eterm-search-forward

@c Caught emacspeak-eterm-set-filter-window

@c Caught emacspeak-eterm-set-focus-window

@c Caught emacspeak-eterm-set-marker

@c Caught emacspeak-eterm-speak-cursor

@c Caught emacspeak-eterm-speak-pointer

@c Caught emacspeak-eterm-speak-pointer-char

@c Caught emacspeak-eterm-speak-pointer-line

@c Caught emacspeak-eterm-speak-pointer-word

@c Caught emacspeak-eterm-speak-predefined-window

@c Caught emacspeak-eterm-speak-screen

@c Caught emacspeak-eterm-speak-window

@c Caught emacspeak-eterm-toggle-filter-window

@c Caught emacspeak-eterm-toggle-focus-window

@c Caught emacspeak-eterm-toggle-pointer-mode

@c Caught emacspeak-eterm-toggle-review

@c Caught emacspeak-eterm-yank-window

@c Caught emacspeak-toggle-eterm-autospeak

@node emacspeak-eudc
@section emacspeak-eudc

Commentary:
EUDC --Emacs Universal Directory Client 
provides a unified interface to directory servers
e.g. ldap servers
this module speech enables eudc 

Automatically generated documentation
for commands defined in module  emacspeak-eudc.

@c Caught emacspeak-eudc-send-mail

@node emacspeak-feeds
@section emacspeak-feeds

Commentary:
This module provides Feeds support for Emacspeak

Automatically generated documentation
for commands defined in module  emacspeak-feeds.

@c Caught emacspeak-feeds-add-feed

@c Caught emacspeak-feeds-archive-feeds

@c Caught emacspeak-feeds-atom-display

@c Caught emacspeak-feeds-browse

@c Caught emacspeak-feeds-fastload-feeds

@c Caught emacspeak-feeds-find-feeds

@c Caught emacspeak-feeds-lookup-and-view

@c Caught emacspeak-feeds-opml-display

@c Caught emacspeak-feeds-restoere-feeds

@c Caught emacspeak-feeds-rss-display

@node emacspeak-filtertext
@section emacspeak-filtertext

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-filtertext.

@c Caught emacspeak-filtertext

@c Caught emacspeak-filtertext-mode

@c Caught emacspeak-filtertext-revert

@node emacspeak-fix-interactive
@section emacspeak-fix-interactive

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-fix-interactive.

@c Caught emacspeak-fix-all-recent-commands

@c Caught emacspeak-fix-commands-loaded-from

@node emacspeak-forms
@section emacspeak-forms

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-forms.

@c Caught emacspeak-forms-find-file

@c Caught emacspeak-forms-flush-unwanted-records

@c Caught emacspeak-forms-rerun-filter

@c Caught emacspeak-forms-speak-field

@c Caught emacspeak-forms-summarize-current-position

@c Caught emacspeak-forms-summarize-current-record

@node emacspeak-gnus
@section emacspeak-gnus

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-gnus.

@c Caught emacspeak-gnus-summary-catchup-quietly-and-exit

@c Caught emacspeak-gnus-summary-hide-all-headers

@c Caught emacspeak-gnus-summary-show-some-headers

@node emacspeak-gomoku
@section emacspeak-gomoku

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-gomoku.

@c Caught emacspeak-gomoku-display-statistics

@c Caught emacspeak-gomoku-goto-x-y

@c Caught emacspeak-gomoku-show-current-column

@c Caught emacspeak-gomoku-show-current-negative-diagonal

@c Caught emacspeak-gomoku-show-current-positive-diagonal

@c Caught emacspeak-gomoku-show-current-row

@c Caught emacspeak-gomoku-speak-emacs-previous-move

@c Caught emacspeak-gomoku-speak-humans-previous-move

@c Caught emacspeak-gomoku-speak-number-of-moves

@c Caught emacspeak-gomoku-speak-square

@node emacspeak-google
@section emacspeak-google

Commentary:
There are a number of search tools that can be implemented on
the Google search page --- in a JS-powered browser, these
show up as the Google tool-belt.
This module implements a minor mode for use in Google result
pages that enables these tools via single keyboard commands.
Originally all options were available as tbs=p:v
Now, some specialized searches, e.g. blog search are tbm=

Automatically generated documentation
for commands defined in module  emacspeak-google.

@c Caught emacspeak-google-show-toolbelt

@c Caught emacspeak-google-sign-in

@c Caught emacspeak-google-sign-out

@c Caught emacspeak-google-toolbelt-change

@c Caught emacspeak-google-toolbelt-change-Shopping

@c Caught emacspeak-google-toolbelt-change-blog

@c Caught emacspeak-google-toolbelt-change-books

@c Caught emacspeak-google-toolbelt-change-books-format

@c Caught emacspeak-google-toolbelt-change-books-type

@c Caught emacspeak-google-toolbelt-change-books-viewability

@c Caught emacspeak-google-toolbelt-change-commercial

@c Caught emacspeak-google-toolbelt-change-commercial-prices

@c Caught emacspeak-google-toolbelt-change-date-filter

@c Caught emacspeak-google-toolbelt-change-discussions

@c Caught emacspeak-google-toolbelt-change-duration

@c Caught emacspeak-google-toolbelt-change-forums

@c Caught emacspeak-google-toolbelt-change-images

@c Caught emacspeak-google-toolbelt-change-literal

@c Caught emacspeak-google-toolbelt-change-news

@c Caught emacspeak-google-toolbelt-change-non-commercial

@c Caught emacspeak-google-toolbelt-change-patents

@c Caught emacspeak-google-toolbelt-change-places

@c Caught emacspeak-google-toolbelt-change-recent

@c Caught emacspeak-google-toolbelt-change-recipes

@c Caught emacspeak-google-toolbelt-change-reviews

@c Caught emacspeak-google-toolbelt-change-social

@c Caught emacspeak-google-toolbelt-change-sort-by-date

@c Caught emacspeak-google-toolbelt-change-structured-snippets

@c Caught emacspeak-google-toolbelt-change-timeline

@c Caught emacspeak-google-toolbelt-change-timeline-high

@c Caught emacspeak-google-toolbelt-change-timeline-low

@c Caught emacspeak-google-toolbelt-change-video

@c Caught emacspeak-google-toolbelt-change-web-history-not-visited

@c Caught emacspeak-google-toolbelt-change-web-history-visited

@node emacspeak-gridtext
@section emacspeak-gridtext

Commentary:
Emacspeak's table browsing mode allows one to
efficiently access  content that is tabular in nature.
That module also provides functions for infering table
structure where possible.
Often, such structure is hard to infer automatically
--but might be known to the user 
e.g. treat columns 1 through 30 as one column of a table
and so on.
This module allows the user to specify a conceptual grid
that is "overlaid" on the region of text to turn it into
a table for tabular browsing. For now, elements of the
grid are "one line" high --but that may change in the
future if necessary. This module is useful for browsing
structured text files and the output from programs that
tabulate their output.
It's also useful for handling multicolumn text.

Automatically generated documentation
for commands defined in module  emacspeak-gridtext.

@c Caught emacspeak-gridtext-apply

@c Caught emacspeak-gridtext-load

@c Caught emacspeak-gridtext-save

@node emacspeak-hide
@section emacspeak-hide

Commentary:
Flexible hide and show for emacspeak.
This module allows one to easily hide or expose
blocks of lines starting with a common prefix.
It is motivated by the need to flexibly hide quoted text in email
but is designed to be more general.
the prefix parsing is inspired by filladapt.el

Automatically generated documentation
for commands defined in module  emacspeak-hide.

@c Caught emacspeak-hide-or-expose-all-blocks

@c Caught emacspeak-hide-or-expose-block

@c Caught emacspeak-hide-speak-block-sans-prefix

@node emacspeak-ibuffer
@section emacspeak-ibuffer

Commentary:
speech-enable ibuffer.el
this is an alternative to buffer-menu

Automatically generated documentation
for commands defined in module  emacspeak-ibuffer.

@c Caught emacspeak-ibuffer-speak-buffer-line

@node emacspeak-imenu
@section emacspeak-imenu

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-imenu.

@c Caught emacspeak-imenu-goto-next-index-position

@c Caught emacspeak-imenu-goto-previous-index-position

@c Caught emacspeak-imenu-speak-this-section

@node emacspeak-info
@section emacspeak-info

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-info.

@c Caught emacspeak-info-speak-header

@c Caught emacspeak-info-wizard

@node emacspeak-jabber
@section emacspeak-jabber

Commentary:
emacs-jabber.el implements a  jabber client for emacs
emacs-jabber is hosted at sourceforge.
I use emacs-jabber with my gmail.com account

Automatically generated documentation
for commands defined in module  emacspeak-jabber.

@c Caught emacspeak-jabber-chat-next-message

@c Caught emacspeak-jabber-chat-previous-message

@c Caught emacspeak-jabber-chat-speak-this-message

@c Caught emacspeak-jabber-popup-roster

@node emacspeak-keymap
@section emacspeak-keymap

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-keymap.

@c Caught emacspeak-keymap-choose-new-emacspeak-prefix

@node emacspeak-librivox
@section emacspeak-librivox

Commentary:
LIBRIVOX == http://wwwlibrivox.org Free Audio Books
It provides a simple Web  API http://wiki.librivox.org/index.php/LibriVoxAPI
This module implements an Emacspeak Librivox client.

Automatically generated documentation
for commands defined in module  emacspeak-librivox.

@c Caught emacspeak-librivox

@c Caught emacspeak-librivox-fetch-catalog

@c Caught emacspeak-librivox-mode

@c Caught emacspeak-librivox-open-rss

@c Caught emacspeak-librivox-open-url

@c Caught emacspeak-librivox-play

@c Caught emacspeak-librivox-search-author

@c Caught emacspeak-librivox-search-genre

@c Caught emacspeak-librivox-search-title

@node emacspeak-loaddefs
@section emacspeak-loaddefs

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-loaddefs.

@c Caught emacspeak-mark-forward-mark

@c Caught emacspeak-toggle-comint-output-monitor

@node emacspeak-m-player
@section emacspeak-m-player

Commentary:
Defines a simple derived mode for interacting with mplayer.
mplayer  is a versatile media player capable of playing many
streaming formats  and is especially useful for playing windows
media (WMA) and streaming windows media (ASF) files.
mplayer is available  on the WWW:
RPM package
http://mirrors.sctpc.com/dominik/linux/pkgs/mplayer/i586/mplayer-0.90pre5-2.i586.rpm
You may need the  win32 codecs which can be downloaded from 
http://ftp.lug.udel.edu/MPlayer/releases/w32codec-0.60.tar.bz2
Mplayer FAQ at
http://www.mplayerhq.hu/DOCS/faq.html
Mplayer docs at 
http://www.mplayerhq.hu/DOCS/

Automatically generated documentation
for commands defined in module  emacspeak-m-player.

@c Caught emacspeak-m-player-add-equalizer

@c Caught emacspeak-m-player-add-filter

@c Caught emacspeak-m-player-alt-src-step

@c Caught emacspeak-m-player-backward-10min

@c Caught emacspeak-m-player-backward-10s

@c Caught emacspeak-m-player-backward-1min

@c Caught emacspeak-m-player-balance

@c Caught emacspeak-m-player-beginning-of-track

@c Caught emacspeak-m-player-bind-accelerator

@c Caught emacspeak-m-player-command

@c Caught emacspeak-m-player-customize-options

@c Caught emacspeak-m-player-display-position

@c Caught emacspeak-m-player-double-speed

@c Caught emacspeak-m-player-end-of-track

@c Caught emacspeak-m-player-equalizer-control

@c Caught emacspeak-m-player-faster

@c Caught emacspeak-m-player-forward-10min

@c Caught emacspeak-m-player-forward-10s

@c Caught emacspeak-m-player-forward-1min

@c Caught emacspeak-m-player-get-length

@c Caught emacspeak-m-player-half-speed

@c Caught emacspeak-m-player-load

@c Caught emacspeak-m-player-load-file

@c Caught emacspeak-m-player-load-playlist

@c Caught emacspeak-m-player-mode

@c Caught emacspeak-m-player-next-track

@c Caught emacspeak-m-player-pause

@c Caught emacspeak-m-player-play-tracks-jump

@c Caught emacspeak-m-player-play-tree-up

@c Caught emacspeak-m-player-previous-track

@c Caught emacspeak-m-player-quit

@c Caught emacspeak-m-player-reset-options

@c Caught emacspeak-m-player-reset-speed

@c Caught emacspeak-m-player-resume

@c Caught emacspeak-m-player-scale-speed

@c Caught emacspeak-m-player-seek-absolute

@c Caught emacspeak-m-player-seek-relative

@c Caught emacspeak-m-player-shuffle

@c Caught emacspeak-m-player-slave-command

@c Caught emacspeak-m-player-slower

@c Caught emacspeak-m-player-speak-current-info

@c Caught emacspeak-m-player-speak-mode-line

@c Caught emacspeak-m-player-url

@c Caught emacspeak-m-player-volume-change

@c Caught emacspeak-m-player-volume-down

@c Caught emacspeak-m-player-volume-up

@c Caught emacspeak-m-player-youtube-player

@c Caught emacspeak-multimedia

@node emacspeak-madplay
@section emacspeak-madplay

Commentary:
Defines a simple derived mode for interacting with
madplay.
madplay navigation commands  work via single keystrokes.

Automatically generated documentation
for commands defined in module  emacspeak-madplay.

@c Caught emacspeak-aumix

@c Caught emacspeak-madplay

@c Caught emacspeak-madplay-madplay-call-command

@c Caught emacspeak-madplay-madplay-command

@c Caught emacspeak-madplay-mode

@node emacspeak-man
@section emacspeak-man

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-man.

@c Caught emacspeak-man-browse-man-page

@c Caught emacspeak-man-speak-this-section

@node emacspeak-mpg123
@section emacspeak-mpg123

Commentary:
This module speech-enables  MPG123
MPG123 is an MP3 player.

Automatically generated documentation
for commands defined in module  emacspeak-mpg123.

@c Caught emacspeak-mp3-playlist-play

@c Caught emacspeak-mp3-playlist-skip

@c Caught emacspeak-mp3-playlist-stop

@c Caught emacspeak-mpg123-backward-minute

@c Caught emacspeak-mpg123-forward-minute

@c Caught emacspeak-mpg123-speak-current-time

@c Caught emacspeak-mpg123-speak-filename

@c Caught emacspeak-mpg123-speak-length

@c Caught emacspeak-mpg123-speak-title

@node emacspeak-npr
@section emacspeak-npr

Commentary:
NPR == http://wwwnpr.org National Public Radio in the US
It provides a simple Web  API http://www.npr.org/api/
This module implements an Emacspeak Npr client.

For now, users will need to get their own API key

Automatically generated documentation
for commands defined in module  emacspeak-npr.

@c Caught emacspeak-npr-listing

@c Caught emacspeak-npr-listing-url-executor

@c Caught emacspeak-npr-view

@node emacspeak-ocr
@section emacspeak-ocr

Commentary:
This module defines Emacspeak front-end to OCR.
This module assumes that sane is installed and working
for image acquisition,
and that there is an OCR engine that can take acquired
images and produce text.
Prerequisites:
Sane installed and working.
scanimage to generate tiff files from scanner.
tiffcp to compress the tiff file.
working ocr executable 
by default this module assumes that the OCR executable
is named "ocr"

Automatically generated documentation
for commands defined in module  emacspeak-ocr.

@c Caught emacspeak-ocr

@c Caught emacspeak-ocr-backward-page

@c Caught emacspeak-ocr-customize

@c Caught emacspeak-ocr-flipflop-and-recognize-image

@c Caught emacspeak-ocr-forward-page

@c Caught emacspeak-ocr-mode

@c Caught emacspeak-ocr-name-document

@c Caught emacspeak-ocr-open-working-directory

@c Caught emacspeak-ocr-page

@c Caught emacspeak-ocr-read-current-page

@c Caught emacspeak-ocr-recognize-image

@c Caught emacspeak-ocr-save-current-page

@c Caught emacspeak-ocr-scan-and-recognize

@c Caught emacspeak-ocr-scan-image

@c Caught emacspeak-ocr-scan-photo

@c Caught emacspeak-ocr-set-compress-image-options

@c Caught emacspeak-ocr-set-scan-image-options

@c Caught emacspeak-ocr-write-document

@node emacspeak-outline
@section emacspeak-outline

Commentary:
Provide additional advice to outline-mode

Automatically generated documentation
for commands defined in module  emacspeak-outline.

@c Caught emacspeak-outline-speak-backward-heading

@c Caught emacspeak-outline-speak-forward-heading

@c Caught emacspeak-outline-speak-next-heading

@c Caught emacspeak-outline-speak-previous-heading

@c Caught emacspeak-outline-speak-this-heading

@node emacspeak-pianobar
@section emacspeak-pianobar

Commentary:
PIANOBAR ==  Pandora Client for Emacs

pianobar git://github.com/PromyLOPh/pianobar.git
Is a stand-alone client for Pandora Radio.
pianobar.el available on the Emacs Wiki at
http://www.emacswiki.org/emacs/pianobar.el
Provides access to Pandora Radio via pianobar from the comfort of Emacs.
This module speech-enables Pianobar and enhances it for the Complete Audio Desktop.

Automatically generated documentation
for commands defined in module  emacspeak-pianobar.

@c Caught emacspeak-pianobar

@c Caught emacspeak-pianobar-command

@c Caught emacspeak-pianobar-electric-mode-toggle

@c Caught emacspeak-pianobar-switch-to-preset

@node emacspeak-pronounce
@section emacspeak-pronounce

Commentary:
This module implements user customizable pronunciation dictionaries
for emacspeak. Custom pronunciations can be defined per file, per
directory and/or per major mode. Emacspeak maintains a persistent
user dictionary upon request and loads these in new emacspeak
sessions. This module implements the user interface to the custom
dictionary as well as providing the internal API used by the rest
of emacspeak in using the dictionary.
Algorithm:

The persistent dictionary is a hash table where the hash keys are
filenames, directory names, or major-mode names. The hash values
are association lists defining the dictionary. Users of this module
can retrieve a dictionary made up of all applicable association
lists for a given file.

Automatically generated documentation
for commands defined in module  emacspeak-pronounce.

@c Caught emacspeak-pronounce-clear-dictionaries

@c Caught emacspeak-pronounce-define-local-pronunciation

@c Caught emacspeak-pronounce-define-pronunciation

@c Caught emacspeak-pronounce-define-template-pronunciation

@c Caught emacspeak-pronounce-dispatch

@c Caught emacspeak-pronounce-edit-pronunciations

@c Caught emacspeak-pronounce-load-dictionaries

@c Caught emacspeak-pronounce-refresh-pronunciations

@c Caught emacspeak-pronounce-save-dictionaries

@c Caught emacspeak-pronounce-toggle-use-of-dictionaries

@c Caught emacspeak-pronounce-yank-word

@node emacspeak-redefine
@section emacspeak-redefine

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-redefine.

@c Caught emacspeak-backward-char

@c Caught emacspeak-forward-char

@c Caught emacspeak-self-insert-command

@node emacspeak-remote
@section emacspeak-remote

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-remote.

@c Caught emacspeak-remote-connect-to-server

@c Caught emacspeak-remote-edit-current-remote-hostname

@c Caught emacspeak-remote-home

@c Caught emacspeak-remote-quick-connect-to-server

@c Caught emacspeak-remote-quick-connect-via-ssh

@c Caught emacspeak-remote-ssh-to-server

@node emacspeak-rmail
@section emacspeak-rmail

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-rmail.

@c Caught emacspeak-rmail-speak-current-message-labels

@c Caught emacspeak-rmail-summarize-current-message

@node emacspeak-solitaire
@section emacspeak-solitaire

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-solitaire.

@c Caught emacspeak-solitaire-show-column

@c Caught emacspeak-solitaire-show-row

@c Caught emacspeak-solitaire-speak-coordinates

@node emacspeak-sounds
@section emacspeak-sounds

Commentary:
This module provides the interface for generating auditory icons in emacspeak.
Design goal:
1) Auditory icons should be used to provide additional feedback,
not as a gimmick.
2) The interface should be usable at all times without the icons:
e.g. when on a machine without a sound card.
3) General principle for when to use an icon:
Convey information about events taking place in parallel.
For instance, if making a selection automatically moves the current focus
to the next choice,
We speak the next choice, while indicating the fact that something was selected with a sound cue.
 This interface will assume the availability of a shell command "play"
that can take one or more sound files and play them.
This module will also provide a mapping between names in the elisp world and actual sound files.
Modules that wish to use auditory icons should use these names, instead of actual file names.
As of Emacspeak 13.0, this module defines a themes
architecture for  auditory icons.
Sound files corresponding to a given theme are found in
appropriate subdirectories of emacspeak-sounds-directory

Automatically generated documentation
for commands defined in module  emacspeak-sounds.

@c Caught emacspeak-audio-setup

@c Caught emacspeak-play-all-icons

@c Caught emacspeak-set-auditory-icon-player

@c Caught emacspeak-sounds-reset-local-player

@c Caught emacspeak-sounds-reset-sound

@c Caught emacspeak-sounds-select-theme

@c Caught emacspeak-toggle-auditory-icons

@node emacspeak-speak
@section emacspeak-speak

Commentary:
This module defines the core speech services used by emacspeak.
It depends on the speech server interface modules
It protects other parts of emacspeak
from becoming dependent on the speech server modules

Automatically generated documentation
for commands defined in module  emacspeak-speak.

@c Caught emacspeak-blink-matching-open

@c Caught emacspeak-completion-pick-completion

@c Caught emacspeak-completions-move-to-completion-group

@c Caught emacspeak-dial-dtk

@c Caught emacspeak-execute-repeatedly

@c Caught emacspeak-goto-percent

@c Caught emacspeak-mark-backward-mark

@c Caught emacspeak-owindow-next-line

@c Caught emacspeak-owindow-previous-line

@c Caught emacspeak-owindow-scroll-down

@c Caught emacspeak-owindow-scroll-up

@c Caught emacspeak-owindow-speak-line

@c Caught emacspeak-read-next-line

@c Caught emacspeak-read-next-word

@c Caught emacspeak-read-previous-line

@c Caught emacspeak-read-previous-word

@c Caught emacspeak-search

@c Caught emacspeak-shell-command

@c Caught emacspeak-silence

@c Caught emacspeak-speak-and-skip-extent-upto-char

@c Caught emacspeak-speak-and-skip-extent-upto-this-char

@c Caught emacspeak-speak-browse-buffer

@c Caught emacspeak-speak-buffer

@c Caught emacspeak-speak-buffer-filename

@c Caught emacspeak-speak-buffer-interactively

@c Caught emacspeak-speak-char

@c Caught emacspeak-speak-char-name

@c Caught emacspeak-speak-completions-if-available

@c Caught emacspeak-speak-continuously

@c Caught emacspeak-speak-current-column

@c Caught emacspeak-speak-current-field

@c Caught emacspeak-speak-current-kill

@c Caught emacspeak-speak-current-mark

@c Caught emacspeak-speak-current-percentage

@c Caught emacspeak-speak-current-window

@c Caught emacspeak-speak-display-char

@c Caught emacspeak-speak-face-interval-and-move

@c Caught emacspeak-speak-front-of-buffer

@c Caught emacspeak-speak-header-line

@c Caught emacspeak-speak-help

@c Caught emacspeak-speak-help-interactively

@c Caught emacspeak-speak-hostname

@c Caught emacspeak-speak-line

@c Caught emacspeak-speak-line-interactively

@c Caught emacspeak-speak-line-number

@c Caught emacspeak-speak-line-set-column-filter

@c Caught emacspeak-speak-load-directory-settings

@c Caught emacspeak-speak-message-again

@c Caught emacspeak-speak-message-at-time

@c Caught emacspeak-speak-microseconds-since-epoch

@c Caught emacspeak-speak-milliseconds-since-epoch

@c Caught emacspeak-speak-minibuffer

@c Caught emacspeak-speak-minor-mode-line

@c Caught emacspeak-speak-mode-line

@c Caught emacspeak-speak-next-face-chunk

@c Caught emacspeak-speak-next-field

@c Caught emacspeak-speak-next-personality-chunk

@c Caught emacspeak-speak-next-window

@c Caught emacspeak-speak-other-buffer

@c Caught emacspeak-speak-other-window

@c Caught emacspeak-speak-page

@c Caught emacspeak-speak-page-interactively

@c Caught emacspeak-speak-paragraph

@c Caught emacspeak-speak-paragraph-interactively

@c Caught emacspeak-speak-preceding-char

@c Caught emacspeak-speak-predefined-window

@c Caught emacspeak-speak-previous-face-chunk

@c Caught emacspeak-speak-previous-field

@c Caught emacspeak-speak-previous-personality-chunk

@c Caught emacspeak-speak-previous-window

@c Caught emacspeak-speak-rectangle

@c Caught emacspeak-speak-region

@c Caught emacspeak-speak-rest-of-buffer

@c Caught emacspeak-speak-seconds-since-epoch

@c Caught emacspeak-speak-sentence

@c Caught emacspeak-speak-set-display-table

@c Caught emacspeak-speak-set-mode-punctuations

@c Caught emacspeak-speak-sexp

@c Caught emacspeak-speak-sexp-interactively

@c Caught emacspeak-speak-show-active-network-interfaces

@c Caught emacspeak-speak-skim-buffer

@c Caught emacspeak-speak-skim-next-paragraph

@c Caught emacspeak-speak-skim-paragraph

@c Caught emacspeak-speak-spaces-at-point

@c Caught emacspeak-speak-spell-current-word

@c Caught emacspeak-speak-text-range

@c Caught emacspeak-speak-this-face-chunk

@c Caught emacspeak-speak-this-personality-chunk

@c Caught emacspeak-speak-time

@c Caught emacspeak-speak-version

@c Caught emacspeak-speak-voice-annotate-paragraphs

@c Caught emacspeak-speak-window-information

@c Caught emacspeak-speak-word

@c Caught emacspeak-speak-word-interactively

@c Caught emacspeak-speak-world-clock

@c Caught emacspeak-switch-to-reference-buffer

@c Caught emacspeak-toggle-action-mode

@c Caught emacspeak-toggle-audio-indentation

@c Caught emacspeak-toggle-character-echo

@c Caught emacspeak-toggle-comint-autospeak

@c Caught emacspeak-toggle-header-line

@c Caught emacspeak-toggle-line-echo

@c Caught emacspeak-toggle-mail-alert

@c Caught emacspeak-toggle-show-point

@c Caught emacspeak-toggle-speak-line-invert-filter

@c Caught emacspeak-toggle-speak-messages

@c Caught emacspeak-toggle-word-echo

@c Caught emacspeak-use-customized-blink-paren

@c Caught emacspeak-voiceify-rectangle

@c Caught emacspeak-voiceify-region

@c Caught emacspeak-zap-tts

@node emacspeak-speedbar
@section emacspeak-speedbar

Commentary:
This module advises speedbar.el for use with Emacs.  The
latest speedbar can be obtained from
ftp://ftp.ultranet.com/pub/zappo/ This module ensures
that speedbar works smoothly outside a windowing system
in addition to speech enabling all interactive
commands. Emacspeak also adds an Emacspeak environment
specific entry point to speedbar
--emacspeak-speedbar-goto-speedbar-- and binds this

Automatically generated documentation
for commands defined in module  emacspeak-speedbar.

@c Caught emacspeak-speedbar-click

@c Caught emacspeak-speedbar-goto-speedbar

@node emacspeak-sudoku
@section emacspeak-sudoku

Commentary:
Playing SuDoku using speech output.
Written to discover what type of feedback one needs for  this
task.
See http://emacspeak.blogspot.com/2006/02/playing-sudoku-using-auditory-feedback.html

Automatically generated documentation
for commands defined in module  emacspeak-sudoku.

@c Caught emacspeak-sudoku-board-columns-summarize

@c Caught emacspeak-sudoku-board-distribution-summarize

@c Caught emacspeak-sudoku-board-rows-summarize

@c Caught emacspeak-sudoku-board-sub-squares-summarize

@c Caught emacspeak-sudoku-board-summarizer

@c Caught emacspeak-sudoku-down-sub-square

@c Caught emacspeak-sudoku-erase-current-column

@c Caught emacspeak-sudoku-erase-current-row

@c Caught emacspeak-sudoku-erase-current-sub-square

@c Caught emacspeak-sudoku-hint

@c Caught emacspeak-sudoku-history-pop

@c Caught emacspeak-sudoku-history-push

@c Caught emacspeak-sudoku-how-many-remaining

@c Caught emacspeak-sudoku-next-sub-square

@c Caught emacspeak-sudoku-previous-sub-square

@c Caught emacspeak-sudoku-speak-current-cell-coordinates

@c Caught emacspeak-sudoku-speak-current-cell-value

@c Caught emacspeak-sudoku-speak-current-column

@c Caught emacspeak-sudoku-speak-current-row

@c Caught emacspeak-sudoku-speak-current-sub-square

@c Caught emacspeak-sudoku-speak-remaining-in-column

@c Caught emacspeak-sudoku-speak-remaining-in-row

@c Caught emacspeak-sudoku-speak-remaining-in-sub-square

@c Caught emacspeak-sudoku-up-sub-square

@node emacspeak-table-ui
@section emacspeak-table-ui

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-table-ui.

@c Caught emacspeak-table-copy-current-element-to-kill-ring

@c Caught emacspeak-table-copy-current-element-to-register

@c Caught emacspeak-table-copy-to-clipboard

@c Caught emacspeak-table-display-table-in-region

@c Caught emacspeak-table-find-csv-file

@c Caught emacspeak-table-find-file

@c Caught emacspeak-table-get-entry-with-headers

@c Caught emacspeak-table-goto

@c Caught emacspeak-table-goto-bottom

@c Caught emacspeak-table-goto-left

@c Caught emacspeak-table-goto-right

@c Caught emacspeak-table-goto-top

@c Caught emacspeak-table-next-column

@c Caught emacspeak-table-next-row

@c Caught emacspeak-table-paste-from-clipboard

@c Caught emacspeak-table-previous-column

@c Caught emacspeak-table-previous-row

@c Caught emacspeak-table-search

@c Caught emacspeak-table-search-column

@c Caught emacspeak-table-search-headers

@c Caught emacspeak-table-search-row

@c Caught emacspeak-table-select-automatic-speaking-method

@c Caught emacspeak-table-sort-on-current-column

@c Caught emacspeak-table-speak-both-headers-and-element

@c Caught emacspeak-table-speak-column-filtered

@c Caught emacspeak-table-speak-column-header-and-element

@c Caught emacspeak-table-speak-coordinates

@c Caught emacspeak-table-speak-current-element

@c Caught emacspeak-table-speak-dimensions

@c Caught emacspeak-table-speak-row-filtered

@c Caught emacspeak-table-speak-row-header-and-element

@c Caught emacspeak-table-ui-filter-load

@c Caught emacspeak-table-ui-filter-save

@c Caught emacspeak-table-view-csv-buffer

@node emacspeak-tabulate
@section emacspeak-tabulate

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-tabulate.

@c Caught emacspeak-tabulate-region

@node emacspeak-tapestry
@section emacspeak-tapestry

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-tapestry.

@c Caught emacspeak-tapestry-describe-tapestry

@c Caught emacspeak-tapestry-select-window-by-name

@node emacspeak-tar
@section emacspeak-tar

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-tar.

@c Caught emacspeak-tar-speak-file-date

@c Caught emacspeak-tar-speak-file-permissions

@c Caught emacspeak-tar-speak-file-size

@node emacspeak-tetris
@section emacspeak-tetris

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-tetris.

@c Caught emacspeak-tetris-goto-bottom-row

@c Caught emacspeak-tetris-goto-top-row

@c Caught emacspeak-tetris-speak-column

@c Caught emacspeak-tetris-speak-coordinates

@c Caught emacspeak-tetris-speak-current-shape

@c Caught emacspeak-tetris-speak-current-shape-and-coordinates

@c Caught emacspeak-tetris-speak-next-shape

@c Caught emacspeak-tetris-speak-row

@c Caught emacspeak-tetris-speak-row-number

@c Caught emacspeak-tetris-speak-score

@c Caught emacspeak-tetris-speak-x-coordinate

@node emacspeak-tnt
@section emacspeak-tnt

Commentary:
Speech-enables TNT -- the Emacs AOL Instant Messenger
client 

Automatically generated documentation
for commands defined in module  emacspeak-tnt.

@c Caught emacspeak-tnt-toggle-autospeak

@node emacspeak-url-template
@section emacspeak-url-template

Commentary:
It is often useful to have ``parametrized hot list entries''
i.e., hotlist entries  that are ``templates'' for the
actual URL.
The user provides values for the parametrized portions
of the URL e.g. the date.
See @xref{URL Templates}, for details on the URL templates
that are presently defined.

Automatically generated documentation
for commands defined in module  emacspeak-url-template.

@c Caught emacspeak-url-template-fetch

@c Caught emacspeak-url-template-help

@c Caught emacspeak-url-template-load

@c Caught emacspeak-url-template-save

@node emacspeak-view
@section emacspeak-view

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-view.

@c Caught emacspeak-view-line-to-top

@node emacspeak-vm
@section emacspeak-vm

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-vm.

@c Caught emacspeak-vm-browse-message

@c Caught emacspeak-vm-catch-up-all-messages

@c Caught emacspeak-vm-locate-subject-line

@c Caught emacspeak-vm-mode-line

@c Caught emacspeak-vm-next-button

@c Caught emacspeak-vm-speak-labels

@c Caught emacspeak-vm-speak-message

@c Caught emacspeak-vm-yank-header

@node emacspeak-w3
@section emacspeak-w3

Commentary:
Ensure that speech support for W3 gets installed and
loaded correctly.
The emacs W3 browser comes with builtin support for
Emacspeak and ACSS

Automatically generated documentation
for commands defined in module  emacspeak-w3.

@c Caught emacspeak-w3-curl-url-under-point

@c Caught emacspeak-w3-customize-base-uri-pronunciation

@c Caught emacspeak-w3-do-onclick

@c Caught emacspeak-w3-javascript-follow-link

@c Caught emacspeak-w3-jump-to-submit

@c Caught emacspeak-w3-lynx-url-under-point

@c Caught emacspeak-w3-next-block

@c Caught emacspeak-w3-next-doc-element

@c Caught emacspeak-w3-next-parsed-item

@c Caught emacspeak-w3-previous-doc-element

@c Caught emacspeak-w3-show-anchor-class

@c Caught emacspeak-w3-show-http-headers

@c Caught emacspeak-w3-speak-next-block

@c Caught emacspeak-w3-speak-next-element

@c Caught emacspeak-w3-speak-this-element

@c Caught emacspeak-w3-toggle-table-borders

@node emacspeak-w3m
@section emacspeak-w3m

Commentary:

Automatically generated documentation
for commands defined in module  emacspeak-w3m.

@c Caught emacspeak-m-player

@c Caught emacspeak-w3m-preview-this-buffer

@node emacspeak-we
@section emacspeak-we

Commentary:
we is for webedit
Invoke XSLT to edit/transform Web pages before they get
rendered.
we makes emacspeak's webedit layer independent of a given
Emacs web browser like W3 or W3M
This module will use the abstraction provided by browse-url
to handle Web pages.
Module emacspeak-webutils provides the needed additional
abstractions not already covered by browse-url

Automatically generated documentation
for commands defined in module  emacspeak-we.

@c Caught emacspeak-we-class-filter-and-follow

@c Caught emacspeak-we-class-filter-and-follow-link

@c Caught emacspeak-we-count-matches

@c Caught emacspeak-we-count-nested-tables

@c Caught emacspeak-we-count-tables

@c Caught emacspeak-we-extract-by-class

@c Caught emacspeak-we-extract-by-class-list

@c Caught emacspeak-we-extract-by-id

@c Caught emacspeak-we-extract-by-id-list

@c Caught emacspeak-we-extract-by-property

@c Caught emacspeak-we-extract-by-role

@c Caught emacspeak-we-extract-id-list-text

@c Caught emacspeak-we-extract-id-text

@c Caught emacspeak-we-extract-matching-urls

@c Caught emacspeak-we-extract-media-streams

@c Caught emacspeak-we-extract-media-streams-under-point

@c Caught emacspeak-we-extract-nested-table

@c Caught emacspeak-we-extract-nested-table-list

@c Caught emacspeak-we-extract-print-streams

@c Caught emacspeak-we-extract-table-by-match

@c Caught emacspeak-we-extract-table-by-position

@c Caught emacspeak-we-extract-tables-by-match-list

@c Caught emacspeak-we-extract-tables-by-position-list

@c Caught emacspeak-we-follow-and-extract-main

@c Caught emacspeak-we-follow-and-filter-by-id

@c Caught emacspeak-we-junk-by-class

@c Caught emacspeak-we-junk-by-class-list

@c Caught emacspeak-we-style-filter

@c Caught emacspeak-we-toggle-xsl-keep-result

@c Caught emacspeak-we-url-expand-and-execute

@c Caught emacspeak-we-url-rewrite-and-follow

@c Caught emacspeak-we-xpath-filter-and-follow

@c Caught emacspeak-we-xpath-junk-and-follow

@c Caught emacspeak-we-xsl-toggle

@c Caught emacspeak-we-xslt-apply

@c Caught emacspeak-we-xslt-filter

@c Caught emacspeak-we-xslt-junk

@c Caught emacspeak-we-xslt-select

@node emacspeak-websearch
@section emacspeak-websearch

Commentary:
This module provides utility functions for searching the WWW

Automatically generated documentation
for commands defined in module  emacspeak-websearch.

@c Caught emacspeak-websearch-accessible-google

@c Caught emacspeak-websearch-amazon-search

@c Caught emacspeak-websearch-ask-jeeves

@c Caught emacspeak-websearch-biblio-search

@c Caught emacspeak-websearch-blinkx-search

@c Caught emacspeak-websearch-citeseer-search

@c Caught emacspeak-websearch-company-news

@c Caught emacspeak-websearch-cpan-search

@c Caught emacspeak-websearch-ctan-search

@c Caught emacspeak-websearch-dispatch

@c Caught emacspeak-websearch-display-form

@c Caught emacspeak-websearch-ebay-search

@c Caught emacspeak-websearch-exchange-rate-convertor

@c Caught emacspeak-websearch-foldoc-search

@c Caught emacspeak-websearch-freshmeat-search

@c Caught emacspeak-websearch-google

@c Caught emacspeak-websearch-google-advanced

@c Caught emacspeak-websearch-google-feeling-lucky

@c Caught emacspeak-websearch-google-mobile

@c Caught emacspeak-websearch-google-news

@c Caught emacspeak-websearch-google-sak

@c Caught emacspeak-websearch-google-search-in-date-range

@c Caught emacspeak-websearch-google-specialize

@c Caught emacspeak-websearch-google-usenet-advanced

@c Caught emacspeak-websearch-gutenberg

@c Caught emacspeak-websearch-help

@c Caught emacspeak-websearch-map-yahoo-directions-search

@c Caught emacspeak-websearch-merriam-webster-search

@c Caught emacspeak-websearch-news-yahoo

@c Caught emacspeak-websearch-open-directory-search

@c Caught emacspeak-websearch-quotes-yahoo-search

@c Caught emacspeak-websearch-recorded-books-search

@c Caught emacspeak-websearch-rpm-find

@c Caught emacspeak-websearch-software-search

@c Caught emacspeak-websearch-sourceforge-search

@c Caught emacspeak-websearch-swik-search

@c Caught emacspeak-websearch-usenet

@c Caught emacspeak-websearch-usenet-search

@c Caught emacspeak-websearch-w3c-search

@c Caught emacspeak-websearch-weather

@c Caught emacspeak-websearch-wikipedia-search

@c Caught emacspeak-websearch-yahoo

@c Caught emacspeak-websearch-yahoo-exchange-rate-convertor

@c Caught emacspeak-websearch-yahoo-historical-chart

@node emacspeak-webspace
@section emacspeak-webspace

Commentary:
WEBSPACE == Smart Web Gadgets For The Emacspeak Desktop

Automatically generated documentation
for commands defined in module  emacspeak-webspace.

@c Caught emacspeak-webspace-feed-reader

@c Caught emacspeak-webspace-filter

@c Caught emacspeak-webspace-freebase-search

@c Caught emacspeak-webspace-google

@c Caught emacspeak-webspace-headlines

@c Caught emacspeak-webspace-headlines-browse

@c Caught emacspeak-webspace-headlines-update

@c Caught emacspeak-webspace-mode

@c Caught emacspeak-webspace-open

@c Caught emacspeak-webspace-transcode

@c Caught emacspeak-webspace-weather

@c Caught emacspeak-webspace-weather-update

@c Caught emacspeak-webspace-yank-link

@node emacspeak-webutils
@section emacspeak-webutils

Commentary:
This module provides common Web utilities for emacspeak.
This is to avoid duplication of code between emacspeak-w3.el
and emacspeak-w3m.el

Automatically generated documentation
for commands defined in module  emacspeak-webutils.

@c Caught emacspeak-webutils-google-extract-from-cache

@c Caught emacspeak-webutils-google-on-this-site

@c Caught emacspeak-webutils-google-similar-to-this-page

@c Caught emacspeak-webutils-google-who-links-to-this-page

@c Caught emacspeak-webutils-jump-to-title-in-content

@c Caught emacspeak-webutils-open-in-other-browser

@c Caught emacspeak-webutils-play-media-at-point

@c Caught emacspeak-webutils-transcode-current-url-via-google

@c Caught emacspeak-webutils-transcode-via-google

@node emacspeak-widget
@section emacspeak-widget

Commentary:
This module implements the necessary extensions to provide talking
widgets.

Automatically generated documentation
for commands defined in module  emacspeak-widget.

@c Caught emacspeak-widget-browse-widget-interactively

@c Caught emacspeak-widget-help

@c Caught emacspeak-widget-summarize-parent

@c Caught emacspeak-widget-summarize-widget-under-point

@c Caught emacspeak-widget-update-from-minibuffer

@node emacspeak-wizards
@section emacspeak-wizards

Commentary:
Contains various wizards for the Emacspeak desktop.

Automatically generated documentation
for commands defined in module  emacspeak-wizards.

@c Caught emacspeak-annotate-add-annotation

@c Caught emacspeak-clipboard-copy

@c Caught emacspeak-clipboard-paste

@c Caught emacspeak-copy-current-file

@c Caught emacspeak-curl

@c Caught emacspeak-customize

@c Caught emacspeak-customize-personal-settings

@c Caught emacspeak-cvs-berlios-get-project-snapshot

@c Caught emacspeak-cvs-get-anonymous

@c Caught emacspeak-cvs-gnu-get-project-snapshot

@c Caught emacspeak-cvs-sf-get-project-snapshot

@c Caught emacspeak-emergency-tts-restart

@c Caught emacspeak-frame-label-or-switch-to-labelled-frame

@c Caught emacspeak-frame-read-frame-label

@c Caught emacspeak-generate-documentation

@c Caught emacspeak-generate-texinfo-command-documentation

@c Caught emacspeak-generate-texinfo-option-documentation

@c Caught emacspeak-kill-buffer-quietly

@c Caught emacspeak-learn-emacs-mode

@c Caught emacspeak-link-current-file

@c Caught emacspeak-links

@c Caught emacspeak-lynx

@c Caught emacspeak-next-frame-or-buffer

@c Caught emacspeak-previous-frame-or-buffer

@c Caught emacspeak-root

@c Caught emacspeak-select-this-buffer-next-display

@c Caught emacspeak-select-this-buffer-other-window-display

@c Caught emacspeak-select-this-buffer-previous-display

@c Caught emacspeak-show-personality-at-point

@c Caught emacspeak-show-property-at-point

@c Caught emacspeak-skip-blank-lines-backward

@c Caught emacspeak-skip-blank-lines-forward

@c Caught emacspeak-speak-browse-linux-howto

@c Caught emacspeak-speak-popup-messages

@c Caught emacspeak-speak-run-shell-command

@c Caught emacspeak-speak-telephone-directory

@c Caught emacspeak-speak-this-buffer-next-display

@c Caught emacspeak-speak-this-buffer-other-window-display

@c Caught emacspeak-speak-this-buffer-previous-display

@c Caught emacspeak-ssh-tts-restart

@c Caught emacspeak-sudo

@c Caught emacspeak-sudo-edit

@c Caught emacspeak-switch-to-previous-buffer

@c Caught emacspeak-symlink-current-file

@c Caught emacspeak-view-emacspeak-doc

@c Caught emacspeak-view-emacspeak-faq

@c Caught emacspeak-view-emacspeak-news

@c Caught emacspeak-view-emacspeak-tips

@c Caught emacspeak-wizards-add-autoload-cookies

@c Caught emacspeak-wizards-braille

@c Caught emacspeak-wizards-byte-compile-current-buffer

@c Caught emacspeak-wizards-cleanup-shell-path

@c Caught emacspeak-wizards-comma-at-end-of-word

@c Caught emacspeak-wizards-count-slides-in-region

@c Caught emacspeak-wizards-cycle-browser

@c Caught emacspeak-wizards-cycle-to-next-buffer

@c Caught emacspeak-wizards-display-pod-as-manpage

@c Caught emacspeak-wizards-dvi-display

@c Caught emacspeak-wizards-dvi-mode

@c Caught emacspeak-wizards-edit-file-as-root

@c Caught emacspeak-wizards-end-of-word

@c Caught emacspeak-wizards-enumerate-matching-commands

@c Caught emacspeak-wizards-enumerate-matching-faces

@c Caught emacspeak-wizards-enumerate-obsolete-faces

@c Caught emacspeak-wizards-enumerate-uncovered-commands

@c Caught emacspeak-wizards-enumerate-unmapped-faces

@c Caught emacspeak-wizards-espeak-region

@c Caught emacspeak-wizards-espeak-string

@c Caught emacspeak-wizards-eww-buffer-list

@c Caught emacspeak-wizards-find-emacspeak-source

@c Caught emacspeak-wizards-find-file-as-root

@c Caught emacspeak-wizards-find-grep

@c Caught emacspeak-wizards-find-longest-line-in-region

@c Caught emacspeak-wizards-find-longest-paragraph-in-region

@c Caught emacspeak-wizards-find-shortest-line-in-region

@c Caught emacspeak-wizards-finder-find

@c Caught emacspeak-wizards-finder-mode

@c Caught emacspeak-wizards-fix-read-only-text

@c Caught emacspeak-wizards-fix-typo

@c Caught emacspeak-wizards-generate-finder

@c Caught emacspeak-wizards-generate-voice-sampler

@c Caught emacspeak-wizards-get-table-content-from-file

@c Caught emacspeak-wizards-get-table-content-from-url

@c Caught emacspeak-wizards-google-hits

@c Caught emacspeak-wizards-google-transcode

@c Caught emacspeak-wizards-how-many-matches

@c Caught emacspeak-wizards-i810-display-status

@c Caught emacspeak-wizards-js

@c Caught emacspeak-wizards-lacheck-buffer-file

@c Caught emacspeak-wizards-load-current-file

@c Caught emacspeak-wizards-move-and-speak

@c Caught emacspeak-wizards-next-bullet

@c Caught emacspeak-wizards-next-interactive-defun

@c Caught emacspeak-wizards-next-shell

@c Caught emacspeak-wizards-occur-header-lines

@c Caught emacspeak-wizards-pdf-open

@c Caught emacspeak-wizards-popup-input-buffer

@c Caught emacspeak-wizards-portfolio-quotes

@c Caught emacspeak-wizards-ppp-toggle

@c Caught emacspeak-wizards-ppt-display

@c Caught emacspeak-wizards-ppt-mode

@c Caught emacspeak-wizards-previous-bullet

@c Caught emacspeak-wizards-previous-shell

@c Caught emacspeak-wizards-refresh-shell-history

@c Caught emacspeak-wizards-rivo

@c Caught emacspeak-wizards-rpm-query-in-dired

@c Caught emacspeak-wizards-shell

@c Caught emacspeak-wizards-shell-toggle

@c Caught emacspeak-wizards-show-commentary

@c Caught emacspeak-wizards-show-environment-variable

@c Caught emacspeak-wizards-show-eval-result

@c Caught emacspeak-wizards-show-face

@c Caught emacspeak-wizards-show-memory-used

@c Caught emacspeak-wizards-speak-iso-datetime

@c Caught emacspeak-wizards-spot-words

@c Caught emacspeak-wizards-squeeze-blanks

@c Caught emacspeak-wizards-sunrise-sunset

@c Caught emacspeak-wizards-switch-shell

@c Caught emacspeak-wizards-term

@c Caught emacspeak-wizards-terminal

@c Caught emacspeak-wizards-tex-tie-current-word

@c Caught emacspeak-wizards-thanks-mail-signature

@c Caught emacspeak-wizards-toggle-mm-dd-yyyy-date-pronouncer

@c Caught emacspeak-wizards-toggle-yyyymmdd-date-pronouncer

@c Caught emacspeak-wizards-tpctl-display-status

@c Caught emacspeak-wizards-tramp-open-location

@c Caught emacspeak-wizards-unhex-uri

@c Caught emacspeak-wizards-units

@c Caught emacspeak-wizards-vc-n

@c Caught emacspeak-wizards-vc-viewer

@c Caught emacspeak-wizards-vc-viewer-mode

@c Caught emacspeak-wizards-vc-viewer-refresh

@c Caught emacspeak-wizards-vi-as-su-file

@c Caught emacspeak-wizards-view-buffers-filtered-by-mode

@c Caught emacspeak-wizards-view-buffers-filtered-by-this-mode

@c Caught emacspeak-wizards-view-url

@c Caught emacspeak-wizards-voice-sampler

@c Caught emacspeak-wizards-vpn-toggle

@c Caught emacspeak-wizards-xl-display

@c Caught emacspeak-wizards-xl-mode

@node emacspeak-xml-shell
@section emacspeak-xml-shell

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-xml-shell.

@c Caught emacspeak-xml-shell

@c Caught emacspeak-xml-shell-browse-current

@c Caught emacspeak-xml-shell-browse-result

@c Caught emacspeak-xml-shell-goto-children

@c Caught emacspeak-xml-shell-goto-next-child

@c Caught emacspeak-xml-shell-goto-parent

@c Caught emacspeak-xml-shell-goto-previous-child

@c Caught emacspeak-xml-shell-mode

@node emacspeak-xslt
@section emacspeak-xslt

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-xslt.

@c Caught emacspeak-xslt-view

@c Caught emacspeak-xslt-view-file

@c Caught emacspeak-xslt-view-region

@c Caught emacspeak-xslt-view-xml

@node emacspeak-zinf
@section emacspeak-zinf

Commentary:
Defines a simple derived mode for interacting with
zinf.
zinf == zinf is not freeamp
zinf navigation commands then work via single keystrokes.

Automatically generated documentation
for commands defined in module  emacspeak-zinf.

@c Caught emacspeak-zinf

@c Caught emacspeak-zinf-mode

@c Caught emacspeak-zinf-zinf-call-command

@c Caught emacspeak-zinf-zinf-command

@node emacspeak
@section emacspeak

Commentary:
The complete audio desktop.

Emacspeak extends Emacs to be a fully functional audio desktop.
This is the main emacspeak module.
It actually does very little:
It loads the various parts of the system.

Automatically generated documentation
for commands defined in module  emacspeak.

@c Caught emacspeak-describe-emacspeak

@c Caught emacspeak-submit-bug

@node voice-setup
@section voice-setup

Commentary:
A voice is to audio as a font is to a visual display.
A personality is to audio as a face is to a visual display.

Voice-lock-mode is a minor mode that causes your comments to be
spoken in one personality, strings in another, reserved words in another,
documentation strings in another, and so on.

Comments will be spoken in `emacspeak-voice-lock-comment-personality'.
Strings will be spoken in `emacspeak-voice-lock-string-personality'.
Function and variable names (in their defining forms) will be
 spoken in `emacspeak-voice-lock-function-name-personality'.
Reserved words will be spoken in `emacspeak-voice-lock-keyword-personality'.

To make the text you type be voiceified, use M-x voice-lock-mode.
When this minor mode is on, the voices of the current line are
updated with every insertion or deletion.

How faces map to voices: TTS engine specific modules e.g.,
dectalk-voices.el and outloud-voices.el define a standard set
of voice names.  This module maps standard "personality"
names to these pre-defined voices.  It does this via special
form def-voice-font which takes a personality name, a voice
name and a face name to set up the mapping between face and
personality, and personality and voice.
Newer Emacspeak modules should use voice-setup-add-map when
defining face->personality mappings.
Older code calls def-voice-font directly, but over time those
calls will be changed to the more succinct form provided by
voice-setup-add-map. For use from other modules, also see
function voice-setup-map-face which is useful when mapping a
single face.
Both voice-setup-add-map and voice-setup-map-face call
special form def-voice-font.

Special form def-voice-font sets up the personality name to
be available via custom.  new voices can be defined using CSS
style specifications see special form defvoice Voices defined
via defvoice can be customized via custom see the
documentation for defvoice.

Automatically generated documentation
for commands defined in module  voice-setup.

@c Caught voice-setup-list-voices

@c Caught voice-setup-toggle-silence-personality

@node emacspeak-bbc
@section emacspeak-bbc

No Commentary

Automatically generated documentation
for commands defined in module  emacspeak-bbc.

@c Caught emacspeak-bbc

@c Caught emacspeak-bbc-genre

@node emacspeak-org
@section emacspeak-org

Commentary:
Speech-enable org ---
 Org allows you to keep organized notes and todo lists.
Homepage: http://www.astro.uva.nl/~dominik/Tools/org/
or http://orgmode.org/

Automatically generated documentation
for commands defined in module  emacspeak-org.

@c Caught emacspeak-org-bookmark

@c Caught emacspeak-org-popup-input

@c Caught emacspeak-org-table-speak-current-element

No Commentary

Automatically generated documentation
for commands defined in module  nil.

@c Caught ad-Advice-emacspeak-eterm-copy-region-to-register

@c Caught ad-Advice-emacspeak-eterm-paste-register

@c Caught emacspeak-py-next-block

@c Caught emacspeak-py-previous-block
@node URL Templates 
@section  URL Templates

This section is generated automatically from the source-level documentation.
Any errors or corrections should be made to the source-level
documentation.
This section documents a total of 113 URL Templates.

All of these URL templates can be invoked via command
  @kbd{M-x emacspeak-url-template-fetch} normally bound to
  @kbd{C-e u}.
This command prompts for the name of the template, and completion
  is available via Emacs' minibuffer completion.
Each URL template carries out the following steps:
@itemize @bullet
@item Prompt for the relevant information.
@item Fetch the resulting URL using an appropriate fetcher.
@item Set up the resulting resource with appropriate
  customizations.
@end itemize

As an example, the URL templates that enable access to map directions
prompt for address and automatically
speak the relevant results.

@kbd{Air Traffic Control}

Find live streams for Air Traffic Control.

@kbd{Airport conditions}

Display airport conditions from the FAA.

@kbd{Amazon Product Details By ASIN}

Retrieve product details from Amazon by either ISBN or ASIN.

@kbd{Anonymize Google Search}

Logout from Google to do an anonymous search.

@kbd{Archive News Search}

Search Google Archive News.

@kbd{Ask Local Search}

Ask Local Search.

@kbd{Ask Walking Directions}

Walking directions from Ask.com

@kbd{BBC  iPlayer}

BBC iPlayer

@kbd{BBC Genre Using IPlayer}

BBC iPlayer Genre

@kbd{BBC Podcast Directory}

BBC PodCast Directory

@kbd{BBC Program Guide}

Display interactive BBC Program Guide.

@kbd{Baseball Game Index}

Display baseball Play By Play.

@kbd{Baseball Play By Play}

Display baseball Play By Play.

@kbd{Baseball scores}

Display baseball scores.

@kbd{Baseball standings}

Display MLB standings.

@kbd{Bing News}

Bing News results as RSS feed.

@kbd{Bing Search}

Bing results as RSS feed.

@kbd{BlogSearch Google}

Google Blog Search

@kbd{CNN Content }

CNN Content

@kbd{CNN Market Data }

CNN Money

@kbd{CNN headlines }

Retrieve and speak headline news from CNN.

@kbd{CNN technology }

CNN Technology news.

@kbd{CNNContent}

Filter down to CNN  content area.

@kbd{CNNPodCasts}

List CNN Podcast media links.

@kbd{Cartoon You Said It By Laxman}

Retrieve Cartoon Times Of India.

@kbd{Dictionary Lookup}

Dictionary Lookup

@kbd{Earthquakes}

Show table of recent quakes.

@kbd{EmacsWiki Search}

EmacsWiki Search

@kbd{Finance Google Portfolio}

Download and display portfolio from Google Finance.

@kbd{Finance Google Search}

Display content from Google Finance.

@kbd{Finance Google news}

Display content from Google Finance.

@kbd{G3 Sourcer URL}

Return Sourcerer URL.

@kbd{GCalendar Mobile}

Google Calendar XHTML version.

@kbd{Geek Linux Daily}

Play specified edition of Geek  Linux DailyShow

@kbd{GitHub Search}

Perform a GitHub Search.

@kbd{Google API Search}

Search Google APIDocs

@kbd{Google Books}

Google Books Search with text when available

@kbd{Google Feeds}

List  Google news Feeds.

@kbd{Google Glossary}

Google Glossary lookup.

@kbd{Google Hits}

Only show Google hits.

@kbd{Google Image Search}

Google Image Search

@kbd{Google Info View}

Do a Google search and get a Info view of results.

@kbd{Google Mobile Search}

Google Mobile Search

@kbd{Google News Search}

Search Google news.

@kbd{Google NewsPaper}

Retrieve and speak Google News Overview.

@kbd{Google Print}

Google Print Search

@kbd{Google Reader}

Google Reader

@kbd{Google Recent News Search}

Search Google news.

@kbd{Google Results}

Show just results and nav bar.

@kbd{Google Scholar}

Google Scholar Search

@kbd{Google TimeLine View}

Do a Google search and get a timeline view of results.

@kbd{Google Transcoder}

Transcode site via Google.

@kbd{Google WebQuotes}

Google WebQuotes.

@kbd{Google Webmaster Page Analysis}

Page Analysis From Google Webmaster tools.

@kbd{Google topical  News}

Display specified news feed.

@kbd{IToRSS}

Pull RSS  feed corresponding to an ITunes Podcast.

@kbd{Linux Today News}

Get news column from Linux Today.

@kbd{MDC Search}

Search MDC Wiki.

@kbd{MLB Scorecard}

Show MLB Scorecard.

@kbd{Market summary from Google}

Display financial market summary.

@kbd{Mobile BBC}

BBC Mobile Streams.

@kbd{Mobile Finance Google Search}

Display content from Google Finance.

@kbd{Money Content }

CNN Content

@kbd{Mozilla Developers Corner}

Pull specified resource from MDC.

@kbd{Multilingual dictionary via Google.}

Translate word using Google.
Source and target languages
are specified as two-letter language codes, e.g. en|de translates
from English to German

@kbd{NY Times Mobile}

NYTimes Mobile Site

@kbd{NY Times RSS Feeds}

Display browsable list of NY Times RSS Feeds.

@kbd{Official GoogleBlog Search}

Search within all official Google blogs.

@kbd{Old Time Radio}

This months Old Time Radio Programing

@kbd{On The Fly CSE}

Build a CSE on the fly and  use it to search.

@kbd{PHC Prairie Home Companion}

Play Prairie Home Companion

@kbd{Patent Search From Google}

Perform patent search via Google

@kbd{PodCast CNet}

Play Podcast from CNET

@kbd{Reader Subscription Search}

Search within feeds subscribed to in Google Reader.

@kbd{Recent BlogSearch Google}

Google Blog Search

@kbd{Recent YouTube Results}

YouTube Search Via Feeds

@kbd{Redhat Linux Show}

Play specified edition of Redhat Linux Show

@kbd{Reuters Finance}

Reuters Finance Lookup

@kbd{Seeking Alpha Stock Search}

Seeking Alpha search.

@kbd{Sign in to Google}

Login to Google.

@kbd{StreamWorld Radio}

Play radio stream.
See http://www.cbsradio.com/streaming/index.html for a list of CBS  stations that use StreamTheWorld.

@kbd{Tech News From CNet}

Display tech news from CNET

@kbd{Times Of India}

Retrieve Times Of India.
Set up URL rewrite rule to get print page.

@kbd{Translation Via Google}

Translate a Web page using google. Source and target languages
are specified as two-letter language codes, e.g. en|de translates
from English to German.

@kbd{Twitter Search}

Twitter search and display results feed.

@kbd{UPS Packages}

Display package tracking information from UPS.

@kbd{Weather forecast from Weather Underground}

Weather forecast from weather underground mobile.

@kbd{WordNet Search}

Look up term in WordNet.

@kbd{Yahoo Business News}

Retrieve and speak business  section from Yahoo Daily News.

@kbd{Yahoo Content By Content ID}

Retrieve and speak news section from Yahoo Daily News.

@kbd{Yahoo DailyNews}

Retrieve and speak DailyNewspage from  Yahoo Daily News.

@kbd{Yahoo Entertainment}

Retrieve and speak Entertainment section from Yahoo Daily News.

@kbd{Yahoo Health}

Retrieve and speak Health section from Yahoo Daily News.

@kbd{Yahoo Lifestyle}

Yahoo Lifestyle News.

@kbd{Yahoo Oddly}

Retrieve and speak Oddity section from Yahoo Daily News.

@kbd{Yahoo Politics}

Retrieve and speak Politics section from Yahoo Daily News.

@kbd{Yahoo RSS Feeds}

List Yahoo RSS Feeds.

@kbd{Yahoo SF Local}

Retrieve and speak Local section from Yahoo Daily News.

@kbd{Yahoo Science}

Retrieve and speak Science section from Yahoo Daily News.

@kbd{Yahoo Sports}

Entertainment news from Yahoo.

@kbd{Yahoo Technology  News}

Yahoo Technology News.

@kbd{Yahoo Top Stories}

Retrieve and speak Top Stories  section from Yahoo Daily News.

@kbd{Yahoo World News}

Yahoo World News.

@kbd{YouTube Results}

YouTube Search Via Feeds

@kbd{ask search mobile}

Mobile search using Ask.com

@kbd{fedex packages}

Display package tracking information from Fedex.

@kbd{html5IRC}

Show HTML5 IRC log.

@kbd{rss weather from wunderground}

Pull RSS weather feed for specified state/city.

@kbd{sourceforge Download}

Download specified file.

@kbd{sourceforge browse mirrors}

Retrieve download page  at Sourceforge for specified project.

@kbd{sourceforge project}

Open specified project page at SourceForge.

@kbd{w3c IRC Logs}

Use this to pull up the
archived  logs from the W3C IRC. You need to know the exact
name of the channel.

@kbd{w3c Lists}

Use this to pull up the
archived  mail from the W3C list. You need to know the exact
name of the list.

