
@node Emacspeak Keybindings from emacspeak-keymap
 @section Emacspeak Keybindings from emacspeak-keymap

@table @kbd
@item "
 emacspeak-speak-sexp-interactively

@item 0
 emacspeak-speak-predefined-window

@item 1
 emacspeak-speak-predefined-window

@item 2
 emacspeak-speak-predefined-window

@item 3
 emacspeak-speak-predefined-window

@item 4
 emacspeak-speak-predefined-window

@item 5
 emacspeak-speak-predefined-window

@item 6
 emacspeak-speak-predefined-window

@item 7
 emacspeak-speak-predefined-window

@item 8
 emacspeak-speak-predefined-window

@item 9
 emacspeak-speak-predefined-window

@item =
 emacspeak-speak-current-column

@item >
 emacspeak-speak-next-field

@item ?
 emacspeak-websearch-dispatch

@item @@
 emacspeak-speak-message-at-time

@item A
 emacspeak-appt-repeat-announcement

@item B
 emacspeak-speak-buffer-interactively

@item C
 emacspeak-customize

@item C-b
 emacspeak-bookshare

@item C-c
 emacspeak-clipboard-copy

@item C-d
 emacspeak-toggle-show-point

@item C-j
 emacspeak-hide-speak-block-sans-prefix

@item C-l
 emacspeak-speak-line-number

@item C-n
 emacspeak-speak-next-window

@item C-o
 emacspeak-ocr

@item C-p
 emacspeak-speak-previous-window

@item C-q
 emacspeak-toggle-comint-autospeak

@item C-s
 tts-restart

@item C-u
 emacspeak-feeds-browse

@item C-v
 view-mode

@item C-w
 emacspeak-speak-window-information

@item C-y
 emacspeak-clipboard-paste

@item DEL
 cd-tool

@item I
 emacspeak-speak-show-active-network-interfaces

@item L
 emacspeak-speak-line-interactively

@item M
 emacspeak-speak-minor-mode-line

@item N
 emacspeak-view-emacspeak-news

@item P
 emacspeak-speak-paragraph-interactively

@item R
 emacspeak-speak-rectangle

@item RET
 emacspeak-speak-continuously

@item SPC
 emacspeak-speak-header-line

@item T
 emacspeak-view-emacspeak-tips

@item TAB
 emacspeak-table-display-table-in-region

@item V
 emacspeak-speak-version

@item W
 emacspeak-tapestry-select-window-by-name

@item [
 emacspeak-speak-page

@item \
 emacspeak-toggle-speak-line-invert-filter

@item ]
 emacspeak-speak-page-interactively

@item ^
 emacspeak-filtertext

@item a
 emacspeak-speak-message-again

@item b
 emacspeak-speak-buffer

@item c
 emacspeak-speak-char

@item f
 emacspeak-speak-buffer-filename

@item g
 emacspeak-epub

@item h
 emacspeak-speak-help

@item i
 emacspeak-tabulate-region

@item j
 emacspeak-hide-or-expose-block

@item k
 emacspeak-speak-current-kill

@item l
 emacspeak-speak-line

@item m
 emacspeak-speak-mode-line

@item n
 emacspeak-speak-rest-of-buffer

@item o
 emacspeak-toggle-comint-output-monitor

@item p
 emacspeak-speak-paragraph

@item q
 emacspeak-toggle-speak-messages

@item r
 emacspeak-speak-region

@item s
 dtk-stop

@item t
 emacspeak-speak-time

@item u
 emacspeak-url-template-fetch

@item v
 view-register

@item w
 emacspeak-speak-word

@item @{
 emacspeak-speak-paragraph

@item |
 emacspeak-speak-line-set-column-filter

@item C-@@
 emacspeak-speak-current-mark

@item !
 emacspeak-speak-run-shell-command

@item %
 emacspeak-speak-current-percentage

@item &
 emacspeak-wizards-shell-command-on-current-file

@item '
 emacspeak-pianobar

@item (
 emacspeak-audio-setup

@item )
 emacspeak-sounds-select-theme

@item ,
 emacspeak-speak-browse-buffer

@item .
 dtk-notify-stop

@item /
 emacspeak-speak-this-buffer-other-window-display

@item :
 emacspeak-m-player-shuffle

@item ;
 emacspeak-multimedia

@item <
 emacspeak-speak-previous-field

@item C-a
 emacspeak-toggle-auditory-icons

@item C-e
 end-of-line

@item e
 end-of-line

@end table

@node Emacspeak Keybindings from emacspeak-dtk-submap
 @section Emacspeak Keybindings from emacspeak-dtk-submap

@table @kbd
@item ,
 dtk-toggle-punctuation-mode

@item 0
 dtk-set-predefined-speech-rate

@item 1
 dtk-set-predefined-speech-rate

@item 2
 dtk-set-predefined-speech-rate

@item 3
 dtk-set-predefined-speech-rate

@item 4
 dtk-set-predefined-speech-rate

@item 5
 dtk-set-predefined-speech-rate

@item 6
 dtk-set-predefined-speech-rate

@item 7
 dtk-set-predefined-speech-rate

@item 8
 dtk-set-predefined-speech-rate

@item 9
 dtk-set-predefined-speech-rate

@item C
 dtk-toggle-allcaps-beep

@item C-c
 dtk-cloud

@item C-d
 dectalk

@item C-e
 espeak

@item C-n
 dtk-notify-initialize

@item C-o
 outloud

@item C-s
 dtk-notify-shutdown

@item C-v
 outloud-32

@item L
 dtk-local-server

@item N
 dtk-set-next-language

@item P
 dtk-set-previous-language

@item R
 dtk-reset-state

@item RET
 dtk-set-chunk-separator-syntax

@item S
 dtk-set-language

@item SPC
 dtk-toggle-splitting-on-white-space

@item V
 tts-speak-version

@item a
 dtk-add-cleanup-pattern

@item c
 dtk-toggle-capitalization

@item d
 dtk-select-server

@item f
 dtk-set-character-scale

@item i
 emacspeak-toggle-audio-indentation

@item k
 emacspeak-toggle-character-echo

@item l
 emacspeak-toggle-line-echo

@item m
 emacspeak-speak-set-mode-punctuations

@item n
 dtk-toggle-speak-nonprinting-chars

@item o
 dtk-toggle-strip-octals

@item p
 dtk-set-punctuations

@item q
 dtk-toggle-quiet

@item r
 dtk-set-rate

@item s
 dtk-toggle-split-caps

@item t
 emacspeak-dial-dtk

@item v
 voice-lock-mode

@item w
 emacspeak-toggle-word-echo

@item z
 emacspeak-zap-tts

@end table

@node Emacspeak Keybindings from emacspeak-hyper-keymap
 @section Emacspeak Keybindings from emacspeak-hyper-keymap

@table @kbd
@item :
 emacspeak-wizards-view-buffers-filtered-by-m-player-mode

@item ;
 emacspeak-m-player-using-openal

@item B
 eww-list-bookmarks

@item C
 apu-chars

@item N
 emacspeak-npr-listing

@item a
 emacspeak-wizards-term

@item b
 eww-list-buffers

@item c
 browse-url-chromium

@item d
 magit-dispatch-popup

@item e
 gmaps

@item f
 emacspeak-webspace-freebase-search

@item g
 gnus

@item h
 emacspeak-org-capture-link

@item i
 ido-everywhere

@item j
 emacspeak-wizards-shell-toggle

@item k
 emacspeak-webspace-knowledge-search

@item l
 emacspeak-librivox

@item m
 vm

@item n
 emacspeak-npr-play-program

@item o
 other-frame

@item p
 emacspeak-wizards-pdf-open

@item q
 emacspeak-remote-quick-connect-to-server

@item r
 org-capture

@item s
 emacspeak-wizards-shell

@item t
 twit

@item u
 browse-url

@item v
 emacspeak-muggles-view/body

@end table

@node Emacspeak Keybindings from emacspeak-super-keymap
 @section Emacspeak Keybindings from emacspeak-super-keymap

@table @kbd
@item .
 auto-correct-update

@item R
 emacspeak-webspace-feed-reader

@item S
 soundscape-stop

@item b
 emacspeak-bbc

@item e
 elfeed

@item f
 emacspeak-feeds-lookup-and-view

@item h
 emacspeak-webspace-headlines-browse

@item i
 ciel-ci

@item j
 ido-imenu-anywhere

@item l
 emacspeak-m-player-locate-media

@item m
 emacspeak-wizards-view-buffers-filtered-by-this-mode

@item o
 ciel-co

@item p
 proced

@item r
 soundscape-restart

@item s
 soundscape

@item t
 soundscape-toggle

@item u
 soundscape-update-mood

@end table

@node Emacspeak Keybindings from emacspeak-alt-keymap
 @section Emacspeak Keybindings from emacspeak-alt-keymap

@table @kbd
@item ,
 emacspeak-eldoc-speak-doc

@item a
 emacspeak-feeds-atom-display

@item c
 emacspeak-wizards-view-buffers-filtered-by-this-mode

@item e
 eww

@item f
 emacspeak-feeds-find-feeds

@item l
 eww-open-file

@item m
 magit-status

@item n
 emacspeak-wizards-cycle-to-next-buffer

@item o
 emacspeak-feeds-opml-display

@item p
 emacspeak-wizards-cycle-to-previous-buffer

@item r
 emacspeak-feeds-rss-display

@item s
 emacspeak-wizards-tune-in-radio-search

@item t
 emacspeak-wizards-tune-in-radio-browse

@item u
 emacspeak-m-player-url

@end table

@node Emacspeak Keybindings from emacspeak-personal-keymap
 @section Emacspeak Keybindings from emacspeak-personal-keymap

@table @kbd
@item 3
 emacspeak-wizards-cycle-browser

@item =
 emacspeak-wizards-find-longest-line-in-region

@item DEL
 desktop-clear

@item Q
 emacspeak-wizards-yql-lookup

@item b
 battery

@item h
 emacspeak-wizards-how-many-matches

@item j
 emacspeak-jabber-popup-roster

@item m
 mspools-show

@item o
 emacspeak-wizards-occur-header-lines

@item q
 emacspeak-wizards-yql-quotes

@item r
 jabber-activity-switch-to

@item s
 emacspeak-emergency-tts-restart

@item t
 emacspeak-speak-telephone-directory

@item u
 emacspeak-wizards-units

@item v
 emacspeak-wizards-vc-viewer

@item |
 emacspeak-wizards-squeeze-blanks

@end table

@node Emacspeak Keybindings from emacspeak-personal-ctlx-keymap
 @section Emacspeak Keybindings from emacspeak-personal-ctlx-keymap

@table @kbd
@end table
