@c $Id$

@node Top
@top Emacspeak


This manual documents Emacspeak, a speech interface to Emacs.  The
manual is divided into the following chapters.

@menu
* Copying: Copyright.
* Announce: Announce.
* Introduction: Introduction.
* Installation: Installation.
* Basic Usage: Basic Usage.
* Audio Desktop: Audio Desktop.
* Voice Lock: Voice Lock.
* Using Online Help: Using Online Help.
* Emacs Packages:  Emacs Packages.
* Running Terminal Based Applications: Running Terminal Based Applications.
* Emacspeak Commands:  Emacspeak Commands.
* Emacspeak Customizations:  Emacspeak Customizations.
* TTS Servers:  TTS Servers.
* Acknowledgements: Acknowledgements.

Indices:

* Concept Index: Concept Index.
* Key Index: Key Index.
@end  menu
