@c $Id$
@macro MDash 
 ---
@end macro 

@macro NDash 
 -- 
@end macro 

@node Top
@top Emacspeak



This manual documents @b{Emacspeak, The Complete Audio Desktop}.
This document was last updated on @today{}.

@ifinfo 
The manual is divided into the following chapters. 
@end ifinfo

@menu
* Copying: Copyright.
* Announce: Announce.
* Background: Background.
* Introduction: Introduction.
* Installation: Installation.
* Basic Usage: Basic Usage.
* Audio Desktop: Audio Desktop.
* Voice Lock: Voice Lock.
* Using Online Help: Using Online Help.
* Emacs Packages:  Emacs Packages.
* Running Terminal Based Applications: Running Terminal Based Applications.
* Emacspeak Commands And Options:  Emacspeak Commands And Options.
* TTS Servers:  TTS Servers.
* Acknowledgments: Acknowledgments.

Indices:

* Concept Index: Concept Index.
* Key Index: Key Index.
@end  menu
