#!/bin/sh
#$Id$
#Description: Launch a TTS server on a remote host.
#Copyright (C) 1995 -- 2000, T. V. Raman 
# {{{  documentation

# Running TTS server remotely.
# }}}
remote=`cat $HOME/.emacspeak/.current-remote-hostname`
TCL=/usr/bin/tcl
OUTLOUD=$HOME/emacs/lisp/emacspeak/servers/outloud

ssh $remote  $TCL $OUTLOUD
