#!/usr/bin/perl -w
#$Id$
#Display Calendar invites in a readable form.
use strict;
my  %fields =qw(
                DTSTART  Start
DTEND End
DESCRIPTION Description
SUMMARY Summary
LOCATION Location
);
print "\n\n";
while (<>){
chomp;
my ($f, $v) =split(':');
  my $key=$fields{$f};
  print "$key:\t$v\n" if defined($key);
}
