#!/bin/sh
#for use in vm
#Description: Install  package wv to obtain wvText

cd /tmp
wmf=/tmp/mswordfile*.wmf
wordfile=mswordviewfile$$.doc
txtfile=mswordviewfile$$.txt
cat > $wordfile
wvText $wordfile $txtfile
cat   $txtfile 
/bin/rm $txtfile  $wmf
