(defun go-fish ()
  (interactive)
  (comint-run "/usr/games/go-fish")
  (unless emacspeak-comint-autospeak (emacspeak-toggle-comint-autospeak))
  (dtk-set-punctuations 'some)
  (when dtk-split-caps (dtk-toggle-split-caps))
  (emacspeak-icon 'open-object))
