#!/bin/sh
#Upload a release to github
#Usage:  $1 tagname $2 filename asset (tar.bz2)

. ${HOME}/.github_token
export PATH=$PATH:$GOPATH/bin
#first, tag this release 
github-release release --user tvraman --repo emacspeak \
--tag $1 --name "Release $1 " 
# Next, upload the tar.bz2 dist package 
github-release upload --user tvraman --repo emacspeak \
--tag $1 --name $2 --file $2

# Upload the latest NEWS   into releases 
github-release upload --user tvraman --repo emacspeak \
--tag $1 --name News-$2 --file ./etc/NEWS

echo "Released $1"
echo "Download URL: https://github.com/tvraman/emacspeak/releases/download/$1/$2"

# Final releases contain  an announcement file.
AText="./announcements/ANNOUNCE-$1.txt"
AHtml="./announcements/ANNOUNCE-$1.html"

test -f ${AText} &&  github-release upload --user tvraman --repo emacspeak \
--tag $1 --name $AText --file $AText



test -f ${AHtml} &&  github-release upload --user tvraman --repo emacspeak \
--tag $1 --name $AHtml --file $AHtml
