#!/bin/sh
# Play prompt  from outside Emacs
#Usage emsicon<icon>
l="$@"
pidof -q `which emacs` && \
emacsclient -n -e "(emacspeak-icon '$l)"   2>&1 > /dev/null ||
        paplay ${HOME}/emacs/lisp/emacspeak/sounds/chimes/$l.ogg
