#!/bin/sh
# Start Emacs and connect to the  daemon.
# Result: Emacs frame pops up on local (laptop for example).

export TERM=xterm
export DTK_PROGRAM=cloud-outloud
pidof emacs || emacs --daemon
emacsclient -c -a -F "'(name . \"Remote-Emacs\"))"'' &

