Document: emacspeak
Title: Debian emacspeak Manual
Author: <insert document author here>
Abstract: This manual describes what emacspeak is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/emacspeak/emacspeak.sgml.gz

Format: postscript
Files: /usr/share/doc/emacspeak/emacspeak.ps.gz

Format: text
Files: /usr/share/doc/emacspeak/emacspeak.text.gz

Format: HTML
Index: /usr/share/doc/emacspeak/html/index.html
Files: /usr/share/doc/emacspeak/html/*.html

  
