#!/bin/sh
#for use in vm
#Description: Install  package xlhtml to obtain ppthtml
#http://www.xlhtml.org
if which ppthtml > /dev/null
then
    tempfile=/tmp/ppthtml-$$.ppt
    cat > $tempfile
    ppthtml   $tempfile
    rm -f $tempfile
    exit 0
else
    echo "ppthtml not found --install package xlhtml from
#http://www.xlhtml.org."
    exit 1
fi
