#!/bin/sh
#$Id$
#

if which pdftotext 
then
    tempfile=/tmp/pdftotext-$$.pdf
    cat > $tempfile
    pdftotext $tempfile -
    rm -f $tempfile
else 
    echo "pdftotext not found --install package XPDF."
fi
