#!/bin/sh
#for use in vm
#Description: Install  package xlhtml to obtain xlhtml
#http://www.xlhtml.org
if which xlhtml > /dev/null
then
    tempfile=/tmp/xlhtml-$$.xls
    cat > $tempfile
    xlhtml -a -te  $tempfile
    rm -f $tempfile
    exit 0
else
    echo "xlhtml not found --install package xlhtml from
#http://www.xlhtml.org."
    exit 1
fi
